/*
 * This code has been automatically generated by aas-core-codegen.
 * Do NOT edit or append.
 */

using Aas = dummy; // renamed
using AasEnhancing = dummy.Enhancing; // renamed

using System.Collections.Generic; // can't alias
using System.Linq; // can't alias

using NUnit.Framework; // can't alias

namespace dummy.Tests
{
    public class TestEnhancing
    {
        class Enhancement
        {
            public readonly long SomeCustomId;

            public Enhancement(long someCustomId)
            {
                SomeCustomId = someCustomId;
            }
        }

        private static AasEnhancing.Enhancer<Enhancement> CreateEnhancer()
        {
            long lastCustomId = 0;

            var enhancementFactory = new System.Func<IClass, Enhancement>(
                delegate
                {
                    lastCustomId++;
                    return new Enhancement(lastCustomId);
                }
            );

            return new AasEnhancing.Enhancer<Enhancement>(enhancementFactory);
        }

        [Test]
        public void Test_StructuralFirst()
        {
            var instance = (
                Aas.Tests.CommonJsonization.LoadMaximalStructuralFirst()
            );

            var enhancer = CreateEnhancer();

            Assert.IsNull(enhancer.Unwrap(instance));

            var wrapped = enhancer.Wrap(instance);
            Assert.IsNotNull(wrapped);

            var idSet = new HashSet<long>();

            idSet.Add(enhancer.MustUnwrap(wrapped).SomeCustomId);
            idSet.UnionWith(
                wrapped
                    .Descend()
                    .Select(
                        (descendant) =>
                            enhancer.MustUnwrap(descendant).SomeCustomId
                        )
            );

            Assert.AreEqual(1, idSet.Min());
            Assert.AreEqual(idSet.Count, idSet.Max());
        }  // public void Test_StructuralFirst

        [Test]
        public void Test_StructuralSecond()
        {
            var instance = (
                Aas.Tests.CommonJsonization.LoadMaximalStructuralSecond()
            );

            var enhancer = CreateEnhancer();

            Assert.IsNull(enhancer.Unwrap(instance));

            var wrapped = enhancer.Wrap(instance);
            Assert.IsNotNull(wrapped);

            var idSet = new HashSet<long>();

            idSet.Add(enhancer.MustUnwrap(wrapped).SomeCustomId);
            idSet.UnionWith(
                wrapped
                    .Descend()
                    .Select(
                        (descendant) =>
                            enhancer.MustUnwrap(descendant).SomeCustomId
                        )
            );

            Assert.AreEqual(1, idSet.Min());
            Assert.AreEqual(idSet.Count, idSet.Max());
        }  // public void Test_StructuralSecond

        [Test]
        public void Test_MixedAbstractDescendantOne()
        {
            var instance = (
                Aas.Tests.CommonJsonization.LoadMaximalMixedAbstractDescendantOne()
            );

            var enhancer = CreateEnhancer();

            Assert.IsNull(enhancer.Unwrap(instance));

            var wrapped = enhancer.Wrap(instance);
            Assert.IsNotNull(wrapped);

            var idSet = new HashSet<long>();

            idSet.Add(enhancer.MustUnwrap(wrapped).SomeCustomId);
            idSet.UnionWith(
                wrapped
                    .Descend()
                    .Select(
                        (descendant) =>
                            enhancer.MustUnwrap(descendant).SomeCustomId
                        )
            );

            Assert.AreEqual(1, idSet.Min());
            Assert.AreEqual(idSet.Count, idSet.Max());
        }  // public void Test_MixedAbstractDescendantOne

        [Test]
        public void Test_MixedAbstractDescendantTwo()
        {
            var instance = (
                Aas.Tests.CommonJsonization.LoadMaximalMixedAbstractDescendantTwo()
            );

            var enhancer = CreateEnhancer();

            Assert.IsNull(enhancer.Unwrap(instance));

            var wrapped = enhancer.Wrap(instance);
            Assert.IsNotNull(wrapped);

            var idSet = new HashSet<long>();

            idSet.Add(enhancer.MustUnwrap(wrapped).SomeCustomId);
            idSet.UnionWith(
                wrapped
                    .Descend()
                    .Select(
                        (descendant) =>
                            enhancer.MustUnwrap(descendant).SomeCustomId
                        )
            );

            Assert.AreEqual(1, idSet.Min());
            Assert.AreEqual(idSet.Count, idSet.Max());
        }  // public void Test_MixedAbstractDescendantTwo

        [Test]
        public void Test_MixedConcreteWithDescendants()
        {
            var instance = (
                Aas.Tests.CommonJsonization.LoadMaximalMixedConcreteWithDescendants()
            );

            var enhancer = CreateEnhancer();

            Assert.IsNull(enhancer.Unwrap(instance));

            var wrapped = enhancer.Wrap(instance);
            Assert.IsNotNull(wrapped);

            var idSet = new HashSet<long>();

            idSet.Add(enhancer.MustUnwrap(wrapped).SomeCustomId);
            idSet.UnionWith(
                wrapped
                    .Descend()
                    .Select(
                        (descendant) =>
                            enhancer.MustUnwrap(descendant).SomeCustomId
                        )
            );

            Assert.AreEqual(1, idSet.Min());
            Assert.AreEqual(idSet.Count, idSet.Max());
        }  // public void Test_MixedConcreteWithDescendants

        [Test]
        public void Test_MixedConcreteWithDescendantsChild()
        {
            var instance = (
                Aas.Tests.CommonJsonization.LoadMaximalMixedConcreteWithDescendantsChild()
            );

            var enhancer = CreateEnhancer();

            Assert.IsNull(enhancer.Unwrap(instance));

            var wrapped = enhancer.Wrap(instance);
            Assert.IsNotNull(wrapped);

            var idSet = new HashSet<long>();

            idSet.Add(enhancer.MustUnwrap(wrapped).SomeCustomId);
            idSet.UnionWith(
                wrapped
                    .Descend()
                    .Select(
                        (descendant) =>
                            enhancer.MustUnwrap(descendant).SomeCustomId
                        )
            );

            Assert.AreEqual(1, idSet.Min());
            Assert.AreEqual(idSet.Count, idSet.Max());
        }  // public void Test_MixedConcreteWithDescendantsChild

        [Test]
        public void Test_MixedConcreteLeaf()
        {
            var instance = (
                Aas.Tests.CommonJsonization.LoadMaximalMixedConcreteLeaf()
            );

            var enhancer = CreateEnhancer();

            Assert.IsNull(enhancer.Unwrap(instance));

            var wrapped = enhancer.Wrap(instance);
            Assert.IsNotNull(wrapped);

            var idSet = new HashSet<long>();

            idSet.Add(enhancer.MustUnwrap(wrapped).SomeCustomId);
            idSet.UnionWith(
                wrapped
                    .Descend()
                    .Select(
                        (descendant) =>
                            enhancer.MustUnwrap(descendant).SomeCustomId
                        )
            );

            Assert.AreEqual(1, idSet.Min());
            Assert.AreEqual(idSet.Count, idSet.Max());
        }  // public void Test_MixedConcreteLeaf

        [Test]
        public void Test_ModelTypedFirst()
        {
            var instance = (
                Aas.Tests.CommonJsonization.LoadMaximalModelTypedFirst()
            );

            var enhancer = CreateEnhancer();

            Assert.IsNull(enhancer.Unwrap(instance));

            var wrapped = enhancer.Wrap(instance);
            Assert.IsNotNull(wrapped);

            var idSet = new HashSet<long>();

            idSet.Add(enhancer.MustUnwrap(wrapped).SomeCustomId);
            idSet.UnionWith(
                wrapped
                    .Descend()
                    .Select(
                        (descendant) =>
                            enhancer.MustUnwrap(descendant).SomeCustomId
                        )
            );

            Assert.AreEqual(1, idSet.Min());
            Assert.AreEqual(idSet.Count, idSet.Max());
        }  // public void Test_ModelTypedFirst

        [Test]
        public void Test_ModelTypedSecond()
        {
            var instance = (
                Aas.Tests.CommonJsonization.LoadMaximalModelTypedSecond()
            );

            var enhancer = CreateEnhancer();

            Assert.IsNull(enhancer.Unwrap(instance));

            var wrapped = enhancer.Wrap(instance);
            Assert.IsNotNull(wrapped);

            var idSet = new HashSet<long>();

            idSet.Add(enhancer.MustUnwrap(wrapped).SomeCustomId);
            idSet.UnionWith(
                wrapped
                    .Descend()
                    .Select(
                        (descendant) =>
                            enhancer.MustUnwrap(descendant).SomeCustomId
                        )
            );

            Assert.AreEqual(1, idSet.Min());
            Assert.AreEqual(idSet.Count, idSet.Max());
        }  // public void Test_ModelTypedSecond

        [Test]
        public void Test_Something()
        {
            var instance = (
                Aas.Tests.CommonJsonization.LoadMaximalSomething()
            );

            var enhancer = CreateEnhancer();

            Assert.IsNull(enhancer.Unwrap(instance));

            var wrapped = enhancer.Wrap(instance);
            Assert.IsNotNull(wrapped);

            var idSet = new HashSet<long>();

            idSet.Add(enhancer.MustUnwrap(wrapped).SomeCustomId);
            idSet.UnionWith(
                wrapped
                    .Descend()
                    .Select(
                        (descendant) =>
                            enhancer.MustUnwrap(descendant).SomeCustomId
                        )
            );

            Assert.AreEqual(1, idSet.Min());
            Assert.AreEqual(idSet.Count, idSet.Max());
        }  // public void Test_Something
    }  // class TestEnhancing
}  // namespace dummy.Tests

/*
 * This code has been automatically generated by aas-core-codegen.
 * Do NOT edit or append.
 */
