/*
 * This code has been automatically generated by aas-core-codegen.
 * Do NOT edit or append.
 */

using Aas = dummy;  // renamed

// We need to use System.MemoryExtension.SequenceEqual.
using System;  // can't alias
using System.Linq;  // can't alias

using NUnit.Framework;  // can't alias

namespace dummy.Tests
{
    public class TestCopying
    {
        internal class DeepEqualiser
            : Aas.Visitation.AbstractTransformerWithContext<Aas.IClass, bool>
        {
            /// <summary>Compare two byte spans for equal content.</summary>
            /// <remarks>
            /// <c>byte[]</c> implicitly converts to <c>ReadOnlySpan</c>.
            /// See: https://stackoverflow.com/a/48599119/1600678
            /// </remarks>
            private static bool ByteSpansEqual(
                System.ReadOnlySpan<byte> that,
                System.ReadOnlySpan<byte> other)
            {
                return that.SequenceEqual(other);
            }

            public override bool TransformStructuralFirst(
                Aas.IStructuralFirst that,
                Aas.IClass other)
            {
                if (!(other is Aas.StructuralFirst casted))
                {
                    return false;
                }

                return (
                    that.UniqueToFirst == casted.UniqueToFirst);
            }

            public override bool TransformStructuralSecond(
                Aas.IStructuralSecond that,
                Aas.IClass other)
            {
                if (!(other is Aas.StructuralSecond casted))
                {
                    return false;
                }

                return (
                    that.UniqueToSecond == casted.UniqueToSecond);
            }

            public override bool TransformMixedAbstractDescendantOne(
                Aas.IMixedAbstractDescendantOne that,
                Aas.IClass other)
            {
                if (!(other is Aas.MixedAbstractDescendantOne casted))
                {
                    return false;
                }

                return (
                    that.UniqueToAbstractDescendantOne == casted.UniqueToAbstractDescendantOne);
            }

            public override bool TransformMixedAbstractDescendantTwo(
                Aas.IMixedAbstractDescendantTwo that,
                Aas.IClass other)
            {
                if (!(other is Aas.MixedAbstractDescendantTwo casted))
                {
                    return false;
                }

                return (
                    that.UniqueToAbstractDescendantTwo == casted.UniqueToAbstractDescendantTwo);
            }

            public override bool TransformMixedConcreteWithDescendants(
                Aas.IMixedConcreteWithDescendants that,
                Aas.IClass other)
            {
                if (!(other is Aas.MixedConcreteWithDescendants casted))
                {
                    return false;
                }

                return (
                    that.SomeBaseProperty == casted.SomeBaseProperty);
            }

            public override bool TransformMixedConcreteWithDescendantsChild(
                Aas.IMixedConcreteWithDescendantsChild that,
                Aas.IClass other)
            {
                if (!(other is Aas.MixedConcreteWithDescendantsChild casted))
                {
                    return false;
                }

                return (
                    that.SomeBaseProperty == casted.SomeBaseProperty
                    && that.SomeChildProperty == casted.SomeChildProperty);
            }

            public override bool TransformMixedConcreteLeaf(
                Aas.IMixedConcreteLeaf that,
                Aas.IClass other)
            {
                if (!(other is Aas.MixedConcreteLeaf casted))
                {
                    return false;
                }

                return (
                    that.UniqueToConcreteLeaf == casted.UniqueToConcreteLeaf);
            }

            public override bool TransformModelTypedFirst(
                Aas.IModelTypedFirst that,
                Aas.IClass other)
            {
                if (!(other is Aas.ModelTypedFirst casted))
                {
                    return false;
                }

                return (
                    that.SomeProperty == casted.SomeProperty);
            }

            public override bool TransformModelTypedSecond(
                Aas.IModelTypedSecond that,
                Aas.IClass other)
            {
                if (!(other is Aas.ModelTypedSecond casted))
                {
                    return false;
                }

                return (
                    that.SomeProperty == casted.SomeProperty);
            }

            public override bool TransformSomething(
                Aas.ISomething that,
                Aas.IClass other)
            {
                if (!(other is Aas.Something casted))
                {
                    return false;
                }

                return (
                    Transform(
                        that.StructuralProperty.Underlying,
                        casted.StructuralProperty.Underlying)
                    && Transform(
                        that.MixedProperty.Underlying,
                        casted.MixedProperty.Underlying)
                    && Transform(
                        that.ModelTypedProperty.Underlying,
                        casted.ModelTypedProperty.Underlying)
                    && that.ListStructuralProperty.Count == casted.ListStructuralProperty.Count
                    && (
                        that.ListStructuralProperty
                            .Zip(
                                casted.ListStructuralProperty,
                                (t, c) => Transform(t.Underlying, c.Underlying))
                            .All(item => item))
                    && that.ListMixedProperty.Count == casted.ListMixedProperty.Count
                    && (
                        that.ListMixedProperty
                            .Zip(
                                casted.ListMixedProperty,
                                (t, c) => Transform(t.Underlying, c.Underlying))
                            .All(item => item))
                    && that.ListModelTypedProperty.Count == casted.ListModelTypedProperty.Count
                    && (
                        that.ListModelTypedProperty
                            .Zip(
                                casted.ListModelTypedProperty,
                                (t, c) => Transform(t.Underlying, c.Underlying))
                            .All(item => item))
                    && (
                        Transform(
                            that.TupleProperty.Item1.Underlying,
                            casted.TupleProperty.Item1.Underlying)
                        && Transform(
                            that.TupleProperty.Item2.Underlying,
                            casted.TupleProperty.Item2.Underlying)
                        && Transform(
                            that.TupleProperty.Item3.Underlying,
                            casted.TupleProperty.Item3.Underlying))
                    && (that.OptionalStructuralProperty != null && casted.OptionalStructuralProperty != null)
                        ? Transform(
                                that.OptionalStructuralProperty.Underlying,
                                casted.OptionalStructuralProperty.Underlying)
                        : that.OptionalStructuralProperty == null && casted.OptionalStructuralProperty == null
                    && (that.OptionalMixedProperty != null && casted.OptionalMixedProperty != null)
                        ? Transform(
                                that.OptionalMixedProperty.Underlying,
                                casted.OptionalMixedProperty.Underlying)
                        : that.OptionalMixedProperty == null && casted.OptionalMixedProperty == null
                    && (that.OptionalModelTypedProperty != null && casted.OptionalModelTypedProperty != null)
                        ? Transform(
                                that.OptionalModelTypedProperty.Underlying,
                                casted.OptionalModelTypedProperty.Underlying)
                        : that.OptionalModelTypedProperty == null && casted.OptionalModelTypedProperty == null);
            }
        }  // internal class DeepEqualiser

        private static readonly DeepEqualiser DeepEqualiserInstance = new DeepEqualiser();

        private static bool StructuralFirstShallowEquals(
            Aas.StructuralFirst that,
            Aas.StructuralFirst other)
        {
            return that.UniqueToFirst == other.UniqueToFirst;
        }

        private static bool StructuralSecondShallowEquals(
            Aas.StructuralSecond that,
            Aas.StructuralSecond other)
        {
            return that.UniqueToSecond == other.UniqueToSecond;
        }

        private static bool MixedAbstractDescendantOneShallowEquals(
            Aas.MixedAbstractDescendantOne that,
            Aas.MixedAbstractDescendantOne other)
        {
            return (
                that.UniqueToAbstractDescendantOne == other.UniqueToAbstractDescendantOne);
        }

        private static bool MixedAbstractDescendantTwoShallowEquals(
            Aas.MixedAbstractDescendantTwo that,
            Aas.MixedAbstractDescendantTwo other)
        {
            return (
                that.UniqueToAbstractDescendantTwo == other.UniqueToAbstractDescendantTwo);
        }

        private static bool MixedConcreteWithDescendantsShallowEquals(
            Aas.MixedConcreteWithDescendants that,
            Aas.MixedConcreteWithDescendants other)
        {
            return that.SomeBaseProperty == other.SomeBaseProperty;
        }

        private static bool MixedConcreteWithDescendantsChildShallowEquals(
            Aas.MixedConcreteWithDescendantsChild that,
            Aas.MixedConcreteWithDescendantsChild other)
        {
            return (
                that.SomeBaseProperty == other.SomeBaseProperty
                && that.SomeChildProperty == other.SomeChildProperty);
        }

        private static bool MixedConcreteLeafShallowEquals(
            Aas.MixedConcreteLeaf that,
            Aas.MixedConcreteLeaf other)
        {
            return that.UniqueToConcreteLeaf == other.UniqueToConcreteLeaf;
        }

        private static bool ModelTypedFirstShallowEquals(
            Aas.ModelTypedFirst that,
            Aas.ModelTypedFirst other)
        {
            return that.SomeProperty == other.SomeProperty;
        }

        private static bool ModelTypedSecondShallowEquals(
            Aas.ModelTypedSecond that,
            Aas.ModelTypedSecond other)
        {
            return that.SomeProperty == other.SomeProperty;
        }

        private static bool SomethingShallowEquals(
            Aas.Something that,
            Aas.Something other)
        {
            return (
                that.StructuralProperty == other.StructuralProperty
                && that.MixedProperty == other.MixedProperty
                && that.ModelTypedProperty == other.ModelTypedProperty
                && that.ListStructuralProperty == other.ListStructuralProperty
                && that.ListMixedProperty == other.ListMixedProperty
                && that.ListModelTypedProperty == other.ListModelTypedProperty
                && that.TupleProperty == other.TupleProperty
                && that.OptionalStructuralProperty == other.OptionalStructuralProperty
                && that.OptionalMixedProperty == other.OptionalMixedProperty
                && that.OptionalModelTypedProperty == other.OptionalModelTypedProperty);
        }

        private static bool StructuralFirstDeepEquals(
            Aas.StructuralFirst that,
            Aas.StructuralFirst other)
        {
            return DeepEqualiserInstance.Transform(that, other);
        }

        private static bool StructuralSecondDeepEquals(
            Aas.StructuralSecond that,
            Aas.StructuralSecond other)
        {
            return DeepEqualiserInstance.Transform(that, other);
        }

        private static bool MixedAbstractDescendantOneDeepEquals(
            Aas.MixedAbstractDescendantOne that,
            Aas.MixedAbstractDescendantOne other)
        {
            return DeepEqualiserInstance.Transform(that, other);
        }

        private static bool MixedAbstractDescendantTwoDeepEquals(
            Aas.MixedAbstractDescendantTwo that,
            Aas.MixedAbstractDescendantTwo other)
        {
            return DeepEqualiserInstance.Transform(that, other);
        }

        private static bool MixedConcreteWithDescendantsDeepEquals(
            Aas.MixedConcreteWithDescendants that,
            Aas.MixedConcreteWithDescendants other)
        {
            return DeepEqualiserInstance.Transform(that, other);
        }

        private static bool MixedConcreteWithDescendantsChildDeepEquals(
            Aas.MixedConcreteWithDescendantsChild that,
            Aas.MixedConcreteWithDescendantsChild other)
        {
            return DeepEqualiserInstance.Transform(that, other);
        }

        private static bool MixedConcreteLeafDeepEquals(
            Aas.MixedConcreteLeaf that,
            Aas.MixedConcreteLeaf other)
        {
            return DeepEqualiserInstance.Transform(that, other);
        }

        private static bool ModelTypedFirstDeepEquals(
            Aas.ModelTypedFirst that,
            Aas.ModelTypedFirst other)
        {
            return DeepEqualiserInstance.Transform(that, other);
        }

        private static bool ModelTypedSecondDeepEquals(
            Aas.ModelTypedSecond that,
            Aas.ModelTypedSecond other)
        {
            return DeepEqualiserInstance.Transform(that, other);
        }

        private static bool SomethingDeepEquals(
            Aas.Something that,
            Aas.Something other)
        {
            return DeepEqualiserInstance.Transform(that, other);
        }

        [Test]
        public void Test_StructuralFirst_shallow_copy()
        {
            Aas.StructuralFirst instance = (
                Aas.Tests.CommonJsonization.LoadMaximalStructuralFirst());

            var instanceCopy = Aas.Copying.Shallow(instance);

            Assert.IsTrue(
                StructuralFirstShallowEquals(
                    instance, instanceCopy),
                "StructuralFirst");
        }  // public void Test_StructuralFirst_shallow_copy

        [Test]
        public void Test_StructuralFirst_deep_copy()
        {
            Aas.StructuralFirst instance = (
                Aas.Tests.CommonJsonization.LoadMaximalStructuralFirst());

            var instanceCopy = Aas.Copying.Deep(instance);

            Assert.IsTrue(
                StructuralFirstDeepEquals(
                    instance, instanceCopy),
                "StructuralFirst");
        }  // public void Test_StructuralFirst_deep_copy

        [Test]
        public void Test_StructuralSecond_shallow_copy()
        {
            Aas.StructuralSecond instance = (
                Aas.Tests.CommonJsonization.LoadMaximalStructuralSecond());

            var instanceCopy = Aas.Copying.Shallow(instance);

            Assert.IsTrue(
                StructuralSecondShallowEquals(
                    instance, instanceCopy),
                "StructuralSecond");
        }  // public void Test_StructuralSecond_shallow_copy

        [Test]
        public void Test_StructuralSecond_deep_copy()
        {
            Aas.StructuralSecond instance = (
                Aas.Tests.CommonJsonization.LoadMaximalStructuralSecond());

            var instanceCopy = Aas.Copying.Deep(instance);

            Assert.IsTrue(
                StructuralSecondDeepEquals(
                    instance, instanceCopy),
                "StructuralSecond");
        }  // public void Test_StructuralSecond_deep_copy

        [Test]
        public void Test_MixedAbstractDescendantOne_shallow_copy()
        {
            Aas.MixedAbstractDescendantOne instance = (
                Aas.Tests.CommonJsonization.LoadMaximalMixedAbstractDescendantOne());

            var instanceCopy = Aas.Copying.Shallow(instance);

            Assert.IsTrue(
                MixedAbstractDescendantOneShallowEquals(
                    instance, instanceCopy),
                "MixedAbstractDescendantOne");
        }  // public void Test_MixedAbstractDescendantOne_shallow_copy

        [Test]
        public void Test_MixedAbstractDescendantOne_deep_copy()
        {
            Aas.MixedAbstractDescendantOne instance = (
                Aas.Tests.CommonJsonization.LoadMaximalMixedAbstractDescendantOne());

            var instanceCopy = Aas.Copying.Deep(instance);

            Assert.IsTrue(
                MixedAbstractDescendantOneDeepEquals(
                    instance, instanceCopy),
                "MixedAbstractDescendantOne");
        }  // public void Test_MixedAbstractDescendantOne_deep_copy

        [Test]
        public void Test_MixedAbstractDescendantTwo_shallow_copy()
        {
            Aas.MixedAbstractDescendantTwo instance = (
                Aas.Tests.CommonJsonization.LoadMaximalMixedAbstractDescendantTwo());

            var instanceCopy = Aas.Copying.Shallow(instance);

            Assert.IsTrue(
                MixedAbstractDescendantTwoShallowEquals(
                    instance, instanceCopy),
                "MixedAbstractDescendantTwo");
        }  // public void Test_MixedAbstractDescendantTwo_shallow_copy

        [Test]
        public void Test_MixedAbstractDescendantTwo_deep_copy()
        {
            Aas.MixedAbstractDescendantTwo instance = (
                Aas.Tests.CommonJsonization.LoadMaximalMixedAbstractDescendantTwo());

            var instanceCopy = Aas.Copying.Deep(instance);

            Assert.IsTrue(
                MixedAbstractDescendantTwoDeepEquals(
                    instance, instanceCopy),
                "MixedAbstractDescendantTwo");
        }  // public void Test_MixedAbstractDescendantTwo_deep_copy

        [Test]
        public void Test_MixedConcreteWithDescendants_shallow_copy()
        {
            Aas.MixedConcreteWithDescendants instance = (
                Aas.Tests.CommonJsonization.LoadMaximalMixedConcreteWithDescendants());

            var instanceCopy = Aas.Copying.Shallow(instance);

            Assert.IsTrue(
                MixedConcreteWithDescendantsShallowEquals(
                    instance, instanceCopy),
                "MixedConcreteWithDescendants");
        }  // public void Test_MixedConcreteWithDescendants_shallow_copy

        [Test]
        public void Test_MixedConcreteWithDescendants_deep_copy()
        {
            Aas.MixedConcreteWithDescendants instance = (
                Aas.Tests.CommonJsonization.LoadMaximalMixedConcreteWithDescendants());

            var instanceCopy = Aas.Copying.Deep(instance);

            Assert.IsTrue(
                MixedConcreteWithDescendantsDeepEquals(
                    instance, instanceCopy),
                "MixedConcreteWithDescendants");
        }  // public void Test_MixedConcreteWithDescendants_deep_copy

        [Test]
        public void Test_MixedConcreteWithDescendantsChild_shallow_copy()
        {
            Aas.MixedConcreteWithDescendantsChild instance = (
                Aas.Tests.CommonJsonization.LoadMaximalMixedConcreteWithDescendantsChild());

            var instanceCopy = Aas.Copying.Shallow(instance);

            Assert.IsTrue(
                MixedConcreteWithDescendantsChildShallowEquals(
                    instance, instanceCopy),
                "MixedConcreteWithDescendantsChild");
        }  // public void Test_MixedConcreteWithDescendantsChild_shallow_copy

        [Test]
        public void Test_MixedConcreteWithDescendantsChild_deep_copy()
        {
            Aas.MixedConcreteWithDescendantsChild instance = (
                Aas.Tests.CommonJsonization.LoadMaximalMixedConcreteWithDescendantsChild());

            var instanceCopy = Aas.Copying.Deep(instance);

            Assert.IsTrue(
                MixedConcreteWithDescendantsChildDeepEquals(
                    instance, instanceCopy),
                "MixedConcreteWithDescendantsChild");
        }  // public void Test_MixedConcreteWithDescendantsChild_deep_copy

        [Test]
        public void Test_MixedConcreteLeaf_shallow_copy()
        {
            Aas.MixedConcreteLeaf instance = (
                Aas.Tests.CommonJsonization.LoadMaximalMixedConcreteLeaf());

            var instanceCopy = Aas.Copying.Shallow(instance);

            Assert.IsTrue(
                MixedConcreteLeafShallowEquals(
                    instance, instanceCopy),
                "MixedConcreteLeaf");
        }  // public void Test_MixedConcreteLeaf_shallow_copy

        [Test]
        public void Test_MixedConcreteLeaf_deep_copy()
        {
            Aas.MixedConcreteLeaf instance = (
                Aas.Tests.CommonJsonization.LoadMaximalMixedConcreteLeaf());

            var instanceCopy = Aas.Copying.Deep(instance);

            Assert.IsTrue(
                MixedConcreteLeafDeepEquals(
                    instance, instanceCopy),
                "MixedConcreteLeaf");
        }  // public void Test_MixedConcreteLeaf_deep_copy

        [Test]
        public void Test_ModelTypedFirst_shallow_copy()
        {
            Aas.ModelTypedFirst instance = (
                Aas.Tests.CommonJsonization.LoadMaximalModelTypedFirst());

            var instanceCopy = Aas.Copying.Shallow(instance);

            Assert.IsTrue(
                ModelTypedFirstShallowEquals(
                    instance, instanceCopy),
                "ModelTypedFirst");
        }  // public void Test_ModelTypedFirst_shallow_copy

        [Test]
        public void Test_ModelTypedFirst_deep_copy()
        {
            Aas.ModelTypedFirst instance = (
                Aas.Tests.CommonJsonization.LoadMaximalModelTypedFirst());

            var instanceCopy = Aas.Copying.Deep(instance);

            Assert.IsTrue(
                ModelTypedFirstDeepEquals(
                    instance, instanceCopy),
                "ModelTypedFirst");
        }  // public void Test_ModelTypedFirst_deep_copy

        [Test]
        public void Test_ModelTypedSecond_shallow_copy()
        {
            Aas.ModelTypedSecond instance = (
                Aas.Tests.CommonJsonization.LoadMaximalModelTypedSecond());

            var instanceCopy = Aas.Copying.Shallow(instance);

            Assert.IsTrue(
                ModelTypedSecondShallowEquals(
                    instance, instanceCopy),
                "ModelTypedSecond");
        }  // public void Test_ModelTypedSecond_shallow_copy

        [Test]
        public void Test_ModelTypedSecond_deep_copy()
        {
            Aas.ModelTypedSecond instance = (
                Aas.Tests.CommonJsonization.LoadMaximalModelTypedSecond());

            var instanceCopy = Aas.Copying.Deep(instance);

            Assert.IsTrue(
                ModelTypedSecondDeepEquals(
                    instance, instanceCopy),
                "ModelTypedSecond");
        }  // public void Test_ModelTypedSecond_deep_copy

        [Test]
        public void Test_Something_shallow_copy()
        {
            Aas.Something instance = (
                Aas.Tests.CommonJsonization.LoadMaximalSomething());

            var instanceCopy = Aas.Copying.Shallow(instance);

            Assert.IsTrue(
                SomethingShallowEquals(
                    instance, instanceCopy),
                "Something");
        }  // public void Test_Something_shallow_copy

        [Test]
        public void Test_Something_deep_copy()
        {
            Aas.Something instance = (
                Aas.Tests.CommonJsonization.LoadMaximalSomething());

            var instanceCopy = Aas.Copying.Deep(instance);

            Assert.IsTrue(
                SomethingDeepEquals(
                    instance, instanceCopy),
                "Something");
        }  // public void Test_Something_deep_copy
    }  // class TestCopying
}  // namespace dummy.Tests

/*
 * This code has been automatically generated by aas-core-codegen.
 * Do NOT edit or append.
 */
