/*
 * This code has been automatically generated by aas-core-codegen.
 * Do NOT edit or append.
 */

package dummy.jsonization;

import dummy.common.*;
import dummy.reporting.Reporting;
import dummy.types.enums.*;
import dummy.types.impl.*;
import dummy.types.model.*;
import dummy.stringification.Stringification;
import dummy.visitation.AbstractTransformer;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.JsonNodeFactory;
import com.fasterxml.jackson.databind.node.ObjectNode;
import java.util.*;
import java.util.function.Function;

/**
 * Provide de/serialization of meta-model classes to/from JSON.
 *
 * <p>We can not use one-pass deserialization for JSON since the object
 * properties do not have fixed order, and hence we can not read
 * {@code modelType} property ahead of the remaining properties.
 */
public class Jsonization {
    /**
     * Implement the deserialization of meta-model classes from JSON nodes.
     *
     * <p>The implementation propagates an {@link Reporting.Error} instead
     * of relying on exceptions. Under the assumption that incorrect data is much
     * less frequent than correct data, this makes the deserialization more
     * efficient.
     *
     * However, we do not want to force the client to deal with
     * the {@link Reporting.Error} class as this is not intuitive. Therefore
     * we distinguish the implementation, realized in
     * {@link _DeserializeImplementation}, and the facade given in
     * {@link Deserialize} class.
     */
    private static class _DeserializeImplementation {
      /** Convert {@code value} to a string.
       * @param node JSON node to be parsed
       */
      private static Reporting.Result<String> tryStringFrom(JsonNode value) {
        if (!value.isTextual()) {
          final Reporting.Error error = new Reporting.Error(
            "Expected a JsonValue of String, but got " + value.getNodeType());
          return Reporting.Result.failure(error);
        }
        return Reporting.Result.success(value.asText());
      }

      /** Convert {@code value} to a boolean.
       * @param node JSON node to be parsed
       */
      private static Reporting.Result<Boolean> tryBooleanFrom(JsonNode value) {
        if (!value.isBoolean()) {
          final Reporting.Error error = new Reporting.Error(
            "Expected a JsonValue of Boolean, but got " + value.getNodeType());
          return Reporting.Result.failure(error);
        }
        return Reporting.Result.success(value.asBoolean());
      }

      /** Convert {@code value} to a long 64-bit integer.
       * @param node JSON node to be parsed
       */
      private static Reporting.Result<Long> tryLongFrom(JsonNode value) {
        if (!value.isIntegralNumber()) {
          final Reporting.Error error = new Reporting.Error(
            "Expected a JsonValue of Long, but got " + value.getNodeType());
          return Reporting.Result.failure(error);
        }
        return Reporting.Result.success(value.asLong());
      }

      /** Convert {@code value} to a double-precision 64-bit float.
       * @param node JSON node to be parsed
       */
      private static Reporting.Result<Double> tryDoubleFrom(JsonNode value) {
        if (!value.isFloatingPointNumber()) {
          final Reporting.Error error = new Reporting.Error(
            "Expected a JsonValue of Double, but got " + value.getNodeType());
          return Reporting.Result.failure(error);
        }
        return Reporting.Result.success(value.asDouble());
      }

      private static Reporting.Result<byte[]> tryBytesFrom(JsonNode value) {
        if (!value.isTextual()) {
          final Reporting.Error error = new Reporting.Error(
            "Expected a JsonValue of String, but got " + value.getNodeType());
          return Reporting.Result.failure(error);
        }
        final byte[] decodedData;
        Base64.Decoder decoder = Base64.getDecoder();

        try {
          decodedData = decoder.decode(value.textValue());
        } catch (Exception exception) {
          final Reporting.Error error = new Reporting.Error(
            "Expected Base-64 encoded bytes, but the conversion failed " +
              "because: " + exception.getMessage());
          return Reporting.Result.failure(error);
        }

        return Reporting.Result.success(decodedData);
      }

      /**
       * Parse every item of {@code array} with {@code parseItem}.
       *
       * @param array JSON array to be parsed
       * @param parseItem to parse a single item of the array
       */
      private static <T> Reporting.Result<List<T>> parseArray(
        JsonNode array,
        Function<JsonNode, Reporting.Result<? extends T>> parseItem) {
        final List<T> result = new ArrayList<>(array.size());
        int index = 0;
        for (JsonNode item : array) {
          if (item == null) {
            final Reporting.Error error = new Reporting.Error(
              "Expected a non-null item, but got a null");
            error.prependSegment(
              new Reporting.IndexSegment(index));
            return Reporting.Result.failure(error);
          }

          final Reporting.Result<? extends T> parsedItemResult = parseItem.apply(item);
          if (parsedItemResult.isError()) {
            parsedItemResult.getError()
              .prependSegment(
              new Reporting.IndexSegment(index));
            return Reporting.Result.failure(parsedItemResult.getError());
          }

          result.add(parsedItemResult.getResult());
          index++;
        }

        return Reporting.Result.success(result);
      }

      /**
       * Parse {@code array} as a tuple of 2 item(s), each de-serialized
       * with the corresponding {@code parseItemI}.
       *
       * @param array JSON array to be parsed
       */
      private static <T1, T2> Reporting.Result<Tuple2<T1, T2>> parseTuple2(
        JsonNode array,
        Function<JsonNode, Reporting.Result<? extends T1>> parseItem1,
        Function<JsonNode, Reporting.Result<? extends T2>> parseItem2) {
        if (array.size() != 2) {
          final Reporting.Error error = new Reporting.Error(
            "Expected exactly 2 item(s), but got " + array.size());
          return Reporting.Result.failure(error);
        }

        final Reporting.Result<? extends T1> item1Result =
          parseItem1.apply(array.get(0));
        if (item1Result.isError()) {
          item1Result.getError()
            .prependSegment(new Reporting.IndexSegment(0));
          return Reporting.Result.failure(item1Result.getError());
        }

        final Reporting.Result<? extends T2> item2Result =
          parseItem2.apply(array.get(1));
        if (item2Result.isError()) {
          item2Result.getError()
            .prependSegment(new Reporting.IndexSegment(1));
          return Reporting.Result.failure(item2Result.getError());
        }

        return Reporting.Result.success(
          new Tuple2<>(
            item1Result.getResult(),
            item2Result.getResult()));
      }

      /**
       * Parse {@code array} as a tuple of 6 item(s), each de-serialized
       * with the corresponding {@code parseItemI}.
       *
       * @param array JSON array to be parsed
       */
      private static <T1, T2, T3, T4, T5, T6> Reporting.Result<Tuple6<T1, T2, T3, T4, T5, T6>> parseTuple6(
        JsonNode array,
        Function<JsonNode, Reporting.Result<? extends T1>> parseItem1,
        Function<JsonNode, Reporting.Result<? extends T2>> parseItem2,
        Function<JsonNode, Reporting.Result<? extends T3>> parseItem3,
        Function<JsonNode, Reporting.Result<? extends T4>> parseItem4,
        Function<JsonNode, Reporting.Result<? extends T5>> parseItem5,
        Function<JsonNode, Reporting.Result<? extends T6>> parseItem6) {
        if (array.size() != 6) {
          final Reporting.Error error = new Reporting.Error(
            "Expected exactly 6 item(s), but got " + array.size());
          return Reporting.Result.failure(error);
        }

        final Reporting.Result<? extends T1> item1Result =
          parseItem1.apply(array.get(0));
        if (item1Result.isError()) {
          item1Result.getError()
            .prependSegment(new Reporting.IndexSegment(0));
          return Reporting.Result.failure(item1Result.getError());
        }

        final Reporting.Result<? extends T2> item2Result =
          parseItem2.apply(array.get(1));
        if (item2Result.isError()) {
          item2Result.getError()
            .prependSegment(new Reporting.IndexSegment(1));
          return Reporting.Result.failure(item2Result.getError());
        }

        final Reporting.Result<? extends T3> item3Result =
          parseItem3.apply(array.get(2));
        if (item3Result.isError()) {
          item3Result.getError()
            .prependSegment(new Reporting.IndexSegment(2));
          return Reporting.Result.failure(item3Result.getError());
        }

        final Reporting.Result<? extends T4> item4Result =
          parseItem4.apply(array.get(3));
        if (item4Result.isError()) {
          item4Result.getError()
            .prependSegment(new Reporting.IndexSegment(3));
          return Reporting.Result.failure(item4Result.getError());
        }

        final Reporting.Result<? extends T5> item5Result =
          parseItem5.apply(array.get(4));
        if (item5Result.isError()) {
          item5Result.getError()
            .prependSegment(new Reporting.IndexSegment(4));
          return Reporting.Result.failure(item5Result.getError());
        }

        final Reporting.Result<? extends T6> item6Result =
          parseItem6.apply(array.get(5));
        if (item6Result.isError()) {
          item6Result.getError()
            .prependSegment(new Reporting.IndexSegment(5));
          return Reporting.Result.failure(item6Result.getError());
        }

        return Reporting.Result.success(
          new Tuple6<>(
            item1Result.getResult(),
            item2Result.getResult(),
            item3Result.getResult(),
            item4Result.getResult(),
            item5Result.getResult(),
            item6Result.getResult()));
      }

      /**
       * Deserialize the enumeration Result from the {@code node}.
       *
       * @param node JSON node to be parsed
       */
      private static Reporting.Result<Result> tryResultFrom(JsonNode node) {
        final Reporting.Result<String> textResult = tryStringFrom(node);
        if (textResult.isError()) {
          return textResult.castTo(Result.class);
        }
        final Optional<Result> result = Stringification.resultFromString(textResult.getResult());
        if (!result.isPresent()) {
          final Reporting.Error error = new Reporting.Error("Not a valid JSON representation of Result");
          return Reporting.Result.failure(error);
        }
        return Reporting.Result.success(result.get());
      }

      /**
       * Deserialize an instance of IAbstractItem by dispatching
       * based on {@code modelType} property of the {@code node}.
       *
       * @param node JSON node to be parsed
       */
      public static Reporting.Result<? extends IAbstractItem> tryIAbstractItemFrom(JsonNode node) {
        if (node == null || !node.isObject()) {
          final Reporting.Error error = new Reporting.Error(
            "Expected a JsonObject, but got " + (node == null ? "null" : node.getNodeType()));
          return Reporting.Result.failure(error);
        }

        final JsonNode modelTypeNode = node.get("modelType");
        if (modelTypeNode == null) {
          final Reporting.Error error = new Reporting.Error(
              "Expected a model type, but none is present");
          return Reporting.Result.failure(error);
        }
        final Reporting.Result<String> modelTypeResult = tryStringFrom(modelTypeNode);
        if (modelTypeResult.isError()) {
          return modelTypeResult.castTo(IAbstractItem.class);
        }

        switch (modelTypeResult.getResult())
        {
          case "AnotherItem": {
            return tryAnotherItemFrom(node);
        }  case "SomeItem": {
            return trySomeItemFrom(node);
        }  default: {
            final Reporting.Error error = new Reporting.Error(
              "Unexpected model type for IAbstractItem: " + modelTypeResult.getResult());
            return Reporting.Result.failure(error);
          }
        }
      }

      /**
       * Deserialize an instance of SomeItem from {@param node}.
       *
       * @param node JSON node to be parsed
       * @param elem Error, if any, during the deserialization
       */
      private static Reporting.Result<SomeItem> trySomeItemFrom(JsonNode node) {
        if (node == null || !node.isObject()) {
          final Reporting.Error error = new Reporting.Error(
            "Expected a JsonObject, but got " + (node == null ? "null" : node.getNodeType()));
          return Reporting.Result.failure(error);
        }

        String theName = null;

        String modelType = null;

        for (Iterator<Map.Entry<String, JsonNode>> iterator = node.fields(); iterator.hasNext(); ) {
          Map.Entry<String, JsonNode> currentNode = iterator.next();

          switch (currentNode.getKey()) {
            case "name": {
              if (currentNode.getValue() == null) {
                continue;
              }

              final Reporting.Result<? extends String> theNameResult = tryStringFrom(currentNode.getValue());
              if (theNameResult.isError()) {
                theNameResult.getError()
                  .prependSegment(new Reporting.NameSegment("name"));
                return theNameResult.castTo(SomeItem.class);
              }
              theName = theNameResult.getResult();
              break;
            }
            case "modelType": {
              if (currentNode.getValue() == null) {
                final Reporting.Error error = new Reporting.Error(
                  "Expected a model type, but got null");
                return Reporting.Result.failure(error);
              }
              final Reporting.Result<? extends String> modelTypeResult =
                _DeserializeImplementation.tryStringFrom(currentNode.getValue());
              if (modelTypeResult.isError()) {
                modelTypeResult.getError()
                  .prependSegment(new Reporting.NameSegment("modelType"));
                return modelTypeResult.castTo(SomeItem.class);
              }
              modelType = modelTypeResult.getResult();

              if (!modelType.equals("SomeItem")) {
                final Reporting.Error error = new Reporting.Error(
                  "Expected the model type 'SomeItem', " +
                  "but got '" + modelType + "'");
                  error.prependSegment(new Reporting.NameSegment("modelType"));
                  return Reporting.Result.failure(error);
              }
              break;
            }
            default: {
              final Reporting.Error error = new Reporting.Error(
                "Unexpected property: " + currentNode.getKey());
              return Reporting.Result.failure(error);
            }
          }
        }

        if (modelType == null) {
          final Reporting.Error error = new Reporting.Error(
            "Required property \"modelType\" is missing");
          return Reporting.Result.failure(error);
        }

        if (theName == null) {
          final Reporting.Error error = new Reporting.Error(
            "Required property \"name\" is missing");
          return Reporting.Result.failure(error);
        }

        return Reporting.Result.success(new SomeItem(
          theName));
      }

      /**
       * Deserialize an instance of AnotherItem from {@param node}.
       *
       * @param node JSON node to be parsed
       * @param elem Error, if any, during the deserialization
       */
      private static Reporting.Result<AnotherItem> tryAnotherItemFrom(JsonNode node) {
        if (node == null || !node.isObject()) {
          final Reporting.Error error = new Reporting.Error(
            "Expected a JsonObject, but got " + (node == null ? "null" : node.getNodeType()));
          return Reporting.Result.failure(error);
        }

        Long theSerialNumber = null;

        String modelType = null;

        for (Iterator<Map.Entry<String, JsonNode>> iterator = node.fields(); iterator.hasNext(); ) {
          Map.Entry<String, JsonNode> currentNode = iterator.next();

          switch (currentNode.getKey()) {
            case "serialNumber": {
              if (currentNode.getValue() == null) {
                continue;
              }

              final Reporting.Result<? extends Long> theSerialNumberResult = tryLongFrom(currentNode.getValue());
              if (theSerialNumberResult.isError()) {
                theSerialNumberResult.getError()
                  .prependSegment(new Reporting.NameSegment("serialNumber"));
                return theSerialNumberResult.castTo(AnotherItem.class);
              }
              theSerialNumber = theSerialNumberResult.getResult();
              break;
            }
            case "modelType": {
              if (currentNode.getValue() == null) {
                final Reporting.Error error = new Reporting.Error(
                  "Expected a model type, but got null");
                return Reporting.Result.failure(error);
              }
              final Reporting.Result<? extends String> modelTypeResult =
                _DeserializeImplementation.tryStringFrom(currentNode.getValue());
              if (modelTypeResult.isError()) {
                modelTypeResult.getError()
                  .prependSegment(new Reporting.NameSegment("modelType"));
                return modelTypeResult.castTo(AnotherItem.class);
              }
              modelType = modelTypeResult.getResult();

              if (!modelType.equals("AnotherItem")) {
                final Reporting.Error error = new Reporting.Error(
                  "Expected the model type 'AnotherItem', " +
                  "but got '" + modelType + "'");
                  error.prependSegment(new Reporting.NameSegment("modelType"));
                  return Reporting.Result.failure(error);
              }
              break;
            }
            default: {
              final Reporting.Error error = new Reporting.Error(
                "Unexpected property: " + currentNode.getKey());
              return Reporting.Result.failure(error);
            }
          }
        }

        if (modelType == null) {
          final Reporting.Error error = new Reporting.Error(
            "Required property \"modelType\" is missing");
          return Reporting.Result.failure(error);
        }

        if (theSerialNumber == null) {
          final Reporting.Error error = new Reporting.Error(
            "Required property \"serialNumber\" is missing");
          return Reporting.Result.failure(error);
        }

        return Reporting.Result.success(new AnotherItem(
          theSerialNumber));
      }

      /**
       * Deserialize an instance of Something from {@param node}.
       *
       * @param node JSON node to be parsed
       * @param elem Error, if any, during the deserialization
       */
      private static Reporting.Result<Something> trySomethingFrom(JsonNode node) {
        if (node == null || !node.isObject()) {
          final Reporting.Error error = new Reporting.Error(
            "Expected a JsonObject, but got " + (node == null ? "null" : node.getNodeType()));
          return Reporting.Result.failure(error);
        }

        Tuple2<String, Long> thePair = null;
        Tuple2<IAbstractItem, IAbstractItem> theItems = null;
        Tuple6<
          Long,
          ISomeItem,
          IAbstractItem,
          ISomeItem,
          Long,
          Result> theTricky = null;

        for (Iterator<Map.Entry<String, JsonNode>> iterator = node.fields(); iterator.hasNext(); ) {
          Map.Entry<String, JsonNode> currentNode = iterator.next();

          switch (currentNode.getKey()) {
            case "pair": {
              if (currentNode.getValue() == null) {
                continue;
              }

              final JsonNode arrayPair = currentNode.getValue();
              if (!arrayPair.isArray()) {
                final Reporting.Error error = new Reporting.Error(
                  "Expected a JsonArray, but got " + arrayPair.getNodeType());
                error.prependSegment(
                  new Reporting.NameSegment(
                    "pair"));
                return Reporting.Result.failure(error);
              }
              final Reporting.Result<Tuple2<String, Long>> thePairResult = parseTuple2(
                arrayPair,
                _DeserializeImplementation::tryStringFrom,
                _DeserializeImplementation::tryLongFrom);
              if (thePairResult.isError()) {
                thePairResult.getError()
                  .prependSegment(
                    new Reporting.NameSegment(
                      "pair"));
                return thePairResult.castTo(Something.class);
              }
              thePair = thePairResult.getResult();
              break;
            }
            case "items": {
              if (currentNode.getValue() == null) {
                continue;
              }

              final JsonNode arrayItems = currentNode.getValue();
              if (!arrayItems.isArray()) {
                final Reporting.Error error = new Reporting.Error(
                  "Expected a JsonArray, but got " + arrayItems.getNodeType());
                error.prependSegment(
                  new Reporting.NameSegment(
                    "items"));
                return Reporting.Result.failure(error);
              }
              final Reporting.Result<Tuple2<IAbstractItem, IAbstractItem>> theItemsResult = parseTuple2(
                arrayItems,
                _DeserializeImplementation::tryIAbstractItemFrom,
                _DeserializeImplementation::tryIAbstractItemFrom);
              if (theItemsResult.isError()) {
                theItemsResult.getError()
                  .prependSegment(
                    new Reporting.NameSegment(
                      "items"));
                return theItemsResult.castTo(Something.class);
              }
              theItems = theItemsResult.getResult();
              break;
            }
            case "tricky": {
              if (currentNode.getValue() == null) {
                continue;
              }

              final JsonNode arrayTricky = currentNode.getValue();
              if (!arrayTricky.isArray()) {
                final Reporting.Error error = new Reporting.Error(
                  "Expected a JsonArray, but got " + arrayTricky.getNodeType());
                error.prependSegment(
                  new Reporting.NameSegment(
                    "tricky"));
                return Reporting.Result.failure(error);
              }
              final Reporting.Result<Tuple6<
                Long,
                ISomeItem,
                IAbstractItem,
                ISomeItem,
                Long,
                Result>> theTrickyResult = parseTuple6(
                arrayTricky,
                _DeserializeImplementation::tryLongFrom,
                _DeserializeImplementation::trySomeItemFrom,
                _DeserializeImplementation::tryIAbstractItemFrom,
                _DeserializeImplementation::trySomeItemFrom,
                _DeserializeImplementation::tryLongFrom,
                _DeserializeImplementation::tryResultFrom);
              if (theTrickyResult.isError()) {
                theTrickyResult.getError()
                  .prependSegment(
                    new Reporting.NameSegment(
                      "tricky"));
                return theTrickyResult.castTo(Something.class);
              }
              theTricky = theTrickyResult.getResult();
              break;
            }
            default: {
              final Reporting.Error error = new Reporting.Error(
                "Unexpected property: " + currentNode.getKey());
              return Reporting.Result.failure(error);
            }
          }
        }

        if (thePair == null) {
          final Reporting.Error error = new Reporting.Error(
            "Required property \"pair\" is missing");
          return Reporting.Result.failure(error);
        }

        if (theItems == null) {
          final Reporting.Error error = new Reporting.Error(
            "Required property \"items\" is missing");
          return Reporting.Result.failure(error);
        }

        if (theTricky == null) {
          final Reporting.Error error = new Reporting.Error(
            "Required property \"tricky\" is missing");
          return Reporting.Result.failure(error);
        }

        return Reporting.Result.success(new Something(
          thePair,
          theItems,
          theTricky));
      }
    }

    /**
    * Represent a critical error during the deserialization.
    */
    @SuppressWarnings("serial")
      public static class DeserializeException extends RuntimeException {
        private final String path;
        private final String reason;

        public DeserializeException(String path, String reason) {
          super(reason + " at: " + ("".equals(path) ? "the beginning" : path));
          this.path = path;
          this.reason = reason;
        }

        public Optional<String> getPath() {
          return Optional.ofNullable(path);
        }

        public Optional<String> getReason() {
          return Optional.ofNullable(reason);
        }
      }

    /**
     * Deserialize instances of meta-model classes from JSON nodes.
     *
     * Here is an example how to parse an instance of IAbstractItem:
     * <pre>{@code
     * String someString = "... some JSON ...";
     * ObjectMapper objectMapper = new ObjectMapper();
     * JsonNode node = objectMapper.readTree(someString);
     * IAbstractItem anInstance = Deserialize.deserializeIAbstractItem(
     *   node);
     * }</pre>
     */
    public static class Deserialize
    {
      /**
       * Deserialize an instance of Result from {@code node}.
       *
       * @param node JSON node to be parsed
       */
      public static Result deserializeResult(JsonNode node) {
        final Reporting.Result<? extends Result> result =
          _DeserializeImplementation.tryResultFrom(
            node);

        return result.onError(error -> {
          throw new DeserializeException(
            Reporting.generateJsonPath(error.getPathSegments()),
            error.getCause());
        });
      }

      /**
       * Deserialize an instance of IAbstractItem from {@code node}.
       *
       * @param node JSON node to be parsed
       */
      public static IAbstractItem deserializeIAbstractItem(JsonNode node) {
        final Reporting.Result<? extends IAbstractItem> result =
          _DeserializeImplementation.tryIAbstractItemFrom(
            node);

        return result.onError(error -> {
          throw new DeserializeException(
            Reporting.generateJsonPath(error.getPathSegments()),
            error.getCause());
        });
      }

      /**
       * Deserialize an instance of SomeItem from {@code node}.
       *
       * @param node JSON node to be parsed
       */
      public static SomeItem deserializeSomeItem(JsonNode node) {
        final Reporting.Result<? extends SomeItem> result =
          _DeserializeImplementation.trySomeItemFrom(
            node);

        return result.onError(error -> {
          throw new DeserializeException(
            Reporting.generateJsonPath(error.getPathSegments()),
            error.getCause());
        });
      }

      /**
       * Deserialize an instance of AnotherItem from {@code node}.
       *
       * @param node JSON node to be parsed
       */
      public static AnotherItem deserializeAnotherItem(JsonNode node) {
        final Reporting.Result<? extends AnotherItem> result =
          _DeserializeImplementation.tryAnotherItemFrom(
            node);

        return result.onError(error -> {
          throw new DeserializeException(
            Reporting.generateJsonPath(error.getPathSegments()),
            error.getCause());
        });
      }

      /**
       * Deserialize an instance of Something from {@code node}.
       *
       * @param node JSON node to be parsed
       */
      public static Something deserializeSomething(JsonNode node) {
        final Reporting.Result<? extends Something> result =
          _DeserializeImplementation.trySomethingFrom(
            node);

        return result.onError(error -> {
          throw new DeserializeException(
            Reporting.generateJsonPath(error.getPathSegments()),
            error.getCause());
        });
      }
    }

    private static class _Transformer extends AbstractTransformer<JsonNode> {
      /**
       * Convert {@code that} 64-bit long integer to a JSON value.
       *
       * @param that value to be converted
       */
      private static JsonNode toJsonNode(Long that) {
        // We need to check that we can perform a lossless conversion.
        long primitiveThat = that.longValue();
        if ((long)((double)primitiveThat) != primitiveThat) {
          throw new IllegalArgumentException(
            "The number can not be losslessly represented in JSON: " + that);
        }
        return JsonNodeFactory.instance.numberNode(that);
      }

      /**
       * Convert {@code that} byte array to a JSON value.
       *
       * @param that value to be converted
       */
      private static JsonNode bytesToJsonNode(byte[] that) {
        return JsonNodeFactory.instance.textNode(
          Base64.getEncoder().encodeToString(that));
      }

      /**
       * Serialize every item of {@code items} with {@code serializeItem} into
       * a JSON array.
       *
       * @param items to be serialized
       * @param serializeItem to serialize a single item of {@code items}
       */
      private static <T> ArrayNode serializeArray(
        Iterable<T> items,
        Function<T, JsonNode> serializeItem) {
        final ArrayNode result = JsonNodeFactory.instance.arrayNode();
        for (T item : items) {
          result.add(
            serializeItem.apply(item));
        }
        return result;
      }

      /**
       * Serialize each item of {@code value} with the corresponding
       * {@code serializeItemI} into a JSON array.
       */
      private static <T1, T2> ArrayNode serializeTuple2(
        Tuple2<T1, T2> value,
        Function<T1, JsonNode> serializeItem1,
        Function<T2, JsonNode> serializeItem2) {
        final ArrayNode result = JsonNodeFactory.instance.arrayNode();
        result.add(
          serializeItem1.apply(value.item1()));
        result.add(
          serializeItem2.apply(value.item2()));
        return result;
      }

      /**
       * Serialize each item of {@code value} with the corresponding
       * {@code serializeItemI} into a JSON array.
       */
      private static <T1, T2, T3, T4, T5, T6> ArrayNode serializeTuple6(
        Tuple6<T1, T2, T3, T4, T5, T6> value,
        Function<T1, JsonNode> serializeItem1,
        Function<T2, JsonNode> serializeItem2,
        Function<T3, JsonNode> serializeItem3,
        Function<T4, JsonNode> serializeItem4,
        Function<T5, JsonNode> serializeItem5,
        Function<T6, JsonNode> serializeItem6) {
        final ArrayNode result = JsonNodeFactory.instance.arrayNode();
        result.add(
          serializeItem1.apply(value.item1()));
        result.add(
          serializeItem2.apply(value.item2()));
        result.add(
          serializeItem3.apply(value.item3()));
        result.add(
          serializeItem4.apply(value.item4()));
        result.add(
          serializeItem5.apply(value.item5()));
        result.add(
          serializeItem6.apply(value.item6()));
        return result;
      }

      @Override
      public JsonNode transformSomeItem(
        ISomeItem that
      ) {
        final ObjectNode result = JsonNodeFactory.instance.objectNode();

        result.put("name", JsonNodeFactory.instance.textNode(
          that.getName()));

        result.put("modelType", "SomeItem");

        return result;
      }

      @Override
      public JsonNode transformAnotherItem(
        IAnotherItem that
      ) {
        final ObjectNode result = JsonNodeFactory.instance.objectNode();

        result.set("serialNumber", _Transformer.toJsonNode(
          that.getSerialNumber()));

        result.put("modelType", "AnotherItem");

        return result;
      }

      @Override
      public JsonNode transformSomething(
        ISomething that
      ) {
        final ObjectNode result = JsonNodeFactory.instance.objectNode();

        final ArrayNode arrayPair = serializeTuple2(
          that.getPair(),
          JsonNodeFactory.instance::textNode,
          _Transformer::toJsonNode);
        result.set("pair", arrayPair);

        final ArrayNode arrayItems = serializeTuple2(
          that.getItems(),
          this::transform,
          this::transform);
        result.set("items", arrayItems);

        final ArrayNode arrayTricky = serializeTuple6(
          that.getTricky(),
          _Transformer::toJsonNode,
          this::transform,
          this::transform,
          this::transform,
          _Transformer::toJsonNode,
          Serialize::resultToJsonValue);
        result.set("tricky", arrayTricky);

        return result;
      }
    }

    /**
     * Serialize instances of meta-model classes to JSON elements.
     *
     * Here is an example how to serialize an instance of IAbstractItem:
     * <pre>{@code
     * IAbstractItem anInstance = new IAbstractItem(
     *     // ... some constructor arguments ...
     * );
     * JsonNode element = Jsonization.Serialize.toJsonObject(
     *     anInstance));
     * }</pre>
     */
    public static class Serialize
    {
      private static final _Transformer transformer = new _Transformer();

      /**
       * Serialize an instance of the meta-model into a JSON object.
       */
      public static JsonNode toJsonObject(IClass that) {
        return transformer.transform(that);
      }

      /**
       * Serialize a literal of Result into a JSON string.
       */
      public static JsonNode resultToJsonValue(Result that) {
        return JsonNodeFactory.instance.textNode(Stringification.mustToString(that));
      }
    }
}

/*
 * This code has been automatically generated by aas-core-codegen.
 * Do NOT edit or append.
 */
