package aastesting

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.

import (
	"fmt"
	"path"
	aasjsonization "github.com/dummy-works/dummy/jsonization"
	aastypes "github.com/dummy-works/dummy/types"
)

// Load a maximal example of [aastypes.IStructuralFirst] from
// the test data directory.
//
// If there is any error, panic.
func MustLoadMaximalStructuralFirst(
) (result aastypes.IStructuralFirst) {
	pth := path.Join(
		TestDataDir,
		"Json",
		"Expected",
		"StructuralFirst",
		"maximal.json",
	)

	jsonable := MustReadJsonable(pth)

	instance, err := aasjsonization.StructuralFirstFromJsonable(
		jsonable,
	)
	if err != nil {
		panic(
			fmt.Sprintf(
				"Failed to de-serialize an instance of IStructuralFirst " +
				"from %s: %s",
				pth, err.Error(),
			),
		)
	}
	var ok bool
	result, ok = instance.(aastypes.IStructuralFirst)
	if !ok {
		panic(
			fmt.Sprintf(
				"Expected to find an instance of IStructuralFirst at %s, " +
				"but got an instance of %T: %v",
				pth, instance, instance,
			),
		)
	}
	return
}

// Load a minimal example of [aastypes.IStructuralFirst] from
// the test data directory.
//
// If there is any error, panic.
func MustLoadMinimalStructuralFirst(
) (result aastypes.IStructuralFirst) {
	pth := path.Join(
		TestDataDir,
		"Json",
		"Expected",
		"StructuralFirst",
		"minimal.json",
	)

	jsonable := MustReadJsonable(pth)

	instance, err := aasjsonization.StructuralFirstFromJsonable(
		jsonable,
	)
	if err != nil {
		panic(
			fmt.Sprintf(
				"Failed to de-serialize an instance of IStructuralFirst " +
				"from %s: %s",
				pth, err.Error(),
			),
		)
	}
	var ok bool
	result, ok = instance.(aastypes.IStructuralFirst)
	if !ok {
		panic(
			fmt.Sprintf(
				"Expected to find an instance of IStructuralFirst at %s, " +
				"but got an instance of %T: %v",
				pth, instance, instance,
			),
		)
	}
	return
}

// Load a maximal example of [aastypes.IStructuralSecond] from
// the test data directory.
//
// If there is any error, panic.
func MustLoadMaximalStructuralSecond(
) (result aastypes.IStructuralSecond) {
	pth := path.Join(
		TestDataDir,
		"Json",
		"Expected",
		"StructuralSecond",
		"maximal.json",
	)

	jsonable := MustReadJsonable(pth)

	instance, err := aasjsonization.StructuralSecondFromJsonable(
		jsonable,
	)
	if err != nil {
		panic(
			fmt.Sprintf(
				"Failed to de-serialize an instance of IStructuralSecond " +
				"from %s: %s",
				pth, err.Error(),
			),
		)
	}
	var ok bool
	result, ok = instance.(aastypes.IStructuralSecond)
	if !ok {
		panic(
			fmt.Sprintf(
				"Expected to find an instance of IStructuralSecond at %s, " +
				"but got an instance of %T: %v",
				pth, instance, instance,
			),
		)
	}
	return
}

// Load a minimal example of [aastypes.IStructuralSecond] from
// the test data directory.
//
// If there is any error, panic.
func MustLoadMinimalStructuralSecond(
) (result aastypes.IStructuralSecond) {
	pth := path.Join(
		TestDataDir,
		"Json",
		"Expected",
		"StructuralSecond",
		"minimal.json",
	)

	jsonable := MustReadJsonable(pth)

	instance, err := aasjsonization.StructuralSecondFromJsonable(
		jsonable,
	)
	if err != nil {
		panic(
			fmt.Sprintf(
				"Failed to de-serialize an instance of IStructuralSecond " +
				"from %s: %s",
				pth, err.Error(),
			),
		)
	}
	var ok bool
	result, ok = instance.(aastypes.IStructuralSecond)
	if !ok {
		panic(
			fmt.Sprintf(
				"Expected to find an instance of IStructuralSecond at %s, " +
				"but got an instance of %T: %v",
				pth, instance, instance,
			),
		)
	}
	return
}

// Load a maximal example of [aastypes.IMixedAbstractDescendantOne] from
// the test data directory.
//
// If there is any error, panic.
func MustLoadMaximalMixedAbstractDescendantOne(
) (result aastypes.IMixedAbstractDescendantOne) {
	pth := path.Join(
		TestDataDir,
		"Json",
		"Expected",
		"MixedAbstractDescendantOne",
		"maximal.json",
	)

	jsonable := MustReadJsonable(pth)

	instance, err := aasjsonization.MixedAbstractDescendantOneFromJsonable(
		jsonable,
	)
	if err != nil {
		panic(
			fmt.Sprintf(
				"Failed to de-serialize an instance of IMixedAbstractDescendantOne " +
				"from %s: %s",
				pth, err.Error(),
			),
		)
	}
	var ok bool
	result, ok = instance.(aastypes.IMixedAbstractDescendantOne)
	if !ok {
		panic(
			fmt.Sprintf(
				"Expected to find an instance of IMixedAbstractDescendantOne at %s, " +
				"but got an instance of %T: %v",
				pth, instance, instance,
			),
		)
	}
	return
}

// Load a minimal example of [aastypes.IMixedAbstractDescendantOne] from
// the test data directory.
//
// If there is any error, panic.
func MustLoadMinimalMixedAbstractDescendantOne(
) (result aastypes.IMixedAbstractDescendantOne) {
	pth := path.Join(
		TestDataDir,
		"Json",
		"Expected",
		"MixedAbstractDescendantOne",
		"minimal.json",
	)

	jsonable := MustReadJsonable(pth)

	instance, err := aasjsonization.MixedAbstractDescendantOneFromJsonable(
		jsonable,
	)
	if err != nil {
		panic(
			fmt.Sprintf(
				"Failed to de-serialize an instance of IMixedAbstractDescendantOne " +
				"from %s: %s",
				pth, err.Error(),
			),
		)
	}
	var ok bool
	result, ok = instance.(aastypes.IMixedAbstractDescendantOne)
	if !ok {
		panic(
			fmt.Sprintf(
				"Expected to find an instance of IMixedAbstractDescendantOne at %s, " +
				"but got an instance of %T: %v",
				pth, instance, instance,
			),
		)
	}
	return
}

// Load a maximal example of [aastypes.IMixedAbstractDescendantTwo] from
// the test data directory.
//
// If there is any error, panic.
func MustLoadMaximalMixedAbstractDescendantTwo(
) (result aastypes.IMixedAbstractDescendantTwo) {
	pth := path.Join(
		TestDataDir,
		"Json",
		"Expected",
		"MixedAbstractDescendantTwo",
		"maximal.json",
	)

	jsonable := MustReadJsonable(pth)

	instance, err := aasjsonization.MixedAbstractDescendantTwoFromJsonable(
		jsonable,
	)
	if err != nil {
		panic(
			fmt.Sprintf(
				"Failed to de-serialize an instance of IMixedAbstractDescendantTwo " +
				"from %s: %s",
				pth, err.Error(),
			),
		)
	}
	var ok bool
	result, ok = instance.(aastypes.IMixedAbstractDescendantTwo)
	if !ok {
		panic(
			fmt.Sprintf(
				"Expected to find an instance of IMixedAbstractDescendantTwo at %s, " +
				"but got an instance of %T: %v",
				pth, instance, instance,
			),
		)
	}
	return
}

// Load a minimal example of [aastypes.IMixedAbstractDescendantTwo] from
// the test data directory.
//
// If there is any error, panic.
func MustLoadMinimalMixedAbstractDescendantTwo(
) (result aastypes.IMixedAbstractDescendantTwo) {
	pth := path.Join(
		TestDataDir,
		"Json",
		"Expected",
		"MixedAbstractDescendantTwo",
		"minimal.json",
	)

	jsonable := MustReadJsonable(pth)

	instance, err := aasjsonization.MixedAbstractDescendantTwoFromJsonable(
		jsonable,
	)
	if err != nil {
		panic(
			fmt.Sprintf(
				"Failed to de-serialize an instance of IMixedAbstractDescendantTwo " +
				"from %s: %s",
				pth, err.Error(),
			),
		)
	}
	var ok bool
	result, ok = instance.(aastypes.IMixedAbstractDescendantTwo)
	if !ok {
		panic(
			fmt.Sprintf(
				"Expected to find an instance of IMixedAbstractDescendantTwo at %s, " +
				"but got an instance of %T: %v",
				pth, instance, instance,
			),
		)
	}
	return
}

// Load a maximal example of [aastypes.IMixedConcreteWithDescendants] from
// the test data directory.
//
// If there is any error, panic.
func MustLoadMaximalMixedConcreteWithDescendants(
) (result aastypes.IMixedConcreteWithDescendants) {
	pth := path.Join(
		TestDataDir,
		"Json",
		"Expected",
		"MixedConcreteWithDescendants",
		"maximal.json",
	)

	jsonable := MustReadJsonable(pth)

	instance, err := aasjsonization.MixedConcreteWithDescendantsFromJsonable(
		jsonable,
	)
	if err != nil {
		panic(
			fmt.Sprintf(
				"Failed to de-serialize an instance of IMixedConcreteWithDescendants " +
				"from %s: %s",
				pth, err.Error(),
			),
		)
	}
	var ok bool
	result, ok = instance.(aastypes.IMixedConcreteWithDescendants)
	if !ok {
		panic(
			fmt.Sprintf(
				"Expected to find an instance of IMixedConcreteWithDescendants at %s, " +
				"but got an instance of %T: %v",
				pth, instance, instance,
			),
		)
	}
	return
}

// Load a minimal example of [aastypes.IMixedConcreteWithDescendants] from
// the test data directory.
//
// If there is any error, panic.
func MustLoadMinimalMixedConcreteWithDescendants(
) (result aastypes.IMixedConcreteWithDescendants) {
	pth := path.Join(
		TestDataDir,
		"Json",
		"Expected",
		"MixedConcreteWithDescendants",
		"minimal.json",
	)

	jsonable := MustReadJsonable(pth)

	instance, err := aasjsonization.MixedConcreteWithDescendantsFromJsonable(
		jsonable,
	)
	if err != nil {
		panic(
			fmt.Sprintf(
				"Failed to de-serialize an instance of IMixedConcreteWithDescendants " +
				"from %s: %s",
				pth, err.Error(),
			),
		)
	}
	var ok bool
	result, ok = instance.(aastypes.IMixedConcreteWithDescendants)
	if !ok {
		panic(
			fmt.Sprintf(
				"Expected to find an instance of IMixedConcreteWithDescendants at %s, " +
				"but got an instance of %T: %v",
				pth, instance, instance,
			),
		)
	}
	return
}

// Load a maximal example of [aastypes.IMixedConcreteWithDescendantsChild] from
// the test data directory.
//
// If there is any error, panic.
func MustLoadMaximalMixedConcreteWithDescendantsChild(
) (result aastypes.IMixedConcreteWithDescendantsChild) {
	pth := path.Join(
		TestDataDir,
		"Json",
		"Expected",
		"MixedConcreteWithDescendantsChild",
		"maximal.json",
	)

	jsonable := MustReadJsonable(pth)

	instance, err := aasjsonization.MixedConcreteWithDescendantsChildFromJsonable(
		jsonable,
	)
	if err != nil {
		panic(
			fmt.Sprintf(
				"Failed to de-serialize an instance of IMixedConcreteWithDescendantsChild " +
				"from %s: %s",
				pth, err.Error(),
			),
		)
	}
	var ok bool
	result, ok = instance.(aastypes.IMixedConcreteWithDescendantsChild)
	if !ok {
		panic(
			fmt.Sprintf(
				"Expected to find an instance of IMixedConcreteWithDescendantsChild at %s, " +
				"but got an instance of %T: %v",
				pth, instance, instance,
			),
		)
	}
	return
}

// Load a minimal example of [aastypes.IMixedConcreteWithDescendantsChild] from
// the test data directory.
//
// If there is any error, panic.
func MustLoadMinimalMixedConcreteWithDescendantsChild(
) (result aastypes.IMixedConcreteWithDescendantsChild) {
	pth := path.Join(
		TestDataDir,
		"Json",
		"Expected",
		"MixedConcreteWithDescendantsChild",
		"minimal.json",
	)

	jsonable := MustReadJsonable(pth)

	instance, err := aasjsonization.MixedConcreteWithDescendantsChildFromJsonable(
		jsonable,
	)
	if err != nil {
		panic(
			fmt.Sprintf(
				"Failed to de-serialize an instance of IMixedConcreteWithDescendantsChild " +
				"from %s: %s",
				pth, err.Error(),
			),
		)
	}
	var ok bool
	result, ok = instance.(aastypes.IMixedConcreteWithDescendantsChild)
	if !ok {
		panic(
			fmt.Sprintf(
				"Expected to find an instance of IMixedConcreteWithDescendantsChild at %s, " +
				"but got an instance of %T: %v",
				pth, instance, instance,
			),
		)
	}
	return
}

// Load a maximal example of [aastypes.IMixedConcreteLeaf] from
// the test data directory.
//
// If there is any error, panic.
func MustLoadMaximalMixedConcreteLeaf(
) (result aastypes.IMixedConcreteLeaf) {
	pth := path.Join(
		TestDataDir,
		"Json",
		"Expected",
		"MixedConcreteLeaf",
		"maximal.json",
	)

	jsonable := MustReadJsonable(pth)

	instance, err := aasjsonization.MixedConcreteLeafFromJsonable(
		jsonable,
	)
	if err != nil {
		panic(
			fmt.Sprintf(
				"Failed to de-serialize an instance of IMixedConcreteLeaf " +
				"from %s: %s",
				pth, err.Error(),
			),
		)
	}
	var ok bool
	result, ok = instance.(aastypes.IMixedConcreteLeaf)
	if !ok {
		panic(
			fmt.Sprintf(
				"Expected to find an instance of IMixedConcreteLeaf at %s, " +
				"but got an instance of %T: %v",
				pth, instance, instance,
			),
		)
	}
	return
}

// Load a minimal example of [aastypes.IMixedConcreteLeaf] from
// the test data directory.
//
// If there is any error, panic.
func MustLoadMinimalMixedConcreteLeaf(
) (result aastypes.IMixedConcreteLeaf) {
	pth := path.Join(
		TestDataDir,
		"Json",
		"Expected",
		"MixedConcreteLeaf",
		"minimal.json",
	)

	jsonable := MustReadJsonable(pth)

	instance, err := aasjsonization.MixedConcreteLeafFromJsonable(
		jsonable,
	)
	if err != nil {
		panic(
			fmt.Sprintf(
				"Failed to de-serialize an instance of IMixedConcreteLeaf " +
				"from %s: %s",
				pth, err.Error(),
			),
		)
	}
	var ok bool
	result, ok = instance.(aastypes.IMixedConcreteLeaf)
	if !ok {
		panic(
			fmt.Sprintf(
				"Expected to find an instance of IMixedConcreteLeaf at %s, " +
				"but got an instance of %T: %v",
				pth, instance, instance,
			),
		)
	}
	return
}

// Load a maximal example of [aastypes.IModelTypedFirst] from
// the test data directory.
//
// If there is any error, panic.
func MustLoadMaximalModelTypedFirst(
) (result aastypes.IModelTypedFirst) {
	pth := path.Join(
		TestDataDir,
		"Json",
		"Expected",
		"ModelTypedFirst",
		"maximal.json",
	)

	jsonable := MustReadJsonable(pth)

	instance, err := aasjsonization.ModelTypedFirstFromJsonable(
		jsonable,
	)
	if err != nil {
		panic(
			fmt.Sprintf(
				"Failed to de-serialize an instance of IModelTypedFirst " +
				"from %s: %s",
				pth, err.Error(),
			),
		)
	}
	var ok bool
	result, ok = instance.(aastypes.IModelTypedFirst)
	if !ok {
		panic(
			fmt.Sprintf(
				"Expected to find an instance of IModelTypedFirst at %s, " +
				"but got an instance of %T: %v",
				pth, instance, instance,
			),
		)
	}
	return
}

// Load a minimal example of [aastypes.IModelTypedFirst] from
// the test data directory.
//
// If there is any error, panic.
func MustLoadMinimalModelTypedFirst(
) (result aastypes.IModelTypedFirst) {
	pth := path.Join(
		TestDataDir,
		"Json",
		"Expected",
		"ModelTypedFirst",
		"minimal.json",
	)

	jsonable := MustReadJsonable(pth)

	instance, err := aasjsonization.ModelTypedFirstFromJsonable(
		jsonable,
	)
	if err != nil {
		panic(
			fmt.Sprintf(
				"Failed to de-serialize an instance of IModelTypedFirst " +
				"from %s: %s",
				pth, err.Error(),
			),
		)
	}
	var ok bool
	result, ok = instance.(aastypes.IModelTypedFirst)
	if !ok {
		panic(
			fmt.Sprintf(
				"Expected to find an instance of IModelTypedFirst at %s, " +
				"but got an instance of %T: %v",
				pth, instance, instance,
			),
		)
	}
	return
}

// Load a maximal example of [aastypes.IModelTypedSecond] from
// the test data directory.
//
// If there is any error, panic.
func MustLoadMaximalModelTypedSecond(
) (result aastypes.IModelTypedSecond) {
	pth := path.Join(
		TestDataDir,
		"Json",
		"Expected",
		"ModelTypedSecond",
		"maximal.json",
	)

	jsonable := MustReadJsonable(pth)

	instance, err := aasjsonization.ModelTypedSecondFromJsonable(
		jsonable,
	)
	if err != nil {
		panic(
			fmt.Sprintf(
				"Failed to de-serialize an instance of IModelTypedSecond " +
				"from %s: %s",
				pth, err.Error(),
			),
		)
	}
	var ok bool
	result, ok = instance.(aastypes.IModelTypedSecond)
	if !ok {
		panic(
			fmt.Sprintf(
				"Expected to find an instance of IModelTypedSecond at %s, " +
				"but got an instance of %T: %v",
				pth, instance, instance,
			),
		)
	}
	return
}

// Load a minimal example of [aastypes.IModelTypedSecond] from
// the test data directory.
//
// If there is any error, panic.
func MustLoadMinimalModelTypedSecond(
) (result aastypes.IModelTypedSecond) {
	pth := path.Join(
		TestDataDir,
		"Json",
		"Expected",
		"ModelTypedSecond",
		"minimal.json",
	)

	jsonable := MustReadJsonable(pth)

	instance, err := aasjsonization.ModelTypedSecondFromJsonable(
		jsonable,
	)
	if err != nil {
		panic(
			fmt.Sprintf(
				"Failed to de-serialize an instance of IModelTypedSecond " +
				"from %s: %s",
				pth, err.Error(),
			),
		)
	}
	var ok bool
	result, ok = instance.(aastypes.IModelTypedSecond)
	if !ok {
		panic(
			fmt.Sprintf(
				"Expected to find an instance of IModelTypedSecond at %s, " +
				"but got an instance of %T: %v",
				pth, instance, instance,
			),
		)
	}
	return
}

// Load a maximal example of [aastypes.ISomething] from
// the test data directory.
//
// If there is any error, panic.
func MustLoadMaximalSomething(
) (result aastypes.ISomething) {
	pth := path.Join(
		TestDataDir,
		"Json",
		"Expected",
		"Something",
		"maximal.json",
	)

	jsonable := MustReadJsonable(pth)

	instance, err := aasjsonization.SomethingFromJsonable(
		jsonable,
	)
	if err != nil {
		panic(
			fmt.Sprintf(
				"Failed to de-serialize an instance of ISomething " +
				"from %s: %s",
				pth, err.Error(),
			),
		)
	}
	var ok bool
	result, ok = instance.(aastypes.ISomething)
	if !ok {
		panic(
			fmt.Sprintf(
				"Expected to find an instance of ISomething at %s, " +
				"but got an instance of %T: %v",
				pth, instance, instance,
			),
		)
	}
	return
}

// Load a minimal example of [aastypes.ISomething] from
// the test data directory.
//
// If there is any error, panic.
func MustLoadMinimalSomething(
) (result aastypes.ISomething) {
	pth := path.Join(
		TestDataDir,
		"Json",
		"Expected",
		"Something",
		"minimal.json",
	)

	jsonable := MustReadJsonable(pth)

	instance, err := aasjsonization.SomethingFromJsonable(
		jsonable,
	)
	if err != nil {
		panic(
			fmt.Sprintf(
				"Failed to de-serialize an instance of ISomething " +
				"from %s: %s",
				pth, err.Error(),
			),
		)
	}
	var ok bool
	result, ok = instance.(aastypes.ISomething)
	if !ok {
		panic(
			fmt.Sprintf(
				"Expected to find an instance of ISomething at %s, " +
				"but got an instance of %T: %v",
				pth, instance, instance,
			),
		)
	}
	return
}

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.
