/*
 * This code has been automatically generated by aas-core-codegen.
 * Do NOT edit or append.
 */

package dummy.xmlization;

import javax.xml.stream.events.XMLEvent;
import javax.xml.stream.XMLEventReader;
import javax.xml.stream.XMLStreamConstants;
import javax.xml.stream.XMLStreamException;
import javax.xml.stream.XMLStreamWriter;
import java.util.ArrayList;
import java.util.Base64;
import java.util.function.BiFunction;
import java.util.function.Function;
import java.util.List;
import java.util.Optional;
import dummy.common.*;
import dummy.reporting.Reporting;
import dummy.stringification.Stringification;
import dummy.types.enums.*;
import dummy.types.impl.*;
import dummy.types.model.*;
import dummy.visitation.*;

/**
 * Provide de/serialization of meta-model classes to/from XML.
 */
public class Xmlization {
  /**
   * Represent a critical error during the deserialization.
   */
  @SuppressWarnings("serial")
  public static class DeserializeException extends RuntimeException {
    private final String path;
    private final String reason;

    public DeserializeException(String path, String reason) {
      super(reason + " at: " + ("".equals(path) ? "the beginning" : path));
      this.path = path;
      this.reason = reason;
    }

    public Optional<String> getPath() {
      return Optional.ofNullable(path);
    }

    public Optional<String> getReason() {
      return Optional.ofNullable(reason);
    }
  }

  /**
   * Represent a critical error during the serialization.
   */
  @SuppressWarnings("serial")
  public static class SerializeException extends RuntimeException {
    private final String path;
    private final String reason;

    public SerializeException(String path, String reason) {
      super(reason + " at: " + ("".equals(path) ? "the beginning" : path));
      this.path = path;
      this.reason = reason;
    }

    public Optional<String> getPath() {
      return Optional.ofNullable(path);
    }

    public Optional<String> getReason() {
      return Optional.ofNullable(reason);
    }
  }

  /**
   * The XML namespace of the meta-model
   */
  public static final String AAS_NAME_SPACE =
    "https://dummy.com";

  /**
   * Implement the deserialization of meta-model classes from XML.
   *
   * <p>The implementation propagates an {@link Reporting.Error} instead of
   * relying on exceptions. Under the assumption that incorrect data is much less
   * frequent than correct data, this makes the deserialization more
   * efficient.
   *
   * <p>However, we do not want to force the client to deal with
   * the {@link Reporting.Error} class as this is not intuitive.
   * Therefore we distinguish the implementation, realized in
   * {@link _DeserializeImplementation}, and the facade given in
   * {@link Deserialize} class.
   */
  private static class _DeserializeImplementation
  {
    private static XMLEvent currentEvent(XMLEventReader reader) {
      try {
        return reader.peek();
      } catch (XMLStreamException xmlStreamException) {
        throw new Xmlization.DeserializeException("",
          "Failed in method peek because of: " +
          xmlStreamException.getMessage());
      }
    }

    private static String getEventTypeAsString(XMLEvent event) {
      switch (event.getEventType()) {
        case XMLStreamConstants.START_ELEMENT:
          return "Start-Element";
        case XMLStreamConstants.END_ELEMENT:
          return "End-Element";
        case XMLStreamConstants.PROCESSING_INSTRUCTION:
          return "Processing-Instruction";
        case XMLStreamConstants.CHARACTERS:
          return "Characters";
        case XMLStreamConstants.COMMENT:
          return "Comment";
        case XMLStreamConstants.SPACE:
          return "Space";
        case XMLStreamConstants.START_DOCUMENT:
          return "Start-Document";
        case XMLStreamConstants.END_DOCUMENT:
          return "End-Document";
        case XMLStreamConstants.ENTITY_REFERENCE:
          return "Entity-Reference";
        case XMLStreamConstants.ATTRIBUTE:
          return "Attribute";
        case XMLStreamConstants.NOTATION_DECLARATION:
          return "Notation-Declaration";
        default:
          return "Unknown-Type";
      }
    }

    private static boolean isEmptyElement(XMLEventReader reader) {
      // Skip the element node and go to the content
      try {
        reader.nextEvent();
      } catch (XMLStreamException xmlStreamException) {
        throw new Xmlization.DeserializeException("",
          "Failed in method isEmptyElement because of: " +
          xmlStreamException.getMessage());
      }
      return currentEvent(reader).isEndElement();
    }

    private static Reporting.Result<XMLEvent> verifyClosingTagForClass(
      String className,
      XMLEventReader reader,
      Reporting.Result<String> tryElementName) {
      final XMLEvent currentEvent = currentEvent(reader);
      if (currentEvent.isEndDocument()) {
        final Reporting.Error error = new Reporting.Error(
            "Expected an XML end element to conclude a property of class " + className
                + " with the element name " + tryElementName.getResult() + ", "
                + "but got the end-of-file.");
        return Reporting.Result.failure(error);
      }

      if (!currentEvent.isEndElement()) {
        final Reporting.Error error = new Reporting.Error(
            "Expected an XML end element to conclude a property of class " + className
                + " with the element name " + tryElementName.getResult() + ", "
                + "but got the node of type " + getEventTypeAsString(currentEvent)
                + " with the value " + currentEvent);
        return Reporting.Result.failure(error);
      }
      final Reporting.Result<String> tryEndElementName = tryElementName(reader);
      if (tryEndElementName.isError()) {
        return tryEndElementName.castTo(XMLEvent.class);
      }
      if (!tryElementName.getResult().equals(tryEndElementName.getResult())) {
        final Reporting.Error error = new Reporting.Error(
            "Expected an XML end element to conclude a property of class " + className
                + " with the element name " + tryElementName.getResult() + ", "
                + "but got the end element with the name " + tryEndElementName.getResult());
        return Reporting.Result.failure(error);
      }
      try {
        return Reporting.Result.success(reader.nextEvent());
      } catch (XMLStreamException xmlStreamException) {
        throw new Xmlization.DeserializeException("",
          "Failed in method verifyClosingTagForClass because of: " +
          xmlStreamException.getMessage());
      }
    }

    /**
     * Deserialize an instance of {@code T} from an XML element.
     *
     * <p>{@code parseAsSequence} is given the element's local name and whether
     * the element is self-closing, and is expected to consume the properties of
     * the instance, but not the element's closing tag.
     */
    private static <T> Reporting.Result<? extends T> parseInstanceFromElement(
      XMLEventReader reader,
      Class<T> type,
      BiFunction<String, Boolean, Reporting.Result<? extends T>> parseAsSequence) {
      skipWhitespaceAndComments(reader);

      final XMLEvent currentEvent = currentEvent(reader);
      if (currentEvent.getEventType() == XMLStreamConstants.END_DOCUMENT) {
        return Reporting.Result.failure(new Reporting.Error(
          "Expected an XML element representing an instance of " + type.getSimpleName() + ", " +
            "but reached the end-of-file"));
      }

      if (currentEvent.getEventType() != XMLStreamConstants.START_ELEMENT) {
        return Reporting.Result.failure(new Reporting.Error(
          "Expected an XML element representing an instance of " + type.getSimpleName() + ", " +
            "but got a node of type " + getEventTypeAsString(currentEvent) +
            " with value " + currentEvent));
      }

      final Reporting.Result<String> tryElementName = tryElementName(reader);
      if (tryElementName.isError()) {
        return Reporting.Result.failure(tryElementName.getError());
      }

      final String elementName = tryElementName.getResult();
      final boolean isEmptyElement = isEmptyElement(reader);

      final Reporting.Result<? extends T> result = parseAsSequence.apply(elementName, isEmptyElement);
      if (result.isError()) {
        return result;
      }

      final Reporting.Result<XMLEvent> checkEndElement = verifyClosingTagForClass(
        type.getSimpleName(),
        reader,
        tryElementName);
      if (checkEndElement.isError()) {
        return Reporting.Result.failure(checkEndElement.getError());
      }

      return result;
    }

    private static void skipWhitespaceAndComments(XMLEventReader reader) {
      while (whiteSpaceOrComment(reader)) {
        reader.next();
      }
    }

    private static boolean whiteSpaceOrComment(XMLEventReader reader) {
      final XMLEvent currentEvent = currentEvent(reader);
      final boolean isComment = (currentEvent != null &&
        currentEvent.getEventType() == XMLStreamConstants.COMMENT);
      final boolean isWhiteSpace = (currentEvent != null &&
        currentEvent.getEventType() == XMLStreamConstants.CHARACTERS &&
        currentEvent.asCharacters().isWhiteSpace());
      return isComment || isWhiteSpace;
    }

    private static void skipStartDocument(XMLEventReader reader){
      if (currentEvent(reader).isStartDocument()){
        reader.next();
      }
    }

    private static boolean invalidNameSpace(XMLEvent event) {
      if (event.isStartElement()) {
        return !AAS_NAME_SPACE.equals(event.asStartElement().getName().getNamespaceURI());
      } else {
        return !AAS_NAME_SPACE.equals(event.asEndElement().getName().getNamespaceURI());
      }
    }

    /**
     * Check the namespace and extract the element's name.
     */
    private static Reporting.Result<String> tryElementName(XMLEventReader reader) {
      final XMLEvent currentEvent = currentEvent(reader);
      final boolean precondition = currentEvent.isStartElement() || currentEvent.isEndElement();
      if (!precondition) {
        throw new IllegalStateException("Expected to be at a start or an end element "
            + "but got: " + getEventTypeAsString(currentEvent));
      }

      if (invalidNameSpace(currentEvent)) {
        String namespace = currentEvent.isStartElement()
            ? currentEvent.asStartElement().getName().getNamespaceURI()
            : currentEvent.asEndElement().getName().getNamespaceURI();
        final Reporting.Error error = new Reporting.Error(
            "Expected an element within a namespace " +
            AAS_NAME_SPACE + ", " + "but got: " + namespace);
        return Reporting.Result.failure(error);
      }
      return Reporting.Result.success(currentEvent.isStartElement()
          ? currentEvent.asStartElement().getName().getLocalPart()
          : currentEvent.asEndElement().getName().getLocalPart());
    }

    private static String readContentAsString(XMLEventReader reader) throws XMLStreamException {
      final StringBuilder content = new StringBuilder();

      while (reader.peek().isCharacters() || reader.peek().getEventType() == XMLStreamConstants.COMMENT) {
        if (reader.peek().isCharacters()) {
          content.append(reader.peek().asCharacters().getData());
        }
        reader.nextEvent();
      }

      return content.toString();
    }

    private static Boolean readContentAsBool(XMLEventReader reader) throws XMLStreamException {
      final StringBuilder content = new StringBuilder();

      while (reader.peek().isCharacters() || reader.peek().getEventType() == XMLStreamConstants.COMMENT) {
        if (reader.peek().isCharacters()) {
          content.append(reader.peek().asCharacters().getData());
        }
        reader.nextEvent();
      }
      if(!("true".equals(content.toString()) || "false".equals(content.toString()))){
        throw new IllegalStateException("Content cannot be converted to the type Boolean.");
      }
      return Boolean.valueOf(content.toString());
    }

    private static Long readContentAsLong(XMLEventReader reader) throws XMLStreamException {
      final StringBuilder content = new StringBuilder();

      while (reader.peek().isCharacters() || reader.peek().getEventType() == XMLStreamConstants.COMMENT) {
        if (reader.peek().isCharacters()) {
          content.append(reader.peek().asCharacters().getData());
        }
        reader.nextEvent();
      }

      return Long.valueOf(content.toString());
    }

    private static Double readContentAsDouble(XMLEventReader reader) throws XMLStreamException {
      final StringBuilder content = new StringBuilder();

      while (reader.peek().isCharacters() || reader.peek().getEventType() == XMLStreamConstants.COMMENT) {
        if (reader.peek().isCharacters()) {
          content.append(reader.peek().asCharacters().getData());
        }
        reader.nextEvent();
      }

      return Double.valueOf(content.toString());
    }

    /**
     * Read the whole content of an element into memory.
     */
    private static byte[] readContentAsBase64(
      XMLEventReader reader) throws XMLStreamException {
      final StringBuilder content = new StringBuilder();
      while (reader.peek().isCharacters() || reader.peek().getEventType() == XMLStreamConstants.COMMENT) {
        if (reader.peek().isCharacters()) {
          content.append(reader.peek().asCharacters().getData());
        }
        reader.nextEvent();
      }

      String encodedData = content.toString();
      final byte[] decodedData;
      Base64.Decoder decoder = Base64.getDecoder();

      try {
        decodedData = decoder.decode(encodedData);
      } catch (IllegalArgumentException exception) {
        throw new XMLStreamException(
          "Failed to read base64 encoded data: " +
          exception.getMessage());
      }

      return decodedData;
    }

    /**
     * Consume a starting element of the {@code expectedName} from the reader
     * and return whether it was a self-closing (empty) element.
     */
    private static Reporting.Result<Boolean> tryNamedStartElement(
      XMLEventReader reader, String expectedName) {
      if (currentEvent(reader).isEndDocument()) {
        final Reporting.Error error = new Reporting.Error(
          "Expected a <" + expectedName + "> element, but got an end-of-file.");
        return Reporting.Result.failure(error);
      }

      if (!currentEvent(reader).isStartElement()) {
        final Reporting.Error error = new Reporting.Error(
          "Expected a <" + expectedName + "> start element, but got the node "
            + "of type " + getEventTypeAsString(currentEvent(reader)));
        return Reporting.Result.failure(error);
      }

      final Reporting.Result<String> tryElementName = tryElementName(reader);
      if (tryElementName.isError()) {
        return tryElementName.castTo(Boolean.class);
      }

      if (!expectedName.equals(tryElementName.getResult())) {
        final Reporting.Error error = new Reporting.Error(
          "Expected a <" + expectedName + "> element, but got an element "
            + tryElementName.getResult());
        return Reporting.Result.failure(error);
      }

      final boolean isEmpty = isEmptyElement(reader);
      return Reporting.Result.success(isEmpty);
    }

    /**
     * Consume a closing element of the {@code expectedName} from the reader.
     */
    private static Reporting.Result<XMLEvent> tryNamedEndElement(
      XMLEventReader reader, String expectedName) {
      skipWhitespaceAndComments(reader);

      if (currentEvent(reader).isEndDocument()) {
        final Reporting.Error error = new Reporting.Error(
          "Expected a closing element for " + expectedName + ", "
            + "but got an end-of-file.");
        return Reporting.Result.failure(error);
      }

      if (!currentEvent(reader).isEndElement()) {
        final Reporting.Error error = new Reporting.Error(
          "Expected a closing element for " + expectedName + ", "
            + "but got the node of type " + getEventTypeAsString(currentEvent(reader)));
        return Reporting.Result.failure(error);
      }

      final Reporting.Result<String> tryElementName = tryElementName(reader);
      if (tryElementName.isError()) {
        return tryElementName.castTo(XMLEvent.class);
      }

      if (!expectedName.equals(tryElementName.getResult())) {
        final Reporting.Error error = new Reporting.Error(
          "Expected a closing element for " + expectedName + ", "
            + "but got an end element " + tryElementName.getResult());
        return Reporting.Result.failure(error);
      }

      try {
        return Reporting.Result.success(reader.nextEvent());
      } catch (XMLStreamException xmlStreamException) {
        throw new Xmlization.DeserializeException("",
          "Failed in method tryNamedEndElement because of: " +
            xmlStreamException.getMessage());
      }
    }

    /**
     * Read the content of a named element and parse it as Boolean.
     */
    private static Reporting.Result<Boolean> tryNamedElementAsBoolean(
      XMLEventReader reader, String expectedName) {
      final Reporting.Result<Boolean> tryStart = tryNamedStartElement(reader, expectedName);
      if (tryStart.isError()) {
        return tryStart.castTo(Boolean.class);
      }

      if (tryStart.getResult()) {
        final Reporting.Error error = new Reporting.Error(
          "Expected an XML content representing Boolean, " +
          "but got a self-closing <" + expectedName + " /> element");
        return Reporting.Result.failure(error);
      }

      final Boolean result;
      try {
        result = readContentAsBool(reader);
      } catch (Exception exception) {
        final Reporting.Error error = new Reporting.Error(
          "The content of a <" + expectedName + "> element could not be "
            + "de-serialized as Boolean: " + exception.getMessage());
        return Reporting.Result.failure(error);
      }

      final Reporting.Result<XMLEvent> tryEnd = tryNamedEndElement(reader, expectedName);
      if (tryEnd.isError()) {
        return tryEnd.castTo(Boolean.class);
      }

      return Reporting.Result.success(result);
    }

    /**
     * Read the content of a named element and parse it as Long.
     */
    private static Reporting.Result<Long> tryNamedElementAsLong(
      XMLEventReader reader, String expectedName) {
      final Reporting.Result<Boolean> tryStart = tryNamedStartElement(reader, expectedName);
      if (tryStart.isError()) {
        return tryStart.castTo(Long.class);
      }

      if (tryStart.getResult()) {
        final Reporting.Error error = new Reporting.Error(
          "Expected an XML content representing Long, " +
          "but got a self-closing <" + expectedName + " /> element");
        return Reporting.Result.failure(error);
      }

      final Long result;
      try {
        result = readContentAsLong(reader);
      } catch (Exception exception) {
        final Reporting.Error error = new Reporting.Error(
          "The content of a <" + expectedName + "> element could not be "
            + "de-serialized as Long: " + exception.getMessage());
        return Reporting.Result.failure(error);
      }

      final Reporting.Result<XMLEvent> tryEnd = tryNamedEndElement(reader, expectedName);
      if (tryEnd.isError()) {
        return tryEnd.castTo(Long.class);
      }

      return Reporting.Result.success(result);
    }

    /**
     * Read the content of a named element and parse it as Double.
     */
    private static Reporting.Result<Double> tryNamedElementAsDouble(
      XMLEventReader reader, String expectedName) {
      final Reporting.Result<Boolean> tryStart = tryNamedStartElement(reader, expectedName);
      if (tryStart.isError()) {
        return tryStart.castTo(Double.class);
      }

      if (tryStart.getResult()) {
        final Reporting.Error error = new Reporting.Error(
          "Expected an XML content representing Double, " +
          "but got a self-closing <" + expectedName + " /> element");
        return Reporting.Result.failure(error);
      }

      final Double result;
      try {
        result = readContentAsDouble(reader);
      } catch (Exception exception) {
        final Reporting.Error error = new Reporting.Error(
          "The content of a <" + expectedName + "> element could not be "
            + "de-serialized as Double: " + exception.getMessage());
        return Reporting.Result.failure(error);
      }

      final Reporting.Result<XMLEvent> tryEnd = tryNamedEndElement(reader, expectedName);
      if (tryEnd.isError()) {
        return tryEnd.castTo(Double.class);
      }

      return Reporting.Result.success(result);
    }

    /**
     * Read the content of a named element and parse it as a string.
     */
    private static Reporting.Result<String> tryNamedElementAsString(
      XMLEventReader reader, String expectedName) {
      final Reporting.Result<Boolean> tryStart = tryNamedStartElement(reader, expectedName);
      if (tryStart.isError()) {
        return tryStart.castTo(String.class);
      }

      final String result;
      if (tryStart.getResult()) {
        result = "";
      } else {
        try {
          result = readContentAsString(reader);
        } catch (Exception exception) {
          final Reporting.Error error = new Reporting.Error(
            "The content of a <" + expectedName + "> element could not be "
              + "de-serialized as String: " + exception.getMessage());
          return Reporting.Result.failure(error);
        }
      }

      // NOTE (mristin):
      // A self-closing named element is represented as a pair of start and end
      // events in StAX, so we need to consume the end element even if the
      // element was empty.
      final Reporting.Result<XMLEvent> tryEnd = tryNamedEndElement(reader, expectedName);
      if (tryEnd.isError()) {
        return tryEnd.castTo(String.class);
      }

      return Reporting.Result.success(result);
    }

    /**
     * Read a named element as base64-encoded bytes.
     */
    private static Reporting.Result<byte[]> tryNamedElementAsBytes(
      XMLEventReader reader, String expectedName) {
      final Reporting.Result<Boolean> tryStart = tryNamedStartElement(reader, expectedName);
      if (tryStart.isError()) {
        return tryStart.castTo(byte[].class);
      }

      final byte[] result;
      if (tryStart.getResult()) {
        result = new byte[0];
      } else {
        try {
          result = readContentAsBase64(reader);
        } catch (Exception exception) {
          final Reporting.Error error = new Reporting.Error(
            "The content of a <" + expectedName + "> element could not be "
              + "de-serialized as base64-encoded bytes: " + exception.getMessage());
          return Reporting.Result.failure(error);
        }
      }

      // NOTE (mristin):
      // A self-closing named element is represented as a pair of start and end
      // events in StAX, so we need to consume the end element even if the
      // element was empty.
      final Reporting.Result<XMLEvent> tryEnd = tryNamedEndElement(reader, expectedName);
      if (tryEnd.isError()) {
        return tryEnd.castTo(byte[].class);
      }

      return Reporting.Result.success(result);
    }

    /**
     * Parse a list of items, each de-serialized by {@code parseItem}.
     *
     * <p>Every start element is considered to mark the start of an item. Parsing
     * stops as soon as a non-start element is encountered.
     */
    private static <T> Reporting.Result<List<T>> parseList(
      XMLEventReader reader,
      boolean isEmptyProperty,
      Class<T> itemType,
      Function<XMLEventReader, Reporting.Result<? extends T>> parseItem) {
      final List<T> result = new ArrayList<>();
      if (isEmptyProperty) {
        return Reporting.Result.success(result);
      }

      skipWhitespaceAndComments(reader);
      int index = 0;
      if (!currentEvent(reader).isStartElement()) {
        final Reporting.Error error = new Reporting.Error(
          "Expected a start element opening an instance of " + itemType.getSimpleName() +
            ", but got an XML " + getEventTypeAsString(currentEvent(reader)));
        error.prependSegment(new Reporting.IndexSegment(index));
        return Reporting.Result.failure(error);
      }

      while (currentEvent(reader).isStartElement()) {
        final Reporting.Result<? extends T> itemResult = parseItem.apply(reader);
        if (itemResult.isError()) {
          itemResult.getError()
            .prependSegment(
              new Reporting.IndexSegment(index));
          return Reporting.Result.failure(itemResult.getError());
        }

        result.add(itemResult.getResult());
        index++;
        skipWhitespaceAndComments(reader);
      }

      return Reporting.Result.success(result);
    }

    /**
     * Read a named element and parse its content as a literal
     * of {@link Result}.
     */
    private static Reporting.Result<Result> tryNamedElementAsResult(
      XMLEventReader reader, String expectedName) {
      final Reporting.Result<String> tryText = tryNamedElementAsString(reader, expectedName);
      if (tryText.isError()) {
        return tryText.castTo(Result.class);
      }

      final Optional<Result> result = Stringification.resultFromString(
        tryText.getResult());

      if (!result.isPresent()) {
        final Reporting.Error error = new Reporting.Error(
          "The text could not be parsed as a literal of Result: " +
          tryText.getResult());
        return Reporting.Result.failure(error);
      }

      return Reporting.Result.success(result.get());
    }

    /**
     * Adapt {@code readNamed} together with {@code name} into a tuple item
     * reader.
     *
     * <p>{@code name} ({@code "v1"}, {@code "v2"}, ...) is a plain runtime
     * string, not a type, so it can not be pinned via a generic type parameter --
     * binding it requires an actual closure, built once here.
     */
    private static <T> Function<XMLEventReader, Reporting.Result<? extends T>> asScalarTupleItemReader(
      String name,
      BiFunction<XMLEventReader, String, Reporting.Result<? extends T>> readNamed) {
      return reader -> readNamed.apply(reader, name);
    }

    /**
     * Adapt {@code readInstance} into a tuple item reader, checking first
     * that {@code reader} is positioned at a start element, and naming the
     * expected class as {@code itemTypeName} if it is not.
     *
     * <p>Unlike a list, whose items all share a single class, each tuple item
     * can have a different class, dispatched through its own natural element
     * tag rather than a positional {@code v1}/{@code v2} wrapper -- so the
     * "expected a start element" message has to name the expected class itself,
     * and {@code readInstance} is a different function value at every call
     * site. Both are runtime values, not types, so binding them requires an
     * actual closure, built once here.
     */
    private static <T> Function<XMLEventReader, Reporting.Result<? extends T>> asInstanceTupleItemReader(
      String itemTypeName,
      Function<XMLEventReader, Reporting.Result<? extends T>> readInstance) {
      return reader -> {
        skipWhitespaceAndComments(reader);
        if (!currentEvent(reader).isStartElement()) {
          final Reporting.Error error = new Reporting.Error(
            "Expected a start element opening an instance of " + itemTypeName +
              ", but got an XML " + getEventTypeAsString(currentEvent(reader)));
          return Reporting.Result.failure(error);
        }
        return readInstance.apply(reader);
      };
    }

    /**
     * Parse a tuple of 2 item(s) from {@code reader}, each de-serialized
     * with the corresponding {@code parseItemI}.
     */
    private static <T1, T2> Reporting.Result<Tuple2<T1, T2>> parseTuple2(
      XMLEventReader reader,
      boolean isEmptyProperty,
      Function<XMLEventReader, Reporting.Result<? extends T1>> parseItem1,
      Function<XMLEventReader, Reporting.Result<? extends T2>> parseItem2) {
      if (isEmptyProperty) {
        final Reporting.Error error = new Reporting.Error(
          "Expected exactly 2 item(s), but got a self-closing element");
        return Reporting.Result.failure(error);
      }

      final Reporting.Result<? extends T1> item1Result =
        parseItem1.apply(reader);
      if (item1Result.isError()) {
        item1Result.getError()
          .prependSegment(new Reporting.IndexSegment(0));
        return Reporting.Result.failure(item1Result.getError());
      }

      final Reporting.Result<? extends T2> item2Result =
        parseItem2.apply(reader);
      if (item2Result.isError()) {
        item2Result.getError()
          .prependSegment(new Reporting.IndexSegment(1));
        return Reporting.Result.failure(item2Result.getError());
      }

      return Reporting.Result.success(
        new Tuple2<>(
          item1Result.getResult(),
          item2Result.getResult()));
    }

    /**
     * Parse a tuple of 6 item(s) from {@code reader}, each de-serialized
     * with the corresponding {@code parseItemI}.
     */
    private static <T1, T2, T3, T4, T5, T6> Reporting.Result<Tuple6<T1, T2, T3, T4, T5, T6>> parseTuple6(
      XMLEventReader reader,
      boolean isEmptyProperty,
      Function<XMLEventReader, Reporting.Result<? extends T1>> parseItem1,
      Function<XMLEventReader, Reporting.Result<? extends T2>> parseItem2,
      Function<XMLEventReader, Reporting.Result<? extends T3>> parseItem3,
      Function<XMLEventReader, Reporting.Result<? extends T4>> parseItem4,
      Function<XMLEventReader, Reporting.Result<? extends T5>> parseItem5,
      Function<XMLEventReader, Reporting.Result<? extends T6>> parseItem6) {
      if (isEmptyProperty) {
        final Reporting.Error error = new Reporting.Error(
          "Expected exactly 6 item(s), but got a self-closing element");
        return Reporting.Result.failure(error);
      }

      final Reporting.Result<? extends T1> item1Result =
        parseItem1.apply(reader);
      if (item1Result.isError()) {
        item1Result.getError()
          .prependSegment(new Reporting.IndexSegment(0));
        return Reporting.Result.failure(item1Result.getError());
      }

      final Reporting.Result<? extends T2> item2Result =
        parseItem2.apply(reader);
      if (item2Result.isError()) {
        item2Result.getError()
          .prependSegment(new Reporting.IndexSegment(1));
        return Reporting.Result.failure(item2Result.getError());
      }

      final Reporting.Result<? extends T3> item3Result =
        parseItem3.apply(reader);
      if (item3Result.isError()) {
        item3Result.getError()
          .prependSegment(new Reporting.IndexSegment(2));
        return Reporting.Result.failure(item3Result.getError());
      }

      final Reporting.Result<? extends T4> item4Result =
        parseItem4.apply(reader);
      if (item4Result.isError()) {
        item4Result.getError()
          .prependSegment(new Reporting.IndexSegment(3));
        return Reporting.Result.failure(item4Result.getError());
      }

      final Reporting.Result<? extends T5> item5Result =
        parseItem5.apply(reader);
      if (item5Result.isError()) {
        item5Result.getError()
          .prependSegment(new Reporting.IndexSegment(4));
        return Reporting.Result.failure(item5Result.getError());
      }

      final Reporting.Result<? extends T6> item6Result =
        parseItem6.apply(reader);
      if (item6Result.isError()) {
        item6Result.getError()
          .prependSegment(new Reporting.IndexSegment(5));
        return Reporting.Result.failure(item6Result.getError());
      }

      return Reporting.Result.success(
        new Tuple6<>(
          item1Result.getResult(),
          item2Result.getResult(),
          item3Result.getResult(),
          item4Result.getResult(),
          item5Result.getResult(),
          item6Result.getResult()));
    }

    /**
     * Deserialize an instance of IAbstractItem from an XML element.
     */
    private static Reporting.Result<? extends IAbstractItem> tryIAbstractItemFromElement(
      XMLEventReader reader) {
      return parseInstanceFromElement(
        reader,
        IAbstractItem.class,
        (elementName, isEmptyElement) -> {
          switch (elementName) {
            case "anotherItem":
              return tryAnotherItemFromSequence(reader, isEmptyElement);
            case "someItem":
              return trySomeItemFromSequence(reader, isEmptyElement);
            default:
              final Reporting.Error error = new Reporting.Error(
                "Unexpected element with the name " + elementName);
              return Reporting.Result.failure(error);
          }
        });
    }

    /**
     * Deserialize an instance of class SomeItem from a sequence of XML elements.
     *
     * <p>If {@code isEmptySequence} is set, we should try to deserialize
     * the instance from an empty sequence. That is, the parent element
     * was a self-closing element.
     */
    private static Reporting.Result<SomeItem> trySomeItemFromSequence(
      XMLEventReader reader,
      boolean isEmptySequence) {
      String theName = null;

      if (!isEmptySequence) {
        skipWhitespaceAndComments(reader);
        if (currentEvent(reader).isEndDocument()) {
          final Reporting.Error error = new Reporting.Error(
            "Expected an XML element representing " +
            "a property of an instance of class SomeItem, " +
            "but reached the end-of-file");
          return Reporting.Result.failure(error);
        }
        while (true) {
          skipWhitespaceAndComments(reader);

          if (currentEvent(reader).isEndElement() || currentEvent(reader).isEndDocument()) {
            break;
          }

          if (!currentEvent(reader).isStartElement()) {
            final Reporting.Error error = new Reporting.Error(
              "Expected an XML start element representing " +
              "a property of an instance of class SomeItem, " +
              "but got the node of type " + getEventTypeAsString(currentEvent(reader)) +
              " with the value " + currentEvent(reader));
            return Reporting.Result.failure(error);
          }

          final Reporting.Result<String> tryElementName = tryElementName(reader);
          if (tryElementName.isError()) {
            return tryElementName.castTo(SomeItem.class);
          }

          final boolean isEmptyProperty = isEmptyElement(reader);
          final String elementName = tryElementName.getResult();

          switch (tryElementName.getResult()) {
            case "name":
            {
              if (isEmptyProperty) {
                theName = "";
              }
              else {
                if (currentEvent(reader).isEndDocument()) {
                  final Reporting.Error error = new Reporting.Error(
                    "Expected an XML content representing " +
                    "the property name of an instance of class SomeItem, " +
                    "but reached the end-of-file");
                  return Reporting.Result.failure(error);
                }

                try {
                  theName = readContentAsString(reader);
                } catch (Exception e) {
                  final Reporting.Error error = new Reporting.Error(
                    "The property name of an instance of class SomeItem "
                      + " could not be de-serialized: " + e.getMessage());
                  error.prependSegment(
                    new Reporting.NameSegment(
                      "name"));
                  return Reporting.Result.failure(error);
                }
              }
              break;
            }
            default:
              final Reporting.Error error = new Reporting.Error(
                "We expected properties of the class SomeItem, " +
                "but got an unexpected element " +
                "with the name " + elementName);
              return Reporting.Result.failure(error);
          }

          skipWhitespaceAndComments(reader);


          final Reporting.Result<XMLEvent> checkEndElement = verifyClosingTagForClass(
            "SomeItem",
            reader,
            tryElementName);
          if (checkEndElement.isError()) return checkEndElement.castTo(SomeItem.class);

        }
      }

      if (theName == null) {
        final Reporting.Error error = new Reporting.Error(
          "The required property name has not been given " +
          "in the XML representation of an instance of class SomeItem");
        return Reporting.Result.failure(error);
      }

      return Reporting.Result.success(new SomeItem(
        theName));
    }

    /**
     * Deserialize an instance of class SomeItem from an XML element.
     */
    private static Reporting.Result<? extends SomeItem> trySomeItemFromElement(
      XMLEventReader reader) {
      return parseInstanceFromElement(
        reader,
        SomeItem.class,
        (elementName, isEmptyElement) -> {
          if (!"someItem".equals(elementName)) {
            final Reporting.Error error = new Reporting.Error(
              "Expected an element representing an instance of class SomeItem " +
              "with element name someItem, but got: " + elementName);
            return Reporting.Result.failure(error);
          }

          return trySomeItemFromSequence(reader, isEmptyElement);
        });
    }

    /**
     * Deserialize an instance of class AnotherItem from a sequence of XML elements.
     *
     * <p>If {@code isEmptySequence} is set, we should try to deserialize
     * the instance from an empty sequence. That is, the parent element
     * was a self-closing element.
     */
    private static Reporting.Result<AnotherItem> tryAnotherItemFromSequence(
      XMLEventReader reader,
      boolean isEmptySequence) {
      Long theSerialNumber = null;

      if (!isEmptySequence) {
        skipWhitespaceAndComments(reader);
        if (currentEvent(reader).isEndDocument()) {
          final Reporting.Error error = new Reporting.Error(
            "Expected an XML element representing " +
            "a property of an instance of class AnotherItem, " +
            "but reached the end-of-file");
          return Reporting.Result.failure(error);
        }
        while (true) {
          skipWhitespaceAndComments(reader);

          if (currentEvent(reader).isEndElement() || currentEvent(reader).isEndDocument()) {
            break;
          }

          if (!currentEvent(reader).isStartElement()) {
            final Reporting.Error error = new Reporting.Error(
              "Expected an XML start element representing " +
              "a property of an instance of class AnotherItem, " +
              "but got the node of type " + getEventTypeAsString(currentEvent(reader)) +
              " with the value " + currentEvent(reader));
            return Reporting.Result.failure(error);
          }

          final Reporting.Result<String> tryElementName = tryElementName(reader);
          if (tryElementName.isError()) {
            return tryElementName.castTo(AnotherItem.class);
          }

          final boolean isEmptyProperty = isEmptyElement(reader);
          final String elementName = tryElementName.getResult();

          switch (tryElementName.getResult()) {
            case "serialNumber":
            {
              if (isEmptyProperty) {
                final Reporting.Error error = new Reporting.Error(
                  "The property serialNumber of an instance of class AnotherItem " +
                  "can not be de-serialized from a self-closing element " +
                  "since it needs content");
                error.prependSegment(
                  new Reporting.NameSegment(
                    "serialNumber"));
                return Reporting.Result.failure(error);
              }
              else {
                if (currentEvent(reader).isEndDocument()) {
                  final Reporting.Error error = new Reporting.Error(
                    "Expected an XML content representing " +
                    "the property serialNumber of an instance of class AnotherItem, " +
                    "but reached the end-of-file");
                  return Reporting.Result.failure(error);
                }

                try {
                  theSerialNumber = readContentAsLong(reader);
                } catch (Exception e) {
                  final Reporting.Error error = new Reporting.Error(
                    "The property serialNumber of an instance of class AnotherItem "
                      + " could not be de-serialized: " + e.getMessage());
                  error.prependSegment(
                    new Reporting.NameSegment(
                      "serialNumber"));
                  return Reporting.Result.failure(error);
                }
              }
              break;
            }
            default:
              final Reporting.Error error = new Reporting.Error(
                "We expected properties of the class AnotherItem, " +
                "but got an unexpected element " +
                "with the name " + elementName);
              return Reporting.Result.failure(error);
          }

          skipWhitespaceAndComments(reader);


          final Reporting.Result<XMLEvent> checkEndElement = verifyClosingTagForClass(
            "AnotherItem",
            reader,
            tryElementName);
          if (checkEndElement.isError()) return checkEndElement.castTo(AnotherItem.class);

        }
      }

      if (theSerialNumber == null) {
        final Reporting.Error error = new Reporting.Error(
          "The required property serialNumber has not been given " +
          "in the XML representation of an instance of class AnotherItem");
        return Reporting.Result.failure(error);
      }

      return Reporting.Result.success(new AnotherItem(
        theSerialNumber));
    }

    /**
     * Deserialize an instance of class AnotherItem from an XML element.
     */
    private static Reporting.Result<? extends AnotherItem> tryAnotherItemFromElement(
      XMLEventReader reader) {
      return parseInstanceFromElement(
        reader,
        AnotherItem.class,
        (elementName, isEmptyElement) -> {
          if (!"anotherItem".equals(elementName)) {
            final Reporting.Error error = new Reporting.Error(
              "Expected an element representing an instance of class AnotherItem " +
              "with element name anotherItem, but got: " + elementName);
            return Reporting.Result.failure(error);
          }

          return tryAnotherItemFromSequence(reader, isEmptyElement);
        });
    }

    /**
     * Deserialize an instance of class Something from a sequence of XML elements.
     *
     * <p>If {@code isEmptySequence} is set, we should try to deserialize
     * the instance from an empty sequence. That is, the parent element
     * was a self-closing element.
     */
    private static Reporting.Result<Something> trySomethingFromSequence(
      XMLEventReader reader,
      boolean isEmptySequence) {
      Tuple2<String, Long> thePair = null;
      Tuple2<IAbstractItem, IAbstractItem> theItems = null;
      Tuple6<
        Long,
        ISomeItem,
        IAbstractItem,
        ISomeItem,
        Long,
        Result> theTricky = null;

      if (!isEmptySequence) {
        skipWhitespaceAndComments(reader);
        if (currentEvent(reader).isEndDocument()) {
          final Reporting.Error error = new Reporting.Error(
            "Expected an XML element representing " +
            "a property of an instance of class Something, " +
            "but reached the end-of-file");
          return Reporting.Result.failure(error);
        }
        while (true) {
          skipWhitespaceAndComments(reader);

          if (currentEvent(reader).isEndElement() || currentEvent(reader).isEndDocument()) {
            break;
          }

          if (!currentEvent(reader).isStartElement()) {
            final Reporting.Error error = new Reporting.Error(
              "Expected an XML start element representing " +
              "a property of an instance of class Something, " +
              "but got the node of type " + getEventTypeAsString(currentEvent(reader)) +
              " with the value " + currentEvent(reader));
            return Reporting.Result.failure(error);
          }

          final Reporting.Result<String> tryElementName = tryElementName(reader);
          if (tryElementName.isError()) {
            return tryElementName.castTo(Something.class);
          }

          final boolean isEmptyProperty = isEmptyElement(reader);
          final String elementName = tryElementName.getResult();

          switch (tryElementName.getResult()) {
            case "pair":
            {
              final Reporting.Result<Tuple2<String, Long>> tryPair = parseTuple2(
                reader,
                isEmptyProperty,
                asScalarTupleItemReader(
                  "v1",
                  _DeserializeImplementation::tryNamedElementAsString),
                asScalarTupleItemReader(
                  "v2",
                  _DeserializeImplementation::tryNamedElementAsLong));

              if (tryPair.isError()) {
                tryPair.getError()
                  .prependSegment(
                    new Reporting.NameSegment(
                      "pair"));
                return tryPair.castTo(Something.class);
              }

              thePair = tryPair.getResult();
              break;
            }
            case "items":
            {
              final Reporting.Result<Tuple2<IAbstractItem, IAbstractItem>> tryItems = parseTuple2(
                reader,
                isEmptyProperty,
                asInstanceTupleItemReader(
                  "IAbstractItem",
                  _DeserializeImplementation::tryIAbstractItemFromElement),
                asInstanceTupleItemReader(
                  "IAbstractItem",
                  _DeserializeImplementation::tryIAbstractItemFromElement));

              if (tryItems.isError()) {
                tryItems.getError()
                  .prependSegment(
                    new Reporting.NameSegment(
                      "items"));
                return tryItems.castTo(Something.class);
              }

              theItems = tryItems.getResult();
              break;
            }
            case "tricky":
            {
              final Reporting.Result<Tuple6<
                Long,
                ISomeItem,
                IAbstractItem,
                ISomeItem,
                Long,
                Result>> tryTricky = parseTuple6(
                reader,
                isEmptyProperty,
                asScalarTupleItemReader(
                  "v1",
                  _DeserializeImplementation::tryNamedElementAsLong),
                asInstanceTupleItemReader(
                  "ISomeItem",
                  _DeserializeImplementation::trySomeItemFromElement),
                asInstanceTupleItemReader(
                  "IAbstractItem",
                  _DeserializeImplementation::tryIAbstractItemFromElement),
                asInstanceTupleItemReader(
                  "ISomeItem",
                  _DeserializeImplementation::trySomeItemFromElement),
                asScalarTupleItemReader(
                  "v5",
                  _DeserializeImplementation::tryNamedElementAsLong),
                asScalarTupleItemReader(
                  "v6",
                  _DeserializeImplementation::tryNamedElementAsResult));

              if (tryTricky.isError()) {
                tryTricky.getError()
                  .prependSegment(
                    new Reporting.NameSegment(
                      "tricky"));
                return tryTricky.castTo(Something.class);
              }

              theTricky = tryTricky.getResult();
              break;
            }
            default:
              final Reporting.Error error = new Reporting.Error(
                "We expected properties of the class Something, " +
                "but got an unexpected element " +
                "with the name " + elementName);
              return Reporting.Result.failure(error);
          }

          skipWhitespaceAndComments(reader);


          final Reporting.Result<XMLEvent> checkEndElement = verifyClosingTagForClass(
            "Something",
            reader,
            tryElementName);
          if (checkEndElement.isError()) return checkEndElement.castTo(Something.class);

        }
      }

      if (thePair == null) {
        final Reporting.Error error = new Reporting.Error(
          "The required property pair has not been given " +
          "in the XML representation of an instance of class Something");
        return Reporting.Result.failure(error);
      }

      if (theItems == null) {
        final Reporting.Error error = new Reporting.Error(
          "The required property items has not been given " +
          "in the XML representation of an instance of class Something");
        return Reporting.Result.failure(error);
      }

      if (theTricky == null) {
        final Reporting.Error error = new Reporting.Error(
          "The required property tricky has not been given " +
          "in the XML representation of an instance of class Something");
        return Reporting.Result.failure(error);
      }

      return Reporting.Result.success(new Something(
        thePair,
        theItems,
        theTricky));
    }

    /**
     * Deserialize an instance of class Something from an XML element.
     */
    private static Reporting.Result<? extends Something> trySomethingFromElement(
      XMLEventReader reader) {
      return parseInstanceFromElement(
        reader,
        Something.class,
        (elementName, isEmptyElement) -> {
          if (!"something".equals(elementName)) {
            final Reporting.Error error = new Reporting.Error(
              "Expected an element representing an instance of class Something " +
              "with element name something, but got: " + elementName);
            return Reporting.Result.failure(error);
          }

          return trySomethingFromSequence(reader, isEmptyElement);
        });
    }
  }

  /**
   * Deserialize instances of meta-model classes from XML.
   */
  /** <pre>
   * Here is an example how to parse an instance of class IAbstractItem:
   * {@code
   * XMLEventReader reader = xmlFactory.createXMLEventReader(...some arguments...);
   * IAbstractItem anInstance = Deserialize.deserializeIAbstractItem(
   *   reader);
   * }
   * </pre>
   *
   * <pre>
   * If the elements live in a namespace, you have to supply it. For example:
   * {@code
   * XMLEventReader reader = xmlFactory.createXMLEventReader(...some arguments...);
   * IAbstractItem anInstance = Deserialize.deserializeIAbstractItem(
   *   reader,
   *   "http://www.example.com/5/12");
   * }
   * </pre>
   */
  public static class Deserialize
  {
    /**
     * Deserialize an instance of IAbstractItem from {@code reader}.
     *
     * @param reader Initialized XML reader with reader.peek() set to the element
     */
    public static IAbstractItem deserializeIAbstractItem(
      XMLEventReader reader) {

      _DeserializeImplementation.skipStartDocument(reader);
      _DeserializeImplementation.skipWhitespaceAndComments(reader);

      Reporting.Result<? extends IAbstractItem> result =
        _DeserializeImplementation.tryIAbstractItemFromElement(
          reader);

      return result.onError(error -> {
        error.prependSegment(new Reporting.NameSegment("iabstractitem"));
        throw new DeserializeException(
          Reporting.generateRelativeXPath(error.getPathSegments()),
          error.getCause());
      });
    }

    /**
     * Deserialize an instance of SomeItem from {@code reader}.
     *
     * @param reader Initialized XML reader with reader.peek() set to the element
     */
    public static SomeItem deserializeSomeItem(
      XMLEventReader reader) {

      _DeserializeImplementation.skipStartDocument(reader);
      _DeserializeImplementation.skipWhitespaceAndComments(reader);

      Reporting.Result<? extends SomeItem> result =
        _DeserializeImplementation.trySomeItemFromElement(
          reader);

      return result.onError(error -> {
        error.prependSegment(new Reporting.NameSegment("someitem"));
        throw new DeserializeException(
          Reporting.generateRelativeXPath(error.getPathSegments()),
          error.getCause());
      });
    }

    /**
     * Deserialize an instance of AnotherItem from {@code reader}.
     *
     * @param reader Initialized XML reader with reader.peek() set to the element
     */
    public static AnotherItem deserializeAnotherItem(
      XMLEventReader reader) {

      _DeserializeImplementation.skipStartDocument(reader);
      _DeserializeImplementation.skipWhitespaceAndComments(reader);

      Reporting.Result<? extends AnotherItem> result =
        _DeserializeImplementation.tryAnotherItemFromElement(
          reader);

      return result.onError(error -> {
        error.prependSegment(new Reporting.NameSegment("anotheritem"));
        throw new DeserializeException(
          Reporting.generateRelativeXPath(error.getPathSegments()),
          error.getCause());
      });
    }

    /**
     * Deserialize an instance of Something from {@code reader}.
     *
     * @param reader Initialized XML reader with reader.peek() set to the element
     */
    public static Something deserializeSomething(
      XMLEventReader reader) {

      _DeserializeImplementation.skipStartDocument(reader);
      _DeserializeImplementation.skipWhitespaceAndComments(reader);

      Reporting.Result<? extends Something> result =
        _DeserializeImplementation.trySomethingFromElement(
          reader);

      return result.onError(error -> {
        error.prependSegment(new Reporting.NameSegment("something"));
        throw new DeserializeException(
          Reporting.generateRelativeXPath(error.getPathSegments()),
          error.getCause());
      });
    }
  }

  /**
   * Serialize recursively the instances as XML elements.
   */
  static class _VisitorWithWriter
    extends AbstractVisitorWithContext<XMLStreamWriter> {

    private boolean topLevel = true;

    @FunctionalInterface
    private interface ElementContentSerializer<T> {
      void serialize(T that, XMLStreamWriter writer) throws XMLStreamException;
    }

    /**
     * Write {@code that} as an XML element named {@code name}, delegating
     * the content in-between the start and the end tag to
     * {@code serializeContent}.
     *
     * <p>This is shared by all the property kinds (primitive, enumeration,
     * class, interface, list) as they all wrap their content in exactly the
     * same way.
     */
    private <T> void serializeElement(
      String name,
      T that,
      XMLStreamWriter writer,
      ElementContentSerializer<T> serializeContent) {
      try {
        writer.writeStartElement(name);
        if (topLevel) {
          writer.writeNamespace("xmlns", AAS_NAME_SPACE);
          topLevel = false;
        }
        serializeContent.serialize(that, writer);
        writer.writeEndElement();
      } catch (XMLStreamException exception) {
        throw new SerializeException("", exception.getMessage());
      }
    }

    /**
     * Adapt {@code writeItem} to serialize every item of an iterable.
     *
     * <p>This is shared by all the list-typed properties, which only need to
     * supply how a single item is written.
     */
    private <T> ElementContentSerializer<Iterable<T>> serializeItems(
      ElementContentSerializer<T> writeItem) {
      return (items, w) -> {
        for (T item : items) {
          writeItem.serialize(item, w);
        }
      };
    }

    /**
     * Adapt {@code writeContent} to serialize a value wrapped in its own
     * {@code name} element.
     *
     * <p>This is only needed for a scalar item (a primitive or an enumeration
     * literal), which is wrapped in a positional {@code v}/{@code v1}/
     * {@code v2} *etc.* element; a class item is dispatched through its own
     * natural element tag by {@code this::visit} already, so it needs no
     * such wrapping.
     *
     * <p>{@code name} is a plain runtime string, not a type, so it can not be
     * pinned via a generic type parameter -- binding it requires an actual
     * closure, built once here.
     */
    private <T> ElementContentSerializer<T> asNamedElementSerializer(
      String name, ElementContentSerializer<T> writeContent) {
      return (that, w) -> serializeElement(name, that, w, writeContent);
    }

    /**
     * Write {@code that.toString()} as XML content.
     *
     * <p>This is shared by every {@code boolean}/{@code long}/{@code double}/
     * {@code String}-typed property or list item, standing in for the property-
     * or item-specific {@link ElementContentSerializer}.
     */
    private <T> void writeStringifiedContent(T that, XMLStreamWriter writer)
      throws XMLStreamException {
      writer.writeCharacters(that.toString());
    }

    /**
     * Write {@code that} as base64-encoded XML content.
     *
     * <p>This is shared by every {@code byte[]}-typed property or list item,
     * standing in for the property- or item-specific
     * {@link ElementContentSerializer}.
     */
    private void writeByteArrayContent(byte[] that, XMLStreamWriter writer)
      throws XMLStreamException {
      writer.writeCharacters(
        Base64.getEncoder().encodeToString(that));
    }

    /**
     * Write a literal of {@link Result} as XML content.
     *
     * <p>This is shared by every Result-typed property or list item,
     * standing in for the property- or item-specific
     * {@link ElementContentSerializer}.
     */
    private void writeResultContent(Result that, XMLStreamWriter writer)
      throws XMLStreamException {
      writer.writeCharacters(Stringification.mustToString(that));
    }

    /**
     * Adapt {@code writeItem1}, ..., {@code writeItem2} to serialize a
     * tuple of 2 item(s), each writing itself (whether wrapped in its own
     * positional element or dispatched through its own natural element tag, as
     * decided by the caller -- see {@link #asNamedElementSerializer}).
     */
    private <T1, T2> ElementContentSerializer<Tuple2<T1, T2>> serializeTuple2(
      ElementContentSerializer<T1> writeItem1,
      ElementContentSerializer<T2> writeItem2) {
      return (value, w) -> {
        writeItem1.serialize(value.item1(), w);
        writeItem2.serialize(value.item2(), w);
      };
    }

    /**
     * Adapt {@code writeItem1}, ..., {@code writeItem6} to serialize a
     * tuple of 6 item(s), each writing itself (whether wrapped in its own
     * positional element or dispatched through its own natural element tag, as
     * decided by the caller -- see {@link #asNamedElementSerializer}).
     */
    private <T1, T2, T3, T4, T5, T6> ElementContentSerializer<Tuple6<T1, T2, T3, T4, T5, T6>> serializeTuple6(
      ElementContentSerializer<T1> writeItem1,
      ElementContentSerializer<T2> writeItem2,
      ElementContentSerializer<T3> writeItem3,
      ElementContentSerializer<T4> writeItem4,
      ElementContentSerializer<T5> writeItem5,
      ElementContentSerializer<T6> writeItem6) {
      return (value, w) -> {
        writeItem1.serialize(value.item1(), w);
        writeItem2.serialize(value.item2(), w);
        writeItem3.serialize(value.item3(), w);
        writeItem4.serialize(value.item4(), w);
        writeItem5.serialize(value.item5(), w);
        writeItem6.serialize(value.item6(), w);
      };
    }

    private void someItemToSequence(
      ISomeItem that,
      XMLStreamWriter writer) {
      serializeElement(
        "name",
        that.getName(),
        writer,
        this::writeStringifiedContent);
    }

    @Override
    public void visitSomeItem(
      ISomeItem that,
      XMLStreamWriter writer) {
      try {
        writer.writeStartElement(
          "someItem");
        if (topLevel) {
          writer.writeNamespace("xmlns", AAS_NAME_SPACE);
          topLevel = false;
        }
        this.someItemToSequence(
          that,
          writer);
        writer.writeEndElement();
      } catch (XMLStreamException exception) {
        throw new SerializeException("", exception.getMessage());
      }
    }

    private void anotherItemToSequence(
      IAnotherItem that,
      XMLStreamWriter writer) {
      serializeElement(
        "serialNumber",
        that.getSerialNumber(),
        writer,
        this::writeStringifiedContent);
    }

    @Override
    public void visitAnotherItem(
      IAnotherItem that,
      XMLStreamWriter writer) {
      try {
        writer.writeStartElement(
          "anotherItem");
        if (topLevel) {
          writer.writeNamespace("xmlns", AAS_NAME_SPACE);
          topLevel = false;
        }
        this.anotherItemToSequence(
          that,
          writer);
        writer.writeEndElement();
      } catch (XMLStreamException exception) {
        throw new SerializeException("", exception.getMessage());
      }
    }

    private void somethingToSequence(
      ISomething that,
      XMLStreamWriter writer) {
      serializeElement(
        "pair",
        that.getPair(),
        writer,
        serializeTuple2(
          asNamedElementSerializer("v1", this::writeStringifiedContent),
          asNamedElementSerializer("v2", this::writeStringifiedContent)));

      serializeElement(
        "items",
        that.getItems(),
        writer,
        serializeTuple2(
          this::visit,
          this::visit));

      serializeElement(
        "tricky",
        that.getTricky(),
        writer,
        serializeTuple6(
          asNamedElementSerializer("v1", this::writeStringifiedContent),
          this::visit,
          this::visit,
          this::visit,
          asNamedElementSerializer("v5", this::writeStringifiedContent),
          asNamedElementSerializer("v6", this::writeResultContent)));
    }

    @Override
    public void visitSomething(
      ISomething that,
      XMLStreamWriter writer) {
      try {
        writer.writeStartElement(
          "something");
        if (topLevel) {
          writer.writeNamespace("xmlns", AAS_NAME_SPACE);
          topLevel = false;
        }
        this.somethingToSequence(
          that,
          writer);
        writer.writeEndElement();
      } catch (XMLStreamException exception) {
        throw new SerializeException("", exception.getMessage());
      }
    }
  }

  /**
   * Serialize instances of meta-model classes to XML.
   */
  /**
   * <pre>
   * Here is an example how to serialize an instance of IAbstractItem:
   * {@code
   * IClass anInstance = new IAbstractItem(
   *     ... some constructor arguments ...
   * );
   * XMLStreamWriter writer = xmlWriterFactory.createXMLStreamWriter(...some arguments...);
   * Serialize.to(
   *   anInstance,
   *   writer);
   * }
   * </pre>
   */
  public static class Serialize
  {
    /**
     * Serialize an instance of the meta-model to XML.
     */
    public static void to(
      IClass that,
      XMLStreamWriter writer) throws SerializeException {
      _VisitorWithWriter visitor = new _VisitorWithWriter();
      visitor.visit(
        that, writer);
    }
  }
}

/*
 * This code has been automatically generated by aas-core-codegen.
 * Do NOT edit or append.
 */
