<?xml version="1.0" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="https://dummy.com" elementFormDefault="qualified" targetNamespace="https://dummy.com">
  <xs:group name="mixedAbstractDescendantOne">
    <xs:sequence>
      <xs:group ref="mixedAbstractMember"/>
      <xs:element name="uniqueToAbstractDescendantOne" type="xs:string"/>
    </xs:sequence>
  </xs:group>
  <xs:group name="mixedAbstractDescendantTwo">
    <xs:sequence>
      <xs:group ref="mixedAbstractMember"/>
      <xs:element name="uniqueToAbstractDescendantTwo" type="xs:string"/>
    </xs:sequence>
  </xs:group>
  <xs:group name="mixedAbstractMember">
    <xs:sequence/>
  </xs:group>
  <xs:group name="mixedAbstractMember_choice">
    <xs:choice>
      <xs:element name="mixedAbstractDescendantOne" type="mixedAbstractDescendantOne_t"/>
      <xs:element name="mixedAbstractDescendantTwo" type="mixedAbstractDescendantTwo_t"/>
    </xs:choice>
  </xs:group>
  <xs:group name="mixedConcreteLeaf">
    <xs:sequence>
      <xs:element name="uniqueToConcreteLeaf" type="xs:string"/>
    </xs:sequence>
  </xs:group>
  <xs:group name="mixedConcreteWithDescendants">
    <xs:sequence>
      <xs:element name="someBaseProperty" type="xs:string"/>
    </xs:sequence>
  </xs:group>
  <xs:group name="mixedConcreteWithDescendantsChild">
    <xs:sequence>
      <xs:group ref="mixedConcreteWithDescendants"/>
      <xs:element name="someChildProperty" type="xs:string"/>
    </xs:sequence>
  </xs:group>
  <xs:group name="mixedConcreteWithDescendants_choice">
    <xs:choice>
      <xs:element name="mixedConcreteWithDescendants" type="mixedConcreteWithDescendants_t"/>
      <xs:element name="mixedConcreteWithDescendantsChild" type="mixedConcreteWithDescendantsChild_t"/>
    </xs:choice>
  </xs:group>
  <xs:group name="mixedUnion_choice">
    <xs:choice>
      <xs:element name="mixedAbstractDescendantOne" type="mixedAbstractDescendantOne_t"/>
      <xs:element name="mixedAbstractDescendantTwo" type="mixedAbstractDescendantTwo_t"/>
      <xs:element name="mixedConcreteWithDescendantsChild" type="mixedConcreteWithDescendantsChild_t"/>
      <xs:element name="mixedConcreteWithDescendants" type="mixedConcreteWithDescendants_t"/>
      <xs:element name="mixedConcreteLeaf" type="mixedConcreteLeaf_t"/>
    </xs:choice>
  </xs:group>
  <xs:group name="modelTypedFirst">
    <xs:sequence>
      <xs:element name="someProperty" type="xs:string"/>
    </xs:sequence>
  </xs:group>
  <xs:group name="modelTypedSecond">
    <xs:sequence>
      <xs:element name="someProperty" type="xs:string"/>
    </xs:sequence>
  </xs:group>
  <xs:group name="modelTypedUnion_choice">
    <xs:choice>
      <xs:element name="modelTypedFirst" type="modelTypedFirst_t"/>
      <xs:element name="modelTypedSecond" type="modelTypedSecond_t"/>
    </xs:choice>
  </xs:group>
  <xs:group name="something">
    <xs:sequence>
      <xs:element name="structuralProperty">
        <xs:complexType>
          <xs:sequence>
            <xs:group ref="structuralUnion_choice"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="mixedProperty">
        <xs:complexType>
          <xs:sequence>
            <xs:group ref="mixedUnion_choice"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="modelTypedProperty">
        <xs:complexType>
          <xs:sequence>
            <xs:group ref="modelTypedUnion_choice"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:group>
  <xs:group name="structuralFirst">
    <xs:sequence>
      <xs:element name="uniqueToFirst" type="xs:string"/>
    </xs:sequence>
  </xs:group>
  <xs:group name="structuralSecond">
    <xs:sequence>
      <xs:element name="uniqueToSecond" type="xs:string"/>
    </xs:sequence>
  </xs:group>
  <xs:group name="structuralUnion_choice">
    <xs:choice>
      <xs:element name="structuralFirst" type="structuralFirst_t"/>
      <xs:element name="structuralSecond" type="structuralSecond_t"/>
    </xs:choice>
  </xs:group>
  <xs:complexType name="mixedAbstractDescendantOne_t">
    <xs:sequence>
      <xs:group ref="mixedAbstractDescendantOne"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="mixedAbstractDescendantTwo_t">
    <xs:sequence>
      <xs:group ref="mixedAbstractDescendantTwo"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="mixedAbstractMember_t">
    <xs:sequence>
      <xs:group ref="mixedAbstractMember"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="mixedConcreteLeaf_t">
    <xs:sequence>
      <xs:group ref="mixedConcreteLeaf"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="mixedConcreteWithDescendantsChild_t">
    <xs:sequence>
      <xs:group ref="mixedConcreteWithDescendantsChild"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="mixedConcreteWithDescendants_t">
    <xs:sequence>
      <xs:group ref="mixedConcreteWithDescendants"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="modelTypedFirst_t">
    <xs:sequence>
      <xs:group ref="modelTypedFirst"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="modelTypedSecond_t">
    <xs:sequence>
      <xs:group ref="modelTypedSecond"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="something_t">
    <xs:sequence>
      <xs:group ref="something"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="structuralFirst_t">
    <xs:sequence>
      <xs:group ref="structuralFirst"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="structuralSecond_t">
    <xs:sequence>
      <xs:group ref="structuralSecond"/>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="something" type="something_t"/>
</xs:schema>
