// Package enhancing allows for enhancement of model instances with your custom data.
package enhancing

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.

import (
	"fmt"

	aascommon "github.com/dummy-works/dummy/common"
	aastypes "github.com/dummy-works/dummy/types"
)

type enhanced[E any] interface {
	// Get the enhancement from the enhanced instance.
	getEnhancement() E

	// Set the enhancement of the enhanced instance.
	setEnhancement(E)
}

type enhancedStructuralFirst[E any] struct {
	instance aastypes.IStructuralFirst
	enhancement E
}

func (esf *enhancedStructuralFirst[E]) ModelType(
) aastypes.ModelType {
	return esf.instance.ModelType()
}

func (esf *enhancedStructuralFirst[E]) DescendOnce(
	action func(aastypes.IClass)bool,
) bool {
	return esf.instance.DescendOnce(action)
}

func (esf *enhancedStructuralFirst[E]) Descend(
	action func(aastypes.IClass) bool,
) bool {
	return esf.instance.Descend(action)
}

func (esf *enhancedStructuralFirst[E]) UniqueToFirst(
) string {
	return esf.instance.UniqueToFirst()
}

func (esf *enhancedStructuralFirst[E]) SetUniqueToFirst(
	value string,
) {
	esf.instance.SetUniqueToFirst(value)
}

func (esf *enhancedStructuralFirst[E]) getEnhancement(
) E {
	return esf.enhancement
}

func (esf *enhancedStructuralFirst[E]) setEnhancement(
	value E,
) {
	esf.enhancement = value
}

func wrapStructuralFirst[E any](
	that aastypes.IStructuralFirst,
	factory func(aastypes.IClass) (E, bool),
) (result aastypes.IStructuralFirst) {
	// We assume that we already checked whether `that` has been enhanced
	// in the caller.

	enh, shouldEnhance := factory(that)
	if shouldEnhance {
		result = &enhancedStructuralFirst[E]{
			instance: that,
			enhancement: enh,
		}
	} else {
		result = that
	}

	return
}

type enhancedStructuralSecond[E any] struct {
	instance aastypes.IStructuralSecond
	enhancement E
}

func (ess *enhancedStructuralSecond[E]) ModelType(
) aastypes.ModelType {
	return ess.instance.ModelType()
}

func (ess *enhancedStructuralSecond[E]) DescendOnce(
	action func(aastypes.IClass)bool,
) bool {
	return ess.instance.DescendOnce(action)
}

func (ess *enhancedStructuralSecond[E]) Descend(
	action func(aastypes.IClass) bool,
) bool {
	return ess.instance.Descend(action)
}

func (ess *enhancedStructuralSecond[E]) UniqueToSecond(
) string {
	return ess.instance.UniqueToSecond()
}

func (ess *enhancedStructuralSecond[E]) SetUniqueToSecond(
	value string,
) {
	ess.instance.SetUniqueToSecond(value)
}

func (ess *enhancedStructuralSecond[E]) getEnhancement(
) E {
	return ess.enhancement
}

func (ess *enhancedStructuralSecond[E]) setEnhancement(
	value E,
) {
	ess.enhancement = value
}

func wrapStructuralSecond[E any](
	that aastypes.IStructuralSecond,
	factory func(aastypes.IClass) (E, bool),
) (result aastypes.IStructuralSecond) {
	// We assume that we already checked whether `that` has been enhanced
	// in the caller.

	enh, shouldEnhance := factory(that)
	if shouldEnhance {
		result = &enhancedStructuralSecond[E]{
			instance: that,
			enhancement: enh,
		}
	} else {
		result = that
	}

	return
}

type enhancedMixedAbstractDescendantOne[E any] struct {
	instance aastypes.IMixedAbstractDescendantOne
	enhancement E
}

func (emado *enhancedMixedAbstractDescendantOne[E]) ModelType(
) aastypes.ModelType {
	return emado.instance.ModelType()
}

func (emado *enhancedMixedAbstractDescendantOne[E]) DescendOnce(
	action func(aastypes.IClass)bool,
) bool {
	return emado.instance.DescendOnce(action)
}

func (emado *enhancedMixedAbstractDescendantOne[E]) Descend(
	action func(aastypes.IClass) bool,
) bool {
	return emado.instance.Descend(action)
}

func (emado *enhancedMixedAbstractDescendantOne[E]) UniqueToAbstractDescendantOne(
) string {
	return emado.instance.UniqueToAbstractDescendantOne()
}

func (emado *enhancedMixedAbstractDescendantOne[E]) SetUniqueToAbstractDescendantOne(
	value string,
) {
	emado.instance.SetUniqueToAbstractDescendantOne(value)
}

func (emado *enhancedMixedAbstractDescendantOne[E]) getEnhancement(
) E {
	return emado.enhancement
}

func (emado *enhancedMixedAbstractDescendantOne[E]) setEnhancement(
	value E,
) {
	emado.enhancement = value
}

func wrapMixedAbstractDescendantOne[E any](
	that aastypes.IMixedAbstractDescendantOne,
	factory func(aastypes.IClass) (E, bool),
) (result aastypes.IMixedAbstractDescendantOne) {
	// We assume that we already checked whether `that` has been enhanced
	// in the caller.

	enh, shouldEnhance := factory(that)
	if shouldEnhance {
		result = &enhancedMixedAbstractDescendantOne[E]{
			instance: that,
			enhancement: enh,
		}
	} else {
		result = that
	}

	return
}

type enhancedMixedAbstractDescendantTwo[E any] struct {
	instance aastypes.IMixedAbstractDescendantTwo
	enhancement E
}

func (emadt *enhancedMixedAbstractDescendantTwo[E]) ModelType(
) aastypes.ModelType {
	return emadt.instance.ModelType()
}

func (emadt *enhancedMixedAbstractDescendantTwo[E]) DescendOnce(
	action func(aastypes.IClass)bool,
) bool {
	return emadt.instance.DescendOnce(action)
}

func (emadt *enhancedMixedAbstractDescendantTwo[E]) Descend(
	action func(aastypes.IClass) bool,
) bool {
	return emadt.instance.Descend(action)
}

func (emadt *enhancedMixedAbstractDescendantTwo[E]) UniqueToAbstractDescendantTwo(
) string {
	return emadt.instance.UniqueToAbstractDescendantTwo()
}

func (emadt *enhancedMixedAbstractDescendantTwo[E]) SetUniqueToAbstractDescendantTwo(
	value string,
) {
	emadt.instance.SetUniqueToAbstractDescendantTwo(value)
}

func (emadt *enhancedMixedAbstractDescendantTwo[E]) getEnhancement(
) E {
	return emadt.enhancement
}

func (emadt *enhancedMixedAbstractDescendantTwo[E]) setEnhancement(
	value E,
) {
	emadt.enhancement = value
}

func wrapMixedAbstractDescendantTwo[E any](
	that aastypes.IMixedAbstractDescendantTwo,
	factory func(aastypes.IClass) (E, bool),
) (result aastypes.IMixedAbstractDescendantTwo) {
	// We assume that we already checked whether `that` has been enhanced
	// in the caller.

	enh, shouldEnhance := factory(that)
	if shouldEnhance {
		result = &enhancedMixedAbstractDescendantTwo[E]{
			instance: that,
			enhancement: enh,
		}
	} else {
		result = that
	}

	return
}

type enhancedMixedConcreteWithDescendants[E any] struct {
	instance aastypes.IMixedConcreteWithDescendants
	enhancement E
}

func (emcwd *enhancedMixedConcreteWithDescendants[E]) ModelType(
) aastypes.ModelType {
	return emcwd.instance.ModelType()
}

func (emcwd *enhancedMixedConcreteWithDescendants[E]) DescendOnce(
	action func(aastypes.IClass)bool,
) bool {
	return emcwd.instance.DescendOnce(action)
}

func (emcwd *enhancedMixedConcreteWithDescendants[E]) Descend(
	action func(aastypes.IClass) bool,
) bool {
	return emcwd.instance.Descend(action)
}

func (emcwd *enhancedMixedConcreteWithDescendants[E]) SomeBaseProperty(
) string {
	return emcwd.instance.SomeBaseProperty()
}

func (emcwd *enhancedMixedConcreteWithDescendants[E]) SetSomeBaseProperty(
	value string,
) {
	emcwd.instance.SetSomeBaseProperty(value)
}

func (emcwd *enhancedMixedConcreteWithDescendants[E]) getEnhancement(
) E {
	return emcwd.enhancement
}

func (emcwd *enhancedMixedConcreteWithDescendants[E]) setEnhancement(
	value E,
) {
	emcwd.enhancement = value
}

func wrapMixedConcreteWithDescendants[E any](
	that aastypes.IMixedConcreteWithDescendants,
	factory func(aastypes.IClass) (E, bool),
) (result aastypes.IMixedConcreteWithDescendants) {
	// We assume that we already checked whether `that` has been enhanced
	// in the caller.

	enh, shouldEnhance := factory(that)
	if shouldEnhance {
		result = &enhancedMixedConcreteWithDescendants[E]{
			instance: that,
			enhancement: enh,
		}
	} else {
		result = that
	}

	return
}

type enhancedMixedConcreteWithDescendantsChild[E any] struct {
	instance aastypes.IMixedConcreteWithDescendantsChild
	enhancement E
}

func (emcwdc *enhancedMixedConcreteWithDescendantsChild[E]) ModelType(
) aastypes.ModelType {
	return emcwdc.instance.ModelType()
}

func (emcwdc *enhancedMixedConcreteWithDescendantsChild[E]) DescendOnce(
	action func(aastypes.IClass)bool,
) bool {
	return emcwdc.instance.DescendOnce(action)
}

func (emcwdc *enhancedMixedConcreteWithDescendantsChild[E]) Descend(
	action func(aastypes.IClass) bool,
) bool {
	return emcwdc.instance.Descend(action)
}

func (emcwdc *enhancedMixedConcreteWithDescendantsChild[E]) SomeBaseProperty(
) string {
	return emcwdc.instance.SomeBaseProperty()
}

func (emcwdc *enhancedMixedConcreteWithDescendantsChild[E]) SetSomeBaseProperty(
	value string,
) {
	emcwdc.instance.SetSomeBaseProperty(value)
}

func (emcwdc *enhancedMixedConcreteWithDescendantsChild[E]) SomeChildProperty(
) string {
	return emcwdc.instance.SomeChildProperty()
}

func (emcwdc *enhancedMixedConcreteWithDescendantsChild[E]) SetSomeChildProperty(
	value string,
) {
	emcwdc.instance.SetSomeChildProperty(value)
}

func (emcwdc *enhancedMixedConcreteWithDescendantsChild[E]) getEnhancement(
) E {
	return emcwdc.enhancement
}

func (emcwdc *enhancedMixedConcreteWithDescendantsChild[E]) setEnhancement(
	value E,
) {
	emcwdc.enhancement = value
}

func wrapMixedConcreteWithDescendantsChild[E any](
	that aastypes.IMixedConcreteWithDescendantsChild,
	factory func(aastypes.IClass) (E, bool),
) (result aastypes.IMixedConcreteWithDescendantsChild) {
	// We assume that we already checked whether `that` has been enhanced
	// in the caller.

	enh, shouldEnhance := factory(that)
	if shouldEnhance {
		result = &enhancedMixedConcreteWithDescendantsChild[E]{
			instance: that,
			enhancement: enh,
		}
	} else {
		result = that
	}

	return
}

type enhancedMixedConcreteLeaf[E any] struct {
	instance aastypes.IMixedConcreteLeaf
	enhancement E
}

func (emcl *enhancedMixedConcreteLeaf[E]) ModelType(
) aastypes.ModelType {
	return emcl.instance.ModelType()
}

func (emcl *enhancedMixedConcreteLeaf[E]) DescendOnce(
	action func(aastypes.IClass)bool,
) bool {
	return emcl.instance.DescendOnce(action)
}

func (emcl *enhancedMixedConcreteLeaf[E]) Descend(
	action func(aastypes.IClass) bool,
) bool {
	return emcl.instance.Descend(action)
}

func (emcl *enhancedMixedConcreteLeaf[E]) UniqueToConcreteLeaf(
) string {
	return emcl.instance.UniqueToConcreteLeaf()
}

func (emcl *enhancedMixedConcreteLeaf[E]) SetUniqueToConcreteLeaf(
	value string,
) {
	emcl.instance.SetUniqueToConcreteLeaf(value)
}

func (emcl *enhancedMixedConcreteLeaf[E]) getEnhancement(
) E {
	return emcl.enhancement
}

func (emcl *enhancedMixedConcreteLeaf[E]) setEnhancement(
	value E,
) {
	emcl.enhancement = value
}

func wrapMixedConcreteLeaf[E any](
	that aastypes.IMixedConcreteLeaf,
	factory func(aastypes.IClass) (E, bool),
) (result aastypes.IMixedConcreteLeaf) {
	// We assume that we already checked whether `that` has been enhanced
	// in the caller.

	enh, shouldEnhance := factory(that)
	if shouldEnhance {
		result = &enhancedMixedConcreteLeaf[E]{
			instance: that,
			enhancement: enh,
		}
	} else {
		result = that
	}

	return
}

type enhancedModelTypedFirst[E any] struct {
	instance aastypes.IModelTypedFirst
	enhancement E
}

func (emtf *enhancedModelTypedFirst[E]) ModelType(
) aastypes.ModelType {
	return emtf.instance.ModelType()
}

func (emtf *enhancedModelTypedFirst[E]) DescendOnce(
	action func(aastypes.IClass)bool,
) bool {
	return emtf.instance.DescendOnce(action)
}

func (emtf *enhancedModelTypedFirst[E]) Descend(
	action func(aastypes.IClass) bool,
) bool {
	return emtf.instance.Descend(action)
}

func (emtf *enhancedModelTypedFirst[E]) SomeProperty(
) string {
	return emtf.instance.SomeProperty()
}

func (emtf *enhancedModelTypedFirst[E]) SetSomeProperty(
	value string,
) {
	emtf.instance.SetSomeProperty(value)
}

func (emtf *enhancedModelTypedFirst[E]) getEnhancement(
) E {
	return emtf.enhancement
}

func (emtf *enhancedModelTypedFirst[E]) setEnhancement(
	value E,
) {
	emtf.enhancement = value
}

func wrapModelTypedFirst[E any](
	that aastypes.IModelTypedFirst,
	factory func(aastypes.IClass) (E, bool),
) (result aastypes.IModelTypedFirst) {
	// We assume that we already checked whether `that` has been enhanced
	// in the caller.

	enh, shouldEnhance := factory(that)
	if shouldEnhance {
		result = &enhancedModelTypedFirst[E]{
			instance: that,
			enhancement: enh,
		}
	} else {
		result = that
	}

	return
}

type enhancedModelTypedSecond[E any] struct {
	instance aastypes.IModelTypedSecond
	enhancement E
}

func (emts *enhancedModelTypedSecond[E]) ModelType(
) aastypes.ModelType {
	return emts.instance.ModelType()
}

func (emts *enhancedModelTypedSecond[E]) DescendOnce(
	action func(aastypes.IClass)bool,
) bool {
	return emts.instance.DescendOnce(action)
}

func (emts *enhancedModelTypedSecond[E]) Descend(
	action func(aastypes.IClass) bool,
) bool {
	return emts.instance.Descend(action)
}

func (emts *enhancedModelTypedSecond[E]) SomeProperty(
) string {
	return emts.instance.SomeProperty()
}

func (emts *enhancedModelTypedSecond[E]) SetSomeProperty(
	value string,
) {
	emts.instance.SetSomeProperty(value)
}

func (emts *enhancedModelTypedSecond[E]) getEnhancement(
) E {
	return emts.enhancement
}

func (emts *enhancedModelTypedSecond[E]) setEnhancement(
	value E,
) {
	emts.enhancement = value
}

func wrapModelTypedSecond[E any](
	that aastypes.IModelTypedSecond,
	factory func(aastypes.IClass) (E, bool),
) (result aastypes.IModelTypedSecond) {
	// We assume that we already checked whether `that` has been enhanced
	// in the caller.

	enh, shouldEnhance := factory(that)
	if shouldEnhance {
		result = &enhancedModelTypedSecond[E]{
			instance: that,
			enhancement: enh,
		}
	} else {
		result = that
	}

	return
}

type enhancedSomething[E any] struct {
	instance aastypes.ISomething
	enhancement E
}

func (es *enhancedSomething[E]) ModelType(
) aastypes.ModelType {
	return es.instance.ModelType()
}

func (es *enhancedSomething[E]) DescendOnce(
	action func(aastypes.IClass)bool,
) bool {
	return es.instance.DescendOnce(action)
}

func (es *enhancedSomething[E]) Descend(
	action func(aastypes.IClass) bool,
) bool {
	return es.instance.Descend(action)
}

func (es *enhancedSomething[E]) StructuralProperty(
) *aastypes.StructuralUnion {
	return es.instance.StructuralProperty()
}

func (es *enhancedSomething[E]) SetStructuralProperty(
	value *aastypes.StructuralUnion,
) {
	es.instance.SetStructuralProperty(value)
}

func (es *enhancedSomething[E]) MixedProperty(
) *aastypes.MixedUnion {
	return es.instance.MixedProperty()
}

func (es *enhancedSomething[E]) SetMixedProperty(
	value *aastypes.MixedUnion,
) {
	es.instance.SetMixedProperty(value)
}

func (es *enhancedSomething[E]) ModelTypedProperty(
) *aastypes.ModelTypedUnion {
	return es.instance.ModelTypedProperty()
}

func (es *enhancedSomething[E]) SetModelTypedProperty(
	value *aastypes.ModelTypedUnion,
) {
	es.instance.SetModelTypedProperty(value)
}

func (es *enhancedSomething[E]) ListStructuralProperty(
) []*aastypes.StructuralUnion {
	return es.instance.ListStructuralProperty()
}

func (es *enhancedSomething[E]) SetListStructuralProperty(
	value []*aastypes.StructuralUnion,
) {
	es.instance.SetListStructuralProperty(value)
}

func (es *enhancedSomething[E]) ListMixedProperty(
) []*aastypes.MixedUnion {
	return es.instance.ListMixedProperty()
}

func (es *enhancedSomething[E]) SetListMixedProperty(
	value []*aastypes.MixedUnion,
) {
	es.instance.SetListMixedProperty(value)
}

func (es *enhancedSomething[E]) ListModelTypedProperty(
) []*aastypes.ModelTypedUnion {
	return es.instance.ListModelTypedProperty()
}

func (es *enhancedSomething[E]) SetListModelTypedProperty(
	value []*aastypes.ModelTypedUnion,
) {
	es.instance.SetListModelTypedProperty(value)
}

func (es *enhancedSomething[E]) TupleProperty(
) aascommon.Tuple3[*aastypes.StructuralUnion, *aastypes.MixedUnion, *aastypes.ModelTypedUnion] {
	return es.instance.TupleProperty()
}

func (es *enhancedSomething[E]) SetTupleProperty(
	value aascommon.Tuple3[*aastypes.StructuralUnion, *aastypes.MixedUnion, *aastypes.ModelTypedUnion],
) {
	es.instance.SetTupleProperty(value)
}

func (es *enhancedSomething[E]) OptionalStructuralProperty(
) *aastypes.StructuralUnion {
	return es.instance.OptionalStructuralProperty()
}

func (es *enhancedSomething[E]) SetOptionalStructuralProperty(
	value *aastypes.StructuralUnion,
) {
	es.instance.SetOptionalStructuralProperty(value)
}

func (es *enhancedSomething[E]) OptionalMixedProperty(
) *aastypes.MixedUnion {
	return es.instance.OptionalMixedProperty()
}

func (es *enhancedSomething[E]) SetOptionalMixedProperty(
	value *aastypes.MixedUnion,
) {
	es.instance.SetOptionalMixedProperty(value)
}

func (es *enhancedSomething[E]) OptionalModelTypedProperty(
) *aastypes.ModelTypedUnion {
	return es.instance.OptionalModelTypedProperty()
}

func (es *enhancedSomething[E]) SetOptionalModelTypedProperty(
	value *aastypes.ModelTypedUnion,
) {
	es.instance.SetOptionalModelTypedProperty(value)
}

func (es *enhancedSomething[E]) getEnhancement(
) E {
	return es.enhancement
}

func (es *enhancedSomething[E]) setEnhancement(
	value E,
) {
	es.enhancement = value
}

func wrapSomething[E any](
	that aastypes.ISomething,
	factory func(aastypes.IClass) (E, bool),
) (result aastypes.ISomething) {
	// We assume that we already checked whether `that` has been enhanced
	// in the caller.

	enh, shouldEnhance := factory(that)
	if shouldEnhance {
		result = &enhancedSomething[E]{
			instance: that,
			enhancement: enh,
		}
	} else {
		result = that
	}

	theStructuralProperty := that.StructuralProperty()
	that.SetStructuralProperty(
		aastypes.StructuralUnionFromUnderlying(
			Wrap[E](
				theStructuralProperty.Underlying(),
				factory,
			),
		),
	)

	theMixedProperty := that.MixedProperty()
	that.SetMixedProperty(
		aastypes.MixedUnionFromUnderlying(
			Wrap[E](
				theMixedProperty.Underlying(),
				factory,
			),
		),
	)

	theModelTypedProperty := that.ModelTypedProperty()
	that.SetModelTypedProperty(
		aastypes.ModelTypedUnionFromUnderlying(
			Wrap[E](
				theModelTypedProperty.Underlying(),
				factory,
			),
		),
	)

	theListStructuralProperty := that.ListStructuralProperty()
	for i, v := range theListStructuralProperty {
		// Update in-situ
		theListStructuralProperty[i] = aastypes.StructuralUnionFromUnderlying(
			Wrap[E](
				v.Underlying(),
				factory,
			),
		)
	}

	theListMixedProperty := that.ListMixedProperty()
	for i, v := range theListMixedProperty {
		// Update in-situ
		theListMixedProperty[i] = aastypes.MixedUnionFromUnderlying(
			Wrap[E](
				v.Underlying(),
				factory,
			),
		)
	}

	theListModelTypedProperty := that.ListModelTypedProperty()
	for i, v := range theListModelTypedProperty {
		// Update in-situ
		theListModelTypedProperty[i] = aastypes.ModelTypedUnionFromUnderlying(
			Wrap[E](
				v.Underlying(),
				factory,
			),
		)
	}

	theTupleProperty := that.TupleProperty()
	theTupleProperty.Item1 = aastypes.StructuralUnionFromUnderlying(
		Wrap[E](
			theTupleProperty.Item1.Underlying(),
			factory,
		),
	)
	theTupleProperty.Item2 = aastypes.MixedUnionFromUnderlying(
		Wrap[E](
			theTupleProperty.Item2.Underlying(),
			factory,
		),
	)
	theTupleProperty.Item3 = aastypes.ModelTypedUnionFromUnderlying(
		Wrap[E](
			theTupleProperty.Item3.Underlying(),
			factory,
		),
	)
	that.SetTupleProperty(
		theTupleProperty,
	)

	theOptionalStructuralProperty := that.OptionalStructuralProperty()
	if theOptionalStructuralProperty != nil {
		that.SetOptionalStructuralProperty(
			aastypes.StructuralUnionFromUnderlying(
				Wrap[E](
					theOptionalStructuralProperty.Underlying(),
					factory,
				),
			),
		)
	}

	theOptionalMixedProperty := that.OptionalMixedProperty()
	if theOptionalMixedProperty != nil {
		that.SetOptionalMixedProperty(
			aastypes.MixedUnionFromUnderlying(
				Wrap[E](
					theOptionalMixedProperty.Underlying(),
					factory,
				),
			),
		)
	}

	theOptionalModelTypedProperty := that.OptionalModelTypedProperty()
	if theOptionalModelTypedProperty != nil {
		that.SetOptionalModelTypedProperty(
			aastypes.ModelTypedUnionFromUnderlying(
				Wrap[E](
					theOptionalModelTypedProperty.Underlying(),
					factory,
				),
			),
		)
	}

	return
}

// Wrap `that` instance recursively with the enhancement produced by the `factory`.
//
// The factory returns the enhancement, and a boolean "should-enhance". If
// the "should-enhance" is false, `that` instance is not enhance, and we simply
// return it. However, we will still continue to enhance the instances referenced
// by `that` instance recursively.
//
// If `that` instance has been already wrapped, panic.
func Wrap[E any](
	that aastypes.IClass,
	factory func(aastypes.IClass) (E, bool),
) (result aastypes.IClass) {
	_, ok := that.(enhanced[E])
	if ok {
		panic(
			fmt.Sprintf(
				"An instance of %T has been already wrapped: %v",
				that, that,
			),
		)
	}

	switch that.ModelType() {
	case aastypes.ModelTypeStructuralFirst:
		result = wrapStructuralFirst[E](
			that.(aastypes.IStructuralFirst),
			factory,
		)
	case aastypes.ModelTypeStructuralSecond:
		result = wrapStructuralSecond[E](
			that.(aastypes.IStructuralSecond),
			factory,
		)
	case aastypes.ModelTypeMixedAbstractDescendantOne:
		result = wrapMixedAbstractDescendantOne[E](
			that.(aastypes.IMixedAbstractDescendantOne),
			factory,
		)
	case aastypes.ModelTypeMixedAbstractDescendantTwo:
		result = wrapMixedAbstractDescendantTwo[E](
			that.(aastypes.IMixedAbstractDescendantTwo),
			factory,
		)
	case aastypes.ModelTypeMixedConcreteWithDescendants:
		result = wrapMixedConcreteWithDescendants[E](
			that.(aastypes.IMixedConcreteWithDescendants),
			factory,
		)
	case aastypes.ModelTypeMixedConcreteWithDescendantsChild:
		result = wrapMixedConcreteWithDescendantsChild[E](
			that.(aastypes.IMixedConcreteWithDescendantsChild),
			factory,
		)
	case aastypes.ModelTypeMixedConcreteLeaf:
		result = wrapMixedConcreteLeaf[E](
			that.(aastypes.IMixedConcreteLeaf),
			factory,
		)
	case aastypes.ModelTypeModelTypedFirst:
		result = wrapModelTypedFirst[E](
			that.(aastypes.IModelTypedFirst),
			factory,
		)
	case aastypes.ModelTypeModelTypedSecond:
		result = wrapModelTypedSecond[E](
			that.(aastypes.IModelTypedSecond),
			factory,
		)
	case aastypes.ModelTypeSomething:
		result = wrapSomething[E](
			that.(aastypes.ISomething),
			factory,
		)
	default:
		panic(
			fmt.Sprintf(
				"Unexpected model type: %v",
				that.ModelType(),
			),
		)
	}

	return
}

// Retrieve the enhancement from `that` instance.
//
// Return the enhancement, or `ok` false, if `that` instance has not been
// enhanced.
func Unwrap[E any](that aastypes.IClass) (enhancement E, ok bool) {
	var enh enhanced[E]
	enh, ok = that.(enhanced[E])
	if !ok {
		return
	}
	enhancement = enh.getEnhancement()
	return
}

// Retrieve the enhancement from `that` instance.
//
// If `that` instance has not been enhanced yet, panic.
func MustUnwrap[E any](that aastypes.IClass) (enhancement E) {
	var ok bool
	enhancement, ok = Unwrap[E](that)
	if !ok {
		panic(
			fmt.Sprintf(
				"An instance of %T has not been wrapped: %v",
				that, that,
			),
		)
	}
	return
}

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.
