/**
 * Provide de/serialization of AAS classes to/from JSON.
 *
 * We can not use one-pass deserialization for JSON since the object
 * properties do not have fixed order, and hence we can not read
 * `modelType` property ahead of the remaining properties.
 */

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.

import * as AasCommon from "./common";
import * as AasTypes from "./types";
import * as AasStringification from "./stringification";

export type JsonValue = string | number | boolean | JsonObject | JsonArray;

export type JsonArray = Iterable<JsonValue>;
export type JsonObject = { [prop: string]: JsonValue };

/**
 * Represent a property on a path to the erroneous value.
 */
export class PropertySegment {
  /**
   * Instance that contains the property
   */
  readonly instance: JsonObject;

  /**
   * Name of the property
   */
  readonly name: string;

  constructor(instance: JsonObject, name: string) {
    this.instance = instance;
    this.name = name;
  }
}

/**
 * Represent an index access on a path to the erroneous value.
 */
export class IndexSegment {
  /**
   * Container that contains the item
   */
  readonly container: JsonArray;

  /**
   * Index of the item
   */
  readonly index: number;

  constructor(container: JsonArray, index: number) {
    if (!Number.isInteger(index)) {
      throw new Error(`Expected an integer for the index, but got: ${index}`);
    }

    this.container = container;
    this.index = index;
  }
}

export type Segment = PropertySegment | IndexSegment;

/**
 * Represent the relative path to the erroneous value.
 */
export class Path {
  private readonly _segments = new Array<Segment>();

  /**
   * Get the segments of the path.
   */
  segments(): Array<Segment> {
    return this._segments;
  }

  /**
   * Insert the `segment` in front of the {@link segments}.
   *
   * @param segment - segment to be prepended to {@link segments}
   */
  prepend(segment: Segment): void {
    this._segments.unshift(segment);
  }

  toString(): string {
    if (this._segments.length === 0) {
      return "";
    }

    const parts = new Array<string>();

    let segment = this._segments[0];

    if (segment instanceof PropertySegment) {
      parts.push(segment.name);
    } else if (segment instanceof IndexSegment) {
      parts.push(`[${segment.index}]`);
    } else {
      throw new Error(`Unexpected segment: ${segment}`);
    }

    for (let i = 1; i < this._segments.length; i++) {
      segment = this._segments[i];
      if (segment instanceof PropertySegment) {
        parts.push(`.${segment.name}`);
      } else if (segment instanceof IndexSegment) {
        parts.push(`[${segment.index}]`);
      } else {
        throw new Error(`Unexpected segment: ${segment}`);
      }
    }

    return parts.join("");
  }
}

// region De-serialization

/**
 * Signal that the JSON de-serialization could not be performed.
 */
export class DeserializationError {
  /**
   * Human-readable explanation of the error
   */
  readonly message: string;

  /**
   * Relative path to the erroneous value
   */
  readonly path: Path;

  constructor(message: string, path: Path | null = null) {
    this.message = message;
    this.path = path ?? new Path();
  }
}

/**
 * Create an error as {@link common.Either}.
 *
 * @param message - human-readable explanation of the error
 * @returns An {@link common.Either } with the error set
 * @typeParam T - type of the value if there had been no error
 */
function newDeserializationError<T>(
  message: string
): AasCommon.Either<T, DeserializationError> {
  return new AasCommon.Either<T, DeserializationError>(
    null,
    new DeserializationError(message)
  );
}

/**
 * Check that `jsonable` looks like a JSON object, without parsing it.
 *
 * @param jsonable - to be checked
 * @returns error, if any
 */
function checkIsJsonObject(jsonable: JsonValue): DeserializationError | null {
  if (jsonable === null) {
    return new DeserializationError(
      "Expected a JSON object, but got null"
    );
  }
  if (Array.isArray(jsonable)) {
    return new DeserializationError(
      "Expected a JSON object, but got a JSON array"
    );
  }
  if (typeof jsonable !== "object") {
    return new DeserializationError(
      `Expected a JSON object, but got: ${typeof jsonable}`
    );
  }

  return null;
}

/**
 * Check that the parsed `modelType` matches `expected`.
 *
 * @param modelType - parsed value of the `modelType` property,
 * or `null` if it was missing
 * @param expected - expected model type
 * @returns error, if any
 */
function checkModelType(
  modelType: string | null,
  expected: string
): DeserializationError | null {
  if (modelType === null) {
    return new DeserializationError(
      "The required property 'modelType' is missing"
    );
  }
  if (modelType != expected) {
    return new DeserializationError(
      `Expected model type '${expected}', ` +
      `but got: ${modelType}`
    );
  }

  return null;
}

/**
 * Check that `jsonable` looks like an iterable which can be parsed
 * item-by-item, without consuming it.
 *
 * @param jsonable - to be checked
 * @returns error, if any
 */
function checkIsIterable(jsonable: JsonValue): DeserializationError | null {
  if (jsonable === null) {
    return new DeserializationError(
      "Expected an iterable, but got null"
    );
  }
  if (typeof jsonable !== "object") {
    return new DeserializationError(
      `Expected an iterable, but got: ${typeof jsonable}`
    );
  }
  if (typeof jsonable[Symbol.iterator] !== "function") {
    return new DeserializationError(
      "Expected an iterable with iterator function, " +
        `but got iterator of type: ${typeof jsonable[Symbol.iterator]}`
    );
  }

  return null;
}

/**
 * Parse every item of `iterable` with `parseItem`.
 *
 * @param iterable - to be parsed item-by-item
 * @param parseItem - to parse a single item of `iterable`
 * @returns parsed items, or an error
 * @typeParam T - type of a single parsed item
 */
function parseArray<T>(
  iterable: Iterable<JsonValue>,
  parseItem: (
    jsonableItem: JsonValue
  ) => AasCommon.Either<T, DeserializationError>
): AasCommon.Either<Array<T>, DeserializationError> {
  const items = new Array<T>();
  let i = 0;
  for (const jsonableItem of iterable) {
    const itemOrError = parseItem(jsonableItem);
    if (itemOrError.error !== null) {
      itemOrError.error.path.prepend(new IndexSegment(iterable, i));
      return new AasCommon.Either<Array<T>, DeserializationError>(
        null,
        itemOrError.error
      );
    }
    items.push(itemOrError.mustValue());
    i++;
  }
  return new AasCommon.Either<Array<T>, DeserializationError>(items, null);
}

/**
 * Parse `jsonable` as a boolean.
 *
 * @param jsonable - to be parsed
 * @returns parsed boolean value, or an error
 */
function booleanFromJsonable(
  jsonable: JsonValue
): AasCommon.Either<boolean, DeserializationError> {
  // `typeof` seems to be optimized these days, so we use it instead of
  // literal comparison, see:
  // https://stackoverflow.com/questions/61786250/is-typeof-faster-than-literal-comparison

  if (jsonable === null) {
    return newDeserializationError<boolean>(
      "Expected a boolean, but got null"
    );
  }
  if (typeof jsonable !== "boolean") {
    return newDeserializationError<boolean>(
      `Expected a boolean, but got ${typeof jsonable}`
    );
  }

  return new AasCommon.Either<boolean, DeserializationError>(jsonable, null);
}

/**
 * Parse `jsonable` as an integer.
 *
 * @param jsonable - to be parsed
 * @returns parsed integer value, or an error
 */
// eslint-disable-next-line @typescript-eslint/no-unused-vars
function integerFromJsonable(
  jsonable: JsonValue
): AasCommon.Either<number, DeserializationError> {
  if (jsonable === null) {
    return newDeserializationError<number>(
      "Expected an integer number, but got null"
    );
  }
  if (typeof jsonable !== "number") {
    return newDeserializationError<number>(
      `Expected an integer number, but got: ${typeof jsonable}`
    );
  }

  if (!Number.isInteger(jsonable)) {
    return newDeserializationError<number>(
      `Expected an integer number, but got: ${jsonable}`
    );
  }

  return new AasCommon.Either<number, DeserializationError>(jsonable, null);
}

/**
 * Parse `jsonable` as a number.
 *
 * @param jsonable - to be parsed
 * @returns parsed numeric value, or an error
 */
// eslint-disable-next-line @typescript-eslint/no-unused-vars
function numberFromJsonable(
  jsonable: JsonValue
): AasCommon.Either<number, DeserializationError> {
  if (jsonable === null) {
    return newDeserializationError<number>(
      "Expected a number, but got null"
    );
  }
  if (typeof jsonable !== "number") {
    return newDeserializationError<number>(
      `Expected a number, but got: ${typeof jsonable}`
    );
  }

  return new AasCommon.Either<number, DeserializationError>(jsonable, null);
}

/**
 * Parse `jsonable` as a string.
 *
 * @param jsonable - to be parsed
 * @returns parsed string value, or an error
 */
function stringFromJsonable(
  jsonable: JsonValue
): AasCommon.Either<string, DeserializationError> {
  if (jsonable === null) {
    return newDeserializationError<string>(
      "Expected a string, but got null"
    );
  }
  if (typeof jsonable !== "string") {
    return newDeserializationError<string>(
      `Expected a string, but got: ${typeof jsonable}`
    );
  }

  return new AasCommon.Either<string, DeserializationError>(jsonable, null);
}

/**
 * Parse `jsonable` as a byte array.
 *
 * @param jsonable - to be parsed
 * @returns parsed byte array, or an error
 */
function bytesFromJsonable(
  jsonable: JsonValue
): AasCommon.Either<Uint8Array, DeserializationError> {
  if (jsonable === null) {
    return newDeserializationError<Uint8Array>(
      "Expected a base64-encoded string, but got null"
    );
  }
  if (typeof jsonable !== "string") {
    return newDeserializationError<Uint8Array>(
      `Expected a base64-encoded string, but got: ${typeof jsonable}`
    );
  }

  const either = AasCommon.base64Decode(jsonable);
  if (either.error !== null) {
    return newDeserializationError<Uint8Array>(either.error);
  }
  return new AasCommon.Either<Uint8Array, DeserializationError>(
    either.mustValue(), null
  );
}

/**
 * Parse `iterable` into a tuple of 2 item(s) by calling `parseItem0`,
 * `parseItem1`, *etc.* on the correspondingly positioned item.
 *
 * @param iterable - expected to contain exactly 2 item(s)
 * @param parseItem0 - to parse the item at index 0 of `iterable`
 * @param parseItem1 - to parse the item at index 1 of `iterable`
 * @returns parsed tuple, or an error
 * @typeParam T0 - type of the item at index 0
 * @typeParam T1 - type of the item at index 1
 */
function parseTuple2<T0, T1>(
  iterable: Iterable<JsonValue>,
  parseItem0: (
    jsonableItem: JsonValue
  ) => AasCommon.Either<T0, DeserializationError>,
  parseItem1: (
    jsonableItem: JsonValue
  ) => AasCommon.Either<T1, DeserializationError>
): AasCommon.Either<[T0, T1], DeserializationError> {
  if (Array.isArray(iterable) && iterable.length !== 2) {
    return newDeserializationError<[T0, T1]>(
      `Expected exactly 2 item(s) in the array, ` +
        `but got: ${iterable.length}`
    );
  }

  const iterator = iterable[Symbol.iterator]();

  const next0 = iterator.next();
  if (next0.done) {
    return newDeserializationError<[T0, T1]>(
      `Expected exactly 2 item(s) in the array, ` +
        `but got only 0 item(s)`
    );
  }
  const item0OrError = parseItem0(next0.value);
  if (item0OrError.error !== null) {
    item0OrError.error.path.prepend(new IndexSegment(iterable, 0));
    return new AasCommon.Either<[T0, T1], DeserializationError>(
      null,
      item0OrError.error
    );
  }

  const next1 = iterator.next();
  if (next1.done) {
    return newDeserializationError<[T0, T1]>(
      `Expected exactly 2 item(s) in the array, ` +
        `but got only 1 item(s)`
    );
  }
  const item1OrError = parseItem1(next1.value);
  if (item1OrError.error !== null) {
    item1OrError.error.path.prepend(new IndexSegment(iterable, 1));
    return new AasCommon.Either<[T0, T1], DeserializationError>(
      null,
      item1OrError.error
    );
  }

  const nextExtra = iterator.next();
  if (!nextExtra.done) {
    return newDeserializationError<[T0, T1]>(
      `Expected exactly 2 item(s) in the array, but got more`
    );
  }

  return new AasCommon.Either<[T0, T1], DeserializationError>(
    [
      item0OrError.mustValue(),
      item1OrError.mustValue()
    ],
    null
  );
}

/**
 * Parse `iterable` into a tuple of 6 item(s) by calling `parseItem0`,
 * `parseItem1`, *etc.* on the correspondingly positioned item.
 *
 * @param iterable - expected to contain exactly 6 item(s)
 * @param parseItem0 - to parse the item at index 0 of `iterable`
 * @param parseItem1 - to parse the item at index 1 of `iterable`
 * @param parseItem2 - to parse the item at index 2 of `iterable`
 * @param parseItem3 - to parse the item at index 3 of `iterable`
 * @param parseItem4 - to parse the item at index 4 of `iterable`
 * @param parseItem5 - to parse the item at index 5 of `iterable`
 * @returns parsed tuple, or an error
 * @typeParam T0 - type of the item at index 0
 * @typeParam T1 - type of the item at index 1
 * @typeParam T2 - type of the item at index 2
 * @typeParam T3 - type of the item at index 3
 * @typeParam T4 - type of the item at index 4
 * @typeParam T5 - type of the item at index 5
 */
function parseTuple6<T0, T1, T2, T3, T4, T5>(
  iterable: Iterable<JsonValue>,
  parseItem0: (
    jsonableItem: JsonValue
  ) => AasCommon.Either<T0, DeserializationError>,
  parseItem1: (
    jsonableItem: JsonValue
  ) => AasCommon.Either<T1, DeserializationError>,
  parseItem2: (
    jsonableItem: JsonValue
  ) => AasCommon.Either<T2, DeserializationError>,
  parseItem3: (
    jsonableItem: JsonValue
  ) => AasCommon.Either<T3, DeserializationError>,
  parseItem4: (
    jsonableItem: JsonValue
  ) => AasCommon.Either<T4, DeserializationError>,
  parseItem5: (
    jsonableItem: JsonValue
  ) => AasCommon.Either<T5, DeserializationError>
): AasCommon.Either<[T0, T1, T2, T3, T4, T5], DeserializationError> {
  if (Array.isArray(iterable) && iterable.length !== 6) {
    return newDeserializationError<[T0, T1, T2, T3, T4, T5]>(
      `Expected exactly 6 item(s) in the array, ` +
        `but got: ${iterable.length}`
    );
  }

  const iterator = iterable[Symbol.iterator]();

  const next0 = iterator.next();
  if (next0.done) {
    return newDeserializationError<[T0, T1, T2, T3, T4, T5]>(
      `Expected exactly 6 item(s) in the array, ` +
        `but got only 0 item(s)`
    );
  }
  const item0OrError = parseItem0(next0.value);
  if (item0OrError.error !== null) {
    item0OrError.error.path.prepend(new IndexSegment(iterable, 0));
    return new AasCommon.Either<[T0, T1, T2, T3, T4, T5], DeserializationError>(
      null,
      item0OrError.error
    );
  }

  const next1 = iterator.next();
  if (next1.done) {
    return newDeserializationError<[T0, T1, T2, T3, T4, T5]>(
      `Expected exactly 6 item(s) in the array, ` +
        `but got only 1 item(s)`
    );
  }
  const item1OrError = parseItem1(next1.value);
  if (item1OrError.error !== null) {
    item1OrError.error.path.prepend(new IndexSegment(iterable, 1));
    return new AasCommon.Either<[T0, T1, T2, T3, T4, T5], DeserializationError>(
      null,
      item1OrError.error
    );
  }

  const next2 = iterator.next();
  if (next2.done) {
    return newDeserializationError<[T0, T1, T2, T3, T4, T5]>(
      `Expected exactly 6 item(s) in the array, ` +
        `but got only 2 item(s)`
    );
  }
  const item2OrError = parseItem2(next2.value);
  if (item2OrError.error !== null) {
    item2OrError.error.path.prepend(new IndexSegment(iterable, 2));
    return new AasCommon.Either<[T0, T1, T2, T3, T4, T5], DeserializationError>(
      null,
      item2OrError.error
    );
  }

  const next3 = iterator.next();
  if (next3.done) {
    return newDeserializationError<[T0, T1, T2, T3, T4, T5]>(
      `Expected exactly 6 item(s) in the array, ` +
        `but got only 3 item(s)`
    );
  }
  const item3OrError = parseItem3(next3.value);
  if (item3OrError.error !== null) {
    item3OrError.error.path.prepend(new IndexSegment(iterable, 3));
    return new AasCommon.Either<[T0, T1, T2, T3, T4, T5], DeserializationError>(
      null,
      item3OrError.error
    );
  }

  const next4 = iterator.next();
  if (next4.done) {
    return newDeserializationError<[T0, T1, T2, T3, T4, T5]>(
      `Expected exactly 6 item(s) in the array, ` +
        `but got only 4 item(s)`
    );
  }
  const item4OrError = parseItem4(next4.value);
  if (item4OrError.error !== null) {
    item4OrError.error.path.prepend(new IndexSegment(iterable, 4));
    return new AasCommon.Either<[T0, T1, T2, T3, T4, T5], DeserializationError>(
      null,
      item4OrError.error
    );
  }

  const next5 = iterator.next();
  if (next5.done) {
    return newDeserializationError<[T0, T1, T2, T3, T4, T5]>(
      `Expected exactly 6 item(s) in the array, ` +
        `but got only 5 item(s)`
    );
  }
  const item5OrError = parseItem5(next5.value);
  if (item5OrError.error !== null) {
    item5OrError.error.path.prepend(new IndexSegment(iterable, 5));
    return new AasCommon.Either<[T0, T1, T2, T3, T4, T5], DeserializationError>(
      null,
      item5OrError.error
    );
  }

  const nextExtra = iterator.next();
  if (!nextExtra.done) {
    return newDeserializationError<[T0, T1, T2, T3, T4, T5]>(
      `Expected exactly 6 item(s) in the array, but got more`
    );
  }

  return new AasCommon.Either<[T0, T1, T2, T3, T4, T5], DeserializationError>(
    [
      item0OrError.mustValue(),
      item1OrError.mustValue(),
      item2OrError.mustValue(),
      item3OrError.mustValue(),
      item4OrError.mustValue(),
      item5OrError.mustValue()
    ],
    null
  );
}

/**
 * Parse `jsonable` structure as a literal
 * of {@link types!Result}.
 *
 * @param jsonable - to be parsed
 * @returns parsed literal, or an error if `jsonable` invalid
 */
export function resultFromJsonable(
  jsonable: JsonValue
): AasCommon.Either<AasTypes.Result, DeserializationError> {
  if (typeof jsonable !== "string") {
    return newDeserializationError<AasTypes.Result>(
      `Expected a string, but got: ${typeof jsonable}`
    );
  }

  const literal = AasStringification.resultFromString(jsonable);
  if (literal === null) {
    return newDeserializationError<AasTypes.Result>(
      "Not a valid string representation of " +
        `a literal of Result: ${jsonable}`
    );
  }

  return new AasCommon.Either<
    AasTypes.Result,
    DeserializationError
  >(literal, null);
}

/**
 * Parse `jsonable` as an instance
 * of {@link types!IAbstractItem}.
 *
 * @param jsonable - to be parsed
 * @returns parsed instance, or error if `jsonable` is invalid
 */
export function abstractItemFromJsonable(
  jsonable: JsonValue
): AasCommon.Either<
  AasTypes.IAbstractItem,
  DeserializationError
> {
  const objectError = checkIsJsonObject(jsonable);
  if (objectError !== null) {
    return new AasCommon.Either<
      AasTypes.IAbstractItem,
      DeserializationError
    >(
      null,
      objectError
    );
  }
  const jsonObject = <JsonObject>jsonable;

  const modelType = jsonObject["modelType"];
  if (modelType === undefined) {
    return newDeserializationError<AasTypes.IAbstractItem>(
      "The required property modelType is missing"
    );
  }

  if (typeof modelType !== "string") {
    return newDeserializationError<AasTypes.IAbstractItem>(
      `Expected the property modelType to be a string, but got: ${typeof modelType}`
    );
  }

  const dispatch = ABSTRACT_ITEM_FROM_JSONABLE_DISPATCH.get(modelType);
  if (dispatch === undefined) {
    return newDeserializationError<AasTypes.IAbstractItem>(
      `Unexpected model type for IAbstractItem: ${modelType}`
    );
  }

  return dispatch(jsonable);
}

/**
 * Provide de-serialize & set methods for properties
 * of {@link types!SomeItem}.
 */
class SetterForSomeItem {
  name: string | null = null;

  // Used only for verification, not for dispatch!
  modelType: string | null = null;

  /**
   * Parse `jsonable` as the value of {@link name}.
   *
   * @param jsonable - to be parsed
   * @returns error, if any
   */
  setNameFromJsonable(
    jsonable: JsonValue
  ): DeserializationError | null {
    const parsedOrError = stringFromJsonable(
      jsonable
    );
    if (parsedOrError.error !== null) {
      return parsedOrError.error;
    } else {
      this.name = parsedOrError.mustValue();
      return null;
    }
  }

  /**
   * Parse `jsonable` as the model type of the concrete instance.
   *
   * This is intended only for verification, and no dispatch is performed.
   *
   * @param jsonable - to be parsed
   * @returns error, if any
   */
  setModelTypeFromJsonable(
    jsonable: JsonValue
  ): DeserializationError | null {
    const parsedOrError = stringFromJsonable(
      jsonable
    );
    if (parsedOrError.error !== null) {
      return parsedOrError.error;
    } else {
      this.modelType = parsedOrError.mustValue();
      return null;
    }
  }
}

/**
 * Parse an instance of {@link types!SomeItem} from the JSON-able
 * structure `jsonable`.
 *
 * @param jsonable - structure to be parsed
 * @returns parsed instance of {@link types!SomeItem},
 * or an error if any
 */
export function someItemFromJsonable(
  jsonable: JsonValue
): AasCommon.Either<
  AasTypes.SomeItem,
  DeserializationError
> {
  const objectError = checkIsJsonObject(jsonable);
  if (objectError !== null) {
    return new AasCommon.Either<
      AasTypes.SomeItem,
      DeserializationError
    >(
      null,
      objectError
    );
  }
  const jsonObject = <JsonObject>jsonable;

  const setter = new SetterForSomeItem();

  for (const key in jsonObject) {
    const jsonableValue = jsonObject[key];
    const setterMethod =
      SETTER_MAP_FOR_SOME_ITEM.get(key);

    // NOTE (mristin, 2022-11-30):
    // Since we conflate here a JavaScript object with a JSON object, we ignore
    // properties which we do not know how to de-serialize and assume they are
    // related to the *JavaScript* properties of the object or `Object` prototype.
    if (setterMethod === undefined) {
      continue;
    }

    const error = setterMethod.call(setter, jsonableValue);
    if (error !== null) {
      error.path.prepend(
        new PropertySegment(jsonObject, key)
      );
      return new AasCommon.Either<
        AasTypes.SomeItem,
        DeserializationError
      >(
          null,
          error
        );
    }
  }

  if (setter.name === null) {
    return newDeserializationError<
      AasTypes.SomeItem
    >(
      "The required property 'name' is missing"
    );
  }

  const modelTypeError = checkModelType(setter.modelType, "SomeItem");
  if (modelTypeError !== null) {
    return new AasCommon.Either<
      AasTypes.SomeItem,
      DeserializationError
    >(
      null,
      modelTypeError
    );
  }

  return new AasCommon.Either<
    AasTypes.SomeItem,
    DeserializationError
  >(
    new AasTypes.SomeItem(
      setter.name
    ),
    null
  );
}

/**
 * Provide de-serialize & set methods for properties
 * of {@link types!AnotherItem}.
 */
class SetterForAnotherItem {
  serialNumber: number | null = null;

  // Used only for verification, not for dispatch!
  modelType: string | null = null;

  /**
   * Parse `jsonable` as the value of {@link serialNumber}.
   *
   * @param jsonable - to be parsed
   * @returns error, if any
   */
  setSerialNumberFromJsonable(
    jsonable: JsonValue
  ): DeserializationError | null {
    const parsedOrError = integerFromJsonable(
      jsonable
    );
    if (parsedOrError.error !== null) {
      return parsedOrError.error;
    } else {
      this.serialNumber = parsedOrError.mustValue();
      return null;
    }
  }

  /**
   * Parse `jsonable` as the model type of the concrete instance.
   *
   * This is intended only for verification, and no dispatch is performed.
   *
   * @param jsonable - to be parsed
   * @returns error, if any
   */
  setModelTypeFromJsonable(
    jsonable: JsonValue
  ): DeserializationError | null {
    const parsedOrError = stringFromJsonable(
      jsonable
    );
    if (parsedOrError.error !== null) {
      return parsedOrError.error;
    } else {
      this.modelType = parsedOrError.mustValue();
      return null;
    }
  }
}

/**
 * Parse an instance of {@link types!AnotherItem} from the JSON-able
 * structure `jsonable`.
 *
 * @param jsonable - structure to be parsed
 * @returns parsed instance of {@link types!AnotherItem},
 * or an error if any
 */
export function anotherItemFromJsonable(
  jsonable: JsonValue
): AasCommon.Either<
  AasTypes.AnotherItem,
  DeserializationError
> {
  const objectError = checkIsJsonObject(jsonable);
  if (objectError !== null) {
    return new AasCommon.Either<
      AasTypes.AnotherItem,
      DeserializationError
    >(
      null,
      objectError
    );
  }
  const jsonObject = <JsonObject>jsonable;

  const setter = new SetterForAnotherItem();

  for (const key in jsonObject) {
    const jsonableValue = jsonObject[key];
    const setterMethod =
      SETTER_MAP_FOR_ANOTHER_ITEM.get(key);

    // NOTE (mristin, 2022-11-30):
    // Since we conflate here a JavaScript object with a JSON object, we ignore
    // properties which we do not know how to de-serialize and assume they are
    // related to the *JavaScript* properties of the object or `Object` prototype.
    if (setterMethod === undefined) {
      continue;
    }

    const error = setterMethod.call(setter, jsonableValue);
    if (error !== null) {
      error.path.prepend(
        new PropertySegment(jsonObject, key)
      );
      return new AasCommon.Either<
        AasTypes.AnotherItem,
        DeserializationError
      >(
          null,
          error
        );
    }
  }

  if (setter.serialNumber === null) {
    return newDeserializationError<
      AasTypes.AnotherItem
    >(
      "The required property 'serialNumber' is missing"
    );
  }

  const modelTypeError = checkModelType(setter.modelType, "AnotherItem");
  if (modelTypeError !== null) {
    return new AasCommon.Either<
      AasTypes.AnotherItem,
      DeserializationError
    >(
      null,
      modelTypeError
    );
  }

  return new AasCommon.Either<
    AasTypes.AnotherItem,
    DeserializationError
  >(
    new AasTypes.AnotherItem(
      setter.serialNumber
    ),
    null
  );
}

/**
 * Provide de-serialize & set methods for properties
 * of {@link types!Something}.
 */
class SetterForSomething {
  pair: [string, number] | null = null;

  items: [AasTypes.IAbstractItem, AasTypes.IAbstractItem] | null = null;

  tricky: [number, AasTypes.SomeItem, AasTypes.IAbstractItem, AasTypes.SomeItem, number, AasTypes.Result] | null = null;

  /**
   * Parse `jsonable` as the value of {@link pair}.
   *
   * @param jsonable - to be parsed
   * @returns error, if any
   */
  setPairFromJsonable(
    jsonable: JsonValue
  ): DeserializationError | null {
    const iterableError = checkIsIterable(jsonable);
    if (iterableError !== null) {
      return iterableError;
    }

    const iterable = <Iterable<JsonValue>>jsonable;

    const tupleOrError = parseTuple2<string, number>(
      iterable,
      stringFromJsonable,
      integerFromJsonable
    );
    if (tupleOrError.error !== null) {
      return tupleOrError.error;
    }

    this.pair = tupleOrError.mustValue();
    return null;
  }

  /**
   * Parse `jsonable` as the value of {@link items}.
   *
   * @param jsonable - to be parsed
   * @returns error, if any
   */
  setItemsFromJsonable(
    jsonable: JsonValue
  ): DeserializationError | null {
    const iterableError = checkIsIterable(jsonable);
    if (iterableError !== null) {
      return iterableError;
    }

    const iterable = <Iterable<JsonValue>>jsonable;

    const tupleOrError = parseTuple2<AasTypes.IAbstractItem, AasTypes.IAbstractItem>(
      iterable,
      abstractItemFromJsonable,
      abstractItemFromJsonable
    );
    if (tupleOrError.error !== null) {
      return tupleOrError.error;
    }

    this.items = tupleOrError.mustValue();
    return null;
  }

  /**
   * Parse `jsonable` as the value of {@link tricky}.
   *
   * @param jsonable - to be parsed
   * @returns error, if any
   */
  setTrickyFromJsonable(
    jsonable: JsonValue
  ): DeserializationError | null {
    const iterableError = checkIsIterable(jsonable);
    if (iterableError !== null) {
      return iterableError;
    }

    const iterable = <Iterable<JsonValue>>jsonable;

    const tupleOrError = parseTuple6<number, AasTypes.SomeItem, AasTypes.IAbstractItem, AasTypes.SomeItem, number, AasTypes.Result>(
      iterable,
      integerFromJsonable,
      someItemFromJsonable,
      abstractItemFromJsonable,
      someItemFromJsonable,
      integerFromJsonable,
      resultFromJsonable
    );
    if (tupleOrError.error !== null) {
      return tupleOrError.error;
    }

    this.tricky = tupleOrError.mustValue();
    return null;
  }
}

/**
 * Parse an instance of {@link types!Something} from the JSON-able
 * structure `jsonable`.
 *
 * @param jsonable - structure to be parsed
 * @returns parsed instance of {@link types!Something},
 * or an error if any
 */
export function somethingFromJsonable(
  jsonable: JsonValue
): AasCommon.Either<
  AasTypes.Something,
  DeserializationError
> {
  const objectError = checkIsJsonObject(jsonable);
  if (objectError !== null) {
    return new AasCommon.Either<
      AasTypes.Something,
      DeserializationError
    >(
      null,
      objectError
    );
  }
  const jsonObject = <JsonObject>jsonable;

  const setter = new SetterForSomething();

  for (const key in jsonObject) {
    const jsonableValue = jsonObject[key];
    const setterMethod =
      SETTER_MAP_FOR_SOMETHING.get(key);

    // NOTE (mristin, 2022-11-30):
    // Since we conflate here a JavaScript object with a JSON object, we ignore
    // properties which we do not know how to de-serialize and assume they are
    // related to the *JavaScript* properties of the object or `Object` prototype.
    if (setterMethod === undefined) {
      continue;
    }

    const error = setterMethod.call(setter, jsonableValue);
    if (error !== null) {
      error.path.prepend(
        new PropertySegment(jsonObject, key)
      );
      return new AasCommon.Either<
        AasTypes.Something,
        DeserializationError
      >(
          null,
          error
        );
    }
  }

  if (setter.pair === null) {
    return newDeserializationError<
      AasTypes.Something
    >(
      "The required property 'pair' is missing"
    );
  }

  if (setter.items === null) {
    return newDeserializationError<
      AasTypes.Something
    >(
      "The required property 'items' is missing"
    );
  }

  if (setter.tricky === null) {
    return newDeserializationError<
      AasTypes.Something
    >(
      "The required property 'tricky' is missing"
    );
  }

  return new AasCommon.Either<
    AasTypes.Something,
    DeserializationError
  >(
    new AasTypes.Something(
      setter.pair,
      setter.items,
      setter.tricky
    ),
    null
  );
}

const ABSTRACT_ITEM_FROM_JSONABLE_DISPATCH =
  new Map<
    string,
    (JsonValue) => AasCommon.Either<
      AasTypes.IAbstractItem,
      DeserializationError
    >
  >(
    [
      [
        "AnotherItem",
        anotherItemFromJsonable
      ],
      [
        "SomeItem",
        someItemFromJsonable
      ]
    ]
  );

const SETTER_MAP_FOR_SOME_ITEM =
  new Map<
    string,
    (
      jsonable: JsonValue
    ) => DeserializationError | null
  >(
    [
      [
        "name",
        SetterForSomeItem.prototype.setNameFromJsonable
      ],
      [
        // The model type here is used only for verification, not for dispatch.
        "modelType",
        SetterForSomeItem.prototype.setModelTypeFromJsonable
      ],
    ]
  );

const SETTER_MAP_FOR_ANOTHER_ITEM =
  new Map<
    string,
    (
      jsonable: JsonValue
    ) => DeserializationError | null
  >(
    [
      [
        "serialNumber",
        SetterForAnotherItem.prototype.setSerialNumberFromJsonable
      ],
      [
        // The model type here is used only for verification, not for dispatch.
        "modelType",
        SetterForAnotherItem.prototype.setModelTypeFromJsonable
      ],
    ]
  );

const SETTER_MAP_FOR_SOMETHING =
  new Map<
    string,
    (
      jsonable: JsonValue
    ) => DeserializationError | null
  >(
    [
      [
        "pair",
        SetterForSomething.prototype.setPairFromJsonable
      ],
      [
        "items",
        SetterForSomething.prototype.setItemsFromJsonable
      ],
      [
        "tricky",
        SetterForSomething.prototype.setTrickyFromJsonable
      ],
    ]
  );

// endregion

// region Serialization

/**
 * Serialize every item of `items` with `serializeItem` into a JSON-able
 * array.
 *
 * @param items - to be serialized
 * @param serializeItem - to serialize a single item of `items`
 * @returns JSON-able array
 * @typeParam T - type of a single item to be serialized
 * @typeParam J - type of a single item once serialized
 */
function serializeArray<T, J extends JsonValue>(
  items: Iterable<T>,
  serializeItem: (item: T) => J
): Array<J> {
  const result = new Array<J>();
  for (const item of items) {
    result.push(serializeItem(item));
  }
  return result;
}

/**
 * Transform the instance to its JSON-able representation.
 */
class Serializer extends AasTypes.AbstractTransformer<JsonObject> {


  /**
   * Serialize `that` to a JSON-able representation.
   *
   * @param that - instance to be serialization
   * @returns JSON-able representation
   */
  transformSomeItem(
    that: AasTypes.SomeItem
  ): JsonObject {
    const jsonable: JsonObject = {};

    jsonable["name"] =
      that.name;

    jsonable["modelType"] = "SomeItem";

    return jsonable;
  }

  /**
   * Serialize `that` to a JSON-able representation.
   *
   * @param that - instance to be serialization
   * @returns JSON-able representation
   */
  transformAnotherItem(
    that: AasTypes.AnotherItem
  ): JsonObject {
    const jsonable: JsonObject = {};

    jsonable["serialNumber"] =
      that.serialNumber;

    jsonable["modelType"] = "AnotherItem";

    return jsonable;
  }

  /**
   * Serialize `that` to a JSON-able representation.
   *
   * @param that - instance to be serialization
   * @returns JSON-able representation
   */
  transformSomething(
    that: AasTypes.Something
  ): JsonObject {
    const jsonable: JsonObject = {};

    jsonable["pair"] = [
      that.pair[0],
      that.pair[1]
    ];

    jsonable["items"] = [
      this.transform(that.items[0]),
      this.transform(that.items[1])
    ];

    jsonable["tricky"] = [
      that.tricky[0],
      this.transform(that.tricky[1]),
      this.transform(that.tricky[2]),
      this.transform(that.tricky[3]),
      that.tricky[4],
      AasStringification.mustResultToString(
        that.tricky[5]
      )
    ];

    return jsonable;
  }
}

const SERIALIZER = new Serializer();

/**
 * Convert `that` to a JSON-able structure.
 *
 * @param that - AAS data to be recursively converted to a JSON-able structure
 * @returns
 * JSON-able structure which can be further processed with, say,
 * {@link https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify|JSON.stringify})
 */
export function toJsonable(that: AasTypes.Class): JsonObject {
  return SERIALIZER.transform(that);
}

// endregion

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.
