/*
 * This code has been automatically generated by aas-core-codegen.
 * Do NOT edit or append.
 */

using Aas = dummy;  // renamed
using CodeAnalysis = System.Diagnostics.CodeAnalysis;
using Nodes = System.Text.Json.Nodes;

using System.Collections.Generic;  // can't alias

namespace dummy
{
    /// <summary>
    /// Provide de/serialization of meta-model classes to/from JSON.
    /// </summary>
    /// <remarks>
    /// We can not use one-pass deserialization for JSON since the object
    /// properties do not have fixed order, and hence we can not read
    /// <c>modelType</c> property ahead of the remaining properties.
    /// </remarks>
    public static class Jsonization
    {
        /// <summary>
        /// Implement the deserialization of meta-model classes from JSON nodes.
        /// </summary>
        /// <remarks>
        /// The implementation propagates an <see cref="Reporting.Error" /> instead of relying
        /// on exceptions. Under the assumption that incorrect data is much less
        /// frequent than correct data, this makes the deserialization more
        /// efficient.
        ///
        /// However, we do not want to force the client to deal with
        /// the <see cref="Reporting.Error" /> class as this is not intuitive. Therefore
        /// we distinguish the implementation, realized in
        /// <see cref="DeserializeImplementation" />, and the facade given in
        /// <see cref="Deserialize" /> class.
        /// </remarks>
        internal static class DeserializeImplementation
        {
            /// <summary>Convert <paramref name="node" /> to a boolean.</summary>
            /// <param name="node">JSON node to be parsed</param>
            /// <param name="error">Error, if any, during the deserialization</param>
            internal static bool? BoolFrom(
                Nodes.JsonNode node,
                out Reporting.Error? error)
            {
                error = null;
                Nodes.JsonValue? value = node as Nodes.JsonValue;
                if (value == null)
                {
                    error = new Reporting.Error(
                        $"Expected a JsonValue, but got {node.GetType()}");
                    return null;
                }
                bool ok = value.TryGetValue<bool>(out bool result);
                if (!ok)
                {
                    error = new Reporting.Error(
                        "Expected a boolean, but the conversion failed " +
                        $"from {value.ToJsonString()}");
                    return null;
                }
                return result;
            }

            /// <summary>
            /// Convert the <paramref name="node" /> to a long 64-bit integer.
            /// </summary>
            /// <param name="node">JSON node to be parsed</param>
            /// <param name="error">Error, if any, during the deserialization</param>
            internal static long? LongFrom(
                Nodes.JsonNode node,
                out Reporting.Error? error)
            {
                error = null;
                Nodes.JsonValue? value = node as Nodes.JsonValue;
                if (value == null)
                {
                    error = new Reporting.Error(
                        $"Expected a JsonValue, but got {node.GetType()}");
                    return null;
                }
                bool ok = value.TryGetValue<long>(out long result);
                if (!ok)
                {
                    error = new Reporting.Error(
                        "Expected a 64-bit long integer, but the conversion failed " +
                        $"from {value.ToJsonString()}");
                    return null;
                }
                return result;
            }

            /// <summary>
            /// Convert the <paramref name="node" /> to a double-precision 64-bit float.
            /// </summary>
            /// <param name="node">JSON node to be parsed</param>
            /// <param name="error">Error, if any, during the deserialization</param>
            internal static double? DoubleFrom(
                Nodes.JsonNode node,
                out Reporting.Error? error)
            {
                error = null;
                Nodes.JsonValue? value = node as Nodes.JsonValue;
                if (value == null)
                {
                    error = new Reporting.Error(
                        $"Expected a JsonValue, but got {node.GetType()}");
                    return null;
                }
                bool ok = value.TryGetValue<double>(out double result);
                if (!ok)
                {
                    error = new Reporting.Error(
                        "Expected a 64-bit double-precision float, " +
                        "but the conversion failed " +
                        $"from {value.ToJsonString()}");
                    return null;
                }
                return result;
            }

            /// <summary>
            /// Convert the <paramref name="node" /> to a string.
            /// </summary>
            /// <param name="node">JSON node to be parsed</param>
            /// <param name="error">Error, if any, during the deserialization</param>
            internal static string? StringFrom(
                Nodes.JsonNode node,
                out Reporting.Error? error)
            {
                error = null;
                Nodes.JsonValue? value = node as Nodes.JsonValue;
                if (value == null)
                {
                    error = new Reporting.Error(
                        $"Expected a JsonValue, but got {node.GetType()}");
                    return null;
                }
                bool ok = value.TryGetValue<string>(out string? result);
                if (!ok)
                {
                    error = new Reporting.Error(
                        "Expected a string, but the conversion failed " +
                        $"from {value.ToJsonString()}");
                    return null;
                }
                if (result == null)
                {
                    error = new Reporting.Error(
                        "Expected a string, but got a null");
                    return null;
                }
                return result;
            }

            /// <summary>
            /// Convert the <paramref name="node" /> to bytes.
            /// </summary>
            /// <param name="node">JSON node to be parsed</param>
            /// <param name="error">Error, if any, during the deserialization</param>
            internal static byte[]? BytesFrom(
                Nodes.JsonNode node,
                out Reporting.Error? error)
            {
                error = null;
                Nodes.JsonValue? value = node as Nodes.JsonValue;
                if (value == null)
                {
                    error = new Reporting.Error(
                        $"Expected a JsonValue, but got {node.GetType()}");
                    return null;
                }
                bool ok = value.TryGetValue<string>(out string? text);
                if (!ok)
                {
                    error = new Reporting.Error(
                        "Expected a string, but the conversion failed " +
                        $"from {value.ToJsonString()}");
                    return null;
                }
                if (text == null)
                {
                    error = new Reporting.Error(
                        "Expected a string, but got a null");
                    return null;
                }
                try
                {
                    return System.Convert.FromBase64String(text);
                }
                catch (System.FormatException exception)
                {
                    error = new Reporting.Error(
                        "Expected Base-64 encoded bytes, but the conversion failed " +
                        $"because: {exception}");
                    return null;
                }
            }

            /// <summary>
            /// Read a single array item.
            /// </summary>
            /// <typeparam name="T">Type of the parsed item</typeparam>
            private delegate T? JsonClassItemDeserializer<T>(
                Nodes.JsonNode node,
                out Reporting.Error? error
                ) where T : class;

            /// <summary>
            /// Parse every item of <paramref name="array" /> with
            /// <paramref name="deserializeItem" />.
            /// </summary>
            /// <remarks>
            /// This is shared by all the list-typed constructor arguments whose items are
            /// de-serialized into a reference type (<em>e.g.</em>, a string, a byte array
            /// or a class instance).
            /// </remarks>
            /// <typeparam name="T">Type of a single array item</typeparam>
            private static List<T> ParseArrayOfClass<T>(
                Nodes.JsonArray array,
                JsonClassItemDeserializer<T> deserializeItem,
                out Reporting.Error? error
                ) where T : class
            {
                error = null;
                List<T> result = new List<T>(array.Count);

                int index = 0;
                foreach (Nodes.JsonNode? item in array)
                {
                    if (item == null)
                    {
                        error = new Reporting.Error(
                            "Expected a non-null item, but got a null");
                        error.PrependSegment(
                            new Reporting.IndexSegment(
                                index));
                        return result;
                    }

                    T? parsedItem = deserializeItem(
                        item ?? throw new System.InvalidOperationException(),
                        out error);
                    if (error != null)
                    {
                        error.PrependSegment(
                            new Reporting.IndexSegment(
                                index));
                        return result;
                    }

                    result.Add(
                        parsedItem
                            ?? throw new System.InvalidOperationException(
                                "Unexpected result null when error is null"));

                    index++;
                }

                return result;
            }

            /// <summary>
            /// Read a single array item.
            /// </summary>
            /// <typeparam name="T">Type of the parsed item</typeparam>
            private delegate T? JsonStructItemDeserializer<T>(
                Nodes.JsonNode node,
                out Reporting.Error? error
                ) where T : struct;

            /// <summary>
            /// Parse every item of <paramref name="array" /> with
            /// <paramref name="deserializeItem" />.
            /// </summary>
            /// <remarks>
            /// This is shared by all the list-typed constructor arguments whose items are
            /// de-serialized into a value type (<em>e.g.</em>, a bool, a number or
            /// an enumeration literal).
            /// </remarks>
            /// <typeparam name="T">Type of a single array item</typeparam>
            private static List<T> ParseArrayOfStruct<T>(
                Nodes.JsonArray array,
                JsonStructItemDeserializer<T> deserializeItem,
                out Reporting.Error? error
                ) where T : struct
            {
                error = null;
                List<T> result = new List<T>(array.Count);

                int index = 0;
                foreach (Nodes.JsonNode? item in array)
                {
                    if (item == null)
                    {
                        error = new Reporting.Error(
                            "Expected a non-null item, but got a null");
                        error.PrependSegment(
                            new Reporting.IndexSegment(
                                index));
                        return result;
                    }

                    T? parsedItem = deserializeItem(
                        item ?? throw new System.InvalidOperationException(),
                        out error);
                    if (error != null)
                    {
                        error.PrependSegment(
                            new Reporting.IndexSegment(
                                index));
                        return result;
                    }

                    result.Add(
                        parsedItem
                            ?? throw new System.InvalidOperationException(
                                "Unexpected result null when error is null"));

                    index++;
                }

                return result;
            }

            /// <summary>
            /// Parse a single tuple item.
            /// </summary>
            /// <remarks>
            /// A tuple-typed property is parsed by <c>ParseTupleN</c> (see
            /// <see cref="ParseTuple2{T0, T1}" /> for the arity-2 case, *etc.*), one
            /// function shared by *every* tuple-typed property of a given arity,
            /// regardless of which mix of reference and value types appears at each
            /// position. If <c>ParseTupleN</c> demanded the same
            /// <c>JsonClassItemDeserializer&lt;T&gt;</c>/<c>JsonStructItemDeserializer&lt;T&gt;</c>
            /// shape already used for list items (a nullable return, constrained to
            /// <c>class</c> or <c>struct</c>), its own type parameters would need that
            /// constraint fixed once per position -- which breaks the moment two
            /// different tuple-typed properties of the same arity mix reference and
            /// value types differently at the same position (<em>e.g.</em>,
            /// <c>(string, long)</c> at one property and <c>(long, string)</c> at
            /// another could not share one <c>ParseTuple2</c>).
            ///
            /// A single unconstrained <c>T? Method(Nodes.JsonNode node, out Reporting.Error? error)</c>
            /// shape shared by both reference and value types does not work around this
            /// either: for a value type, an unconstrained <c>T?</c> erases to plain
            /// <c>T</c> (not <c>System.Nullable&lt;T&gt;</c>), so a method returning
            /// <c>long?</c> can not even be assigned to it.
            ///
            /// <c>TupleItemDeserializer&lt;T&gt;</c> sidesteps the class/struct split
            /// entirely by using an <c>out</c> parameter for the value instead of a
            /// nullable return, at the cost of needing an adapter --
            /// <see cref="AsTupleItemDeserializer{T}(JsonClassItemDeserializer{T})" /> --
            /// to convert an existing item parser (such as a bare <c>StringFrom</c> or
            /// <c>LongFrom</c> method group) into one.
            /// </remarks>
            /// <typeparam name="T">Type of the parsed item</typeparam>
            private delegate void TupleItemDeserializer<T>(
                Nodes.JsonNode node,
                out T value,
                out Reporting.Error? error);

            /// <summary>
            /// Adapt <paramref name="deserializeItem" /> -- a reference-type item parser
            /// as used for list-typed properties -- into a <see cref="TupleItemDeserializer{T}" />
            /// for use in a tuple-typed property.
            /// </summary>
            /// <remarks>
            /// See the remarks on <see cref="TupleItemDeserializer{T}" /> for why this
            /// adapter -- rather than a shared constraint on <c>ParseTupleN</c> itself --
            /// is necessary. This overload and its <c>JsonStructItemDeserializer&lt;T&gt;</c>
            /// counterpart are dispatched on the parameter's delegate type alone, so a
            /// caller never has to pick between them by name; each encapsulates the
            /// "unwrap the nullable result, or propagate the error" check exactly once,
            /// mirroring how <see cref="ParseArrayOfClass{T}" />/
            /// <see cref="ParseArrayOfStruct{T}" /> encapsulate the very same check
            /// once for lists instead of repeating it at every call site.
            /// </remarks>
            /// <typeparam name="T">Type of the parsed item</typeparam>
            private static TupleItemDeserializer<T> AsTupleItemDeserializer<T>(
                JsonClassItemDeserializer<T> deserializeItem
                ) where T : class
            {
                return (
                    Nodes.JsonNode node,
                    out T value,
                    out Reporting.Error? error) =>
                    {
                        T? parsed = deserializeItem(node, out error);
                        if (error != null)
                        {
                            value = default!;
                            return;
                        }
                        value = parsed
                            ?? throw new System.InvalidOperationException(
                                "Unexpected result null when error is null");
                    };
            }

            /// <summary>
            /// Adapt <paramref name="deserializeItem" /> -- a value-type item parser
            /// as used for list-typed properties -- into a <see cref="TupleItemDeserializer{T}" />
            /// for use in a tuple-typed property.
            /// </summary>
            /// <remarks>
            /// See <see cref="AsTupleItemDeserializer{T}(JsonClassItemDeserializer{T})" />
            /// for why this adapter is necessary.
            /// </remarks>
            /// <typeparam name="T">Type of the parsed item</typeparam>
            private static TupleItemDeserializer<T> AsTupleItemDeserializer<T>(
                JsonStructItemDeserializer<T> deserializeItem
                ) where T : struct
            {
                return (
                    Nodes.JsonNode node,
                    out T value,
                    out Reporting.Error? error) =>
                    {
                        T? parsed = deserializeItem(node, out error);
                        if (error != null)
                        {
                            value = default;
                            return;
                        }
                        value = parsed
                            ?? throw new System.InvalidOperationException(
                                "Unexpected result null when error is null");
                    };
            }

            /// <summary>
            /// Parse every item of <paramref name="array" /> as a tuple of 2 item(s).
            /// </summary>
            /// <remarks>
            /// This is shared by all the tuple-typed properties of arity 2.
            /// </remarks>
            private static (T0, T1) ParseTuple2<T0, T1>(
                Nodes.JsonArray array,
                TupleItemDeserializer<T0> deserializeItem0,
                TupleItemDeserializer<T1> deserializeItem1,
                out Reporting.Error? error)
            {
                error = null;

                if (array.Count != 2)
                {
                    error = new Reporting.Error(
                        $"Expected exactly 2 item(s) in the JsonArray, " +
                        $"but got: {array.Count}");
                    return default!;
                }

                Nodes.JsonNode? node0 = array[0];
                if (node0 == null)
                {
                    error = new Reporting.Error(
                        "Expected a non-null item, but got a null");
                    error.PrependSegment(
                        new Reporting.IndexSegment(
                            0));
                    return default!;
                }
                deserializeItem0(node0, out T0 item0, out error);
                if (error != null)
                {
                    error.PrependSegment(
                        new Reporting.IndexSegment(
                            0));
                    return default!;
                }

                Nodes.JsonNode? node1 = array[1];
                if (node1 == null)
                {
                    error = new Reporting.Error(
                        "Expected a non-null item, but got a null");
                    error.PrependSegment(
                        new Reporting.IndexSegment(
                            1));
                    return default!;
                }
                deserializeItem1(node1, out T1 item1, out error);
                if (error != null)
                {
                    error.PrependSegment(
                        new Reporting.IndexSegment(
                            1));
                    return default!;
                }

                return (
                    item0,
                    item1
                );
            }

            /// <summary>
            /// Parse every item of <paramref name="array" /> as a tuple of 6 item(s).
            /// </summary>
            /// <remarks>
            /// This is shared by all the tuple-typed properties of arity 6.
            /// </remarks>
            private static (T0, T1, T2, T3, T4, T5) ParseTuple6<T0, T1, T2, T3, T4, T5>(
                Nodes.JsonArray array,
                TupleItemDeserializer<T0> deserializeItem0,
                TupleItemDeserializer<T1> deserializeItem1,
                TupleItemDeserializer<T2> deserializeItem2,
                TupleItemDeserializer<T3> deserializeItem3,
                TupleItemDeserializer<T4> deserializeItem4,
                TupleItemDeserializer<T5> deserializeItem5,
                out Reporting.Error? error)
            {
                error = null;

                if (array.Count != 6)
                {
                    error = new Reporting.Error(
                        $"Expected exactly 6 item(s) in the JsonArray, " +
                        $"but got: {array.Count}");
                    return default!;
                }

                Nodes.JsonNode? node0 = array[0];
                if (node0 == null)
                {
                    error = new Reporting.Error(
                        "Expected a non-null item, but got a null");
                    error.PrependSegment(
                        new Reporting.IndexSegment(
                            0));
                    return default!;
                }
                deserializeItem0(node0, out T0 item0, out error);
                if (error != null)
                {
                    error.PrependSegment(
                        new Reporting.IndexSegment(
                            0));
                    return default!;
                }

                Nodes.JsonNode? node1 = array[1];
                if (node1 == null)
                {
                    error = new Reporting.Error(
                        "Expected a non-null item, but got a null");
                    error.PrependSegment(
                        new Reporting.IndexSegment(
                            1));
                    return default!;
                }
                deserializeItem1(node1, out T1 item1, out error);
                if (error != null)
                {
                    error.PrependSegment(
                        new Reporting.IndexSegment(
                            1));
                    return default!;
                }

                Nodes.JsonNode? node2 = array[2];
                if (node2 == null)
                {
                    error = new Reporting.Error(
                        "Expected a non-null item, but got a null");
                    error.PrependSegment(
                        new Reporting.IndexSegment(
                            2));
                    return default!;
                }
                deserializeItem2(node2, out T2 item2, out error);
                if (error != null)
                {
                    error.PrependSegment(
                        new Reporting.IndexSegment(
                            2));
                    return default!;
                }

                Nodes.JsonNode? node3 = array[3];
                if (node3 == null)
                {
                    error = new Reporting.Error(
                        "Expected a non-null item, but got a null");
                    error.PrependSegment(
                        new Reporting.IndexSegment(
                            3));
                    return default!;
                }
                deserializeItem3(node3, out T3 item3, out error);
                if (error != null)
                {
                    error.PrependSegment(
                        new Reporting.IndexSegment(
                            3));
                    return default!;
                }

                Nodes.JsonNode? node4 = array[4];
                if (node4 == null)
                {
                    error = new Reporting.Error(
                        "Expected a non-null item, but got a null");
                    error.PrependSegment(
                        new Reporting.IndexSegment(
                            4));
                    return default!;
                }
                deserializeItem4(node4, out T4 item4, out error);
                if (error != null)
                {
                    error.PrependSegment(
                        new Reporting.IndexSegment(
                            4));
                    return default!;
                }

                Nodes.JsonNode? node5 = array[5];
                if (node5 == null)
                {
                    error = new Reporting.Error(
                        "Expected a non-null item, but got a null");
                    error.PrependSegment(
                        new Reporting.IndexSegment(
                            5));
                    return default!;
                }
                deserializeItem5(node5, out T5 item5, out error);
                if (error != null)
                {
                    error.PrependSegment(
                        new Reporting.IndexSegment(
                            5));
                    return default!;
                }

                return (
                    item0,
                    item1,
                    item2,
                    item3,
                    item4,
                    item5
                );
            }

            /// <summary>
            /// Deserialize the enumeration Result from the <paramref name="node" />.
            /// </summary>
            /// <param name="node">JSON node to be parsed</param>
            /// <param name="error">Error, if any, during the deserialization</param>
            internal static Aas.Result? ResultFrom(
                Nodes.JsonNode node,
                out Reporting.Error? error)
            {
                error = null;
                string? text = DeserializeImplementation.StringFrom(
                    node, out error);
                if (error != null)
                {
                    return null;
                }
                if (text == null)
                {
                    throw new System.InvalidOperationException(
                        "Unexpected text null if error null");
                }
                Aas.Result? result = Stringification.ResultFromString(text);
                if (result == null)
                {
                    error = new Reporting.Error(
                        "Not a valid JSON representation of Result");
                }
                return result;
            }  // internal static ResultFrom

            /// <summary>
            /// Deserialize an instance of IAbstractItem by dispatching
            /// based on <c>modelType</c> property of the <paramref name="node" />.
            /// </summary>
            /// <param name="node">JSON node to be parsed</param>
            /// <param name="error">Error, if any, during the deserialization</param>
            [CodeAnalysis.SuppressMessage("ReSharper", "InconsistentNaming")]
            public static Aas.IAbstractItem? IAbstractItemFrom(
                Nodes.JsonNode node,
                out Reporting.Error? error)
            {
                error = null;

                var obj = node as Nodes.JsonObject;
                if (obj == null)
                {
                    error = new Reporting.Error(
                        $"Expected Nodes.JsonObject, but got {node.GetType()}");
                    return null;
                }

                Nodes.JsonNode? modelTypeNode = obj["modelType"];
                if (modelTypeNode == null)
                {
                    error = new Reporting.Error(
                        "Expected a model type, but none is present");
                    return null;
                }
                Nodes.JsonValue? modelTypeValue = modelTypeNode as Nodes.JsonValue;
                if (modelTypeValue == null)
                {
                    error = new Reporting.Error(
                        "Expected JsonValue, " +
                        $"but got {modelTypeNode.GetType()}");
                    return null;
                }
                modelTypeValue.TryGetValue<string>(out string? modelType);
                if (modelType == null)
                {
                    error = new Reporting.Error(
                        "Expected a string, " +
                        $"but the conversion failed from {modelTypeValue}");
                    return null;
                }

                switch (modelType)
                {
                    case "AnotherItem":
                        return AnotherItemFrom(
                            node, out error);
                    case "SomeItem":
                        return SomeItemFrom(
                            node, out error);
                    default:
                        error = new Reporting.Error(
                            $"Unexpected model type for IAbstractItem: {modelType}");
                        return null;
                }
            }  // public static Aas.IAbstractItem IAbstractItemFrom

            /// <summary>
            /// Deserialize an instance of SomeItem from <paramref name="node" />.
            /// </summary>
            /// <param name="node">JSON node to be parsed</param>
            /// <param name="error">Error, if any, during the deserialization</param>
            internal static Aas.SomeItem? SomeItemFrom(
                Nodes.JsonNode node,
                out Reporting.Error? error)
            {
                error = null;

                Nodes.JsonObject? obj = node as Nodes.JsonObject;
                if (obj == null)
                {
                    error = new Reporting.Error(
                        $"Expected a JsonObject, but got {node.GetType()}");
                    return null;
                }

                string? theName = null;

                string? modelType = null;

                foreach (var keyValue in obj)
                {
                    switch (keyValue.Key)
                    {
                        case "name":
                        {
                            if (keyValue.Value == null)
                            {
                                error = new Reporting.Error(
                                    "Unexpected null for a required property");
                                error.PrependSegment(
                                    new Reporting.NameSegment(
                                        "name"));
                                return null;
                            }

                            theName = DeserializeImplementation.StringFrom(
                                keyValue.Value,
                                out error);
                            if (error != null)
                            {
                                error.PrependSegment(
                                    new Reporting.NameSegment(
                                        "name"));
                                return null;
                            }
                            if (theName == null)
                            {
                                throw new System.InvalidOperationException(
                                    "Unexpected theName null when error is also null");
                            }
                            break;
                        }
                        case "modelType":
                            {
                                if (keyValue.Value == null)
                                {
                                    error = new Reporting.Error(
                                        "Expected a model type, but got null");
                                    return null;
                                }
                                modelType = DeserializeImplementation.StringFrom(
                                    keyValue.Value,
                                    out error);
                                if (error != null)
                                {
                                    error.PrependSegment(
                                        new Reporting.NameSegment(
                                            "modelType"));
                                    return null;
                                }

                                if (modelType != "SomeItem")
                                {
                                    error = new Reporting.Error(
                                        "Expected the model type 'SomeItem', " +
                                        $"but got {modelType}");
                                    error.PrependSegment(
                                        new Reporting.NameSegment(
                                            "modelType"));
                                    return null;
                                }
                                break;
                            }
                        default:
                            error = new Reporting.Error(
                                $"Unexpected property: {keyValue.Key}");
                            return null;
                    }
                }

                if (theName == null)
                {
                    error = new Reporting.Error(
                        "Required property \"name\" is missing");
                    return null;
                }

                if (modelType == null)
                {
                    error = new Reporting.Error(
                        "Required property \"modelType\" is missing");
                    return null;
                }

                return new Aas.SomeItem(
                    theName
                         ?? throw new System.InvalidOperationException(
                            "Unexpected null, had to be handled before"));
            }  // internal static SomeItemFrom

            /// <summary>
            /// Deserialize an instance of AnotherItem from <paramref name="node" />.
            /// </summary>
            /// <param name="node">JSON node to be parsed</param>
            /// <param name="error">Error, if any, during the deserialization</param>
            internal static Aas.AnotherItem? AnotherItemFrom(
                Nodes.JsonNode node,
                out Reporting.Error? error)
            {
                error = null;

                Nodes.JsonObject? obj = node as Nodes.JsonObject;
                if (obj == null)
                {
                    error = new Reporting.Error(
                        $"Expected a JsonObject, but got {node.GetType()}");
                    return null;
                }

                long? theSerialNumber = null;

                string? modelType = null;

                foreach (var keyValue in obj)
                {
                    switch (keyValue.Key)
                    {
                        case "serialNumber":
                        {
                            if (keyValue.Value == null)
                            {
                                error = new Reporting.Error(
                                    "Unexpected null for a required property");
                                error.PrependSegment(
                                    new Reporting.NameSegment(
                                        "serialNumber"));
                                return null;
                            }

                            theSerialNumber = DeserializeImplementation.LongFrom(
                                keyValue.Value,
                                out error);
                            if (error != null)
                            {
                                error.PrependSegment(
                                    new Reporting.NameSegment(
                                        "serialNumber"));
                                return null;
                            }
                            if (theSerialNumber == null)
                            {
                                throw new System.InvalidOperationException(
                                    "Unexpected theSerialNumber null when error is also null");
                            }
                            break;
                        }
                        case "modelType":
                            {
                                if (keyValue.Value == null)
                                {
                                    error = new Reporting.Error(
                                        "Expected a model type, but got null");
                                    return null;
                                }
                                modelType = DeserializeImplementation.StringFrom(
                                    keyValue.Value,
                                    out error);
                                if (error != null)
                                {
                                    error.PrependSegment(
                                        new Reporting.NameSegment(
                                            "modelType"));
                                    return null;
                                }

                                if (modelType != "AnotherItem")
                                {
                                    error = new Reporting.Error(
                                        "Expected the model type 'AnotherItem', " +
                                        $"but got {modelType}");
                                    error.PrependSegment(
                                        new Reporting.NameSegment(
                                            "modelType"));
                                    return null;
                                }
                                break;
                            }
                        default:
                            error = new Reporting.Error(
                                $"Unexpected property: {keyValue.Key}");
                            return null;
                    }
                }

                if (theSerialNumber == null)
                {
                    error = new Reporting.Error(
                        "Required property \"serialNumber\" is missing");
                    return null;
                }

                if (modelType == null)
                {
                    error = new Reporting.Error(
                        "Required property \"modelType\" is missing");
                    return null;
                }

                return new Aas.AnotherItem(
                    theSerialNumber
                         ?? throw new System.InvalidOperationException(
                            "Unexpected null, had to be handled before"));
            }  // internal static AnotherItemFrom

            /// <summary>
            /// Deserialize an instance of Something from <paramref name="node" />.
            /// </summary>
            /// <param name="node">JSON node to be parsed</param>
            /// <param name="error">Error, if any, during the deserialization</param>
            internal static Aas.Something? SomethingFrom(
                Nodes.JsonNode node,
                out Reporting.Error? error)
            {
                error = null;

                Nodes.JsonObject? obj = node as Nodes.JsonObject;
                if (obj == null)
                {
                    error = new Reporting.Error(
                        $"Expected a JsonObject, but got {node.GetType()}");
                    return null;
                }

                (string, long)? thePair = null;
                (IAbstractItem, IAbstractItem)? theItems = null;
                (long, ISomeItem, IAbstractItem, ISomeItem, long, Result)? theTricky = null;

                foreach (var keyValue in obj)
                {
                    switch (keyValue.Key)
                    {
                        case "pair":
                        {
                            if (keyValue.Value == null)
                            {
                                error = new Reporting.Error(
                                    "Unexpected null for a required property");
                                error.PrependSegment(
                                    new Reporting.NameSegment(
                                        "pair"));
                                return null;
                            }

                            Nodes.JsonArray? arrayPair = keyValue.Value as Nodes.JsonArray;
                            if (arrayPair == null)
                            {
                                error = new Reporting.Error(
                                    $"Expected a JsonArray, but got {keyValue.Value.GetType()}");
                                error.PrependSegment(
                                    new Reporting.NameSegment(
                                        "pair"));
                                return null;
                            }
                            thePair = ParseTuple2(
                                arrayPair,
                                AsTupleItemDeserializer(DeserializeImplementation.StringFrom),
                                AsTupleItemDeserializer(DeserializeImplementation.LongFrom),
                                out error);
                            if (error != null)
                            {
                                error.PrependSegment(
                                    new Reporting.NameSegment(
                                        "pair"));
                                return null;
                            }
                            break;
                        }
                        case "items":
                        {
                            if (keyValue.Value == null)
                            {
                                error = new Reporting.Error(
                                    "Unexpected null for a required property");
                                error.PrependSegment(
                                    new Reporting.NameSegment(
                                        "items"));
                                return null;
                            }

                            Nodes.JsonArray? arrayItems = keyValue.Value as Nodes.JsonArray;
                            if (arrayItems == null)
                            {
                                error = new Reporting.Error(
                                    $"Expected a JsonArray, but got {keyValue.Value.GetType()}");
                                error.PrependSegment(
                                    new Reporting.NameSegment(
                                        "items"));
                                return null;
                            }
                            theItems = ParseTuple2(
                                arrayItems,
                                AsTupleItemDeserializer(DeserializeImplementation.IAbstractItemFrom),
                                AsTupleItemDeserializer(DeserializeImplementation.IAbstractItemFrom),
                                out error);
                            if (error != null)
                            {
                                error.PrependSegment(
                                    new Reporting.NameSegment(
                                        "items"));
                                return null;
                            }
                            break;
                        }
                        case "tricky":
                        {
                            if (keyValue.Value == null)
                            {
                                error = new Reporting.Error(
                                    "Unexpected null for a required property");
                                error.PrependSegment(
                                    new Reporting.NameSegment(
                                        "tricky"));
                                return null;
                            }

                            Nodes.JsonArray? arrayTricky = keyValue.Value as Nodes.JsonArray;
                            if (arrayTricky == null)
                            {
                                error = new Reporting.Error(
                                    $"Expected a JsonArray, but got {keyValue.Value.GetType()}");
                                error.PrependSegment(
                                    new Reporting.NameSegment(
                                        "tricky"));
                                return null;
                            }
                            theTricky = ParseTuple6(
                                arrayTricky,
                                AsTupleItemDeserializer(DeserializeImplementation.LongFrom),
                                AsTupleItemDeserializer(DeserializeImplementation.SomeItemFrom),
                                AsTupleItemDeserializer(DeserializeImplementation.IAbstractItemFrom),
                                AsTupleItemDeserializer(DeserializeImplementation.SomeItemFrom),
                                AsTupleItemDeserializer(DeserializeImplementation.LongFrom),
                                AsTupleItemDeserializer(DeserializeImplementation.ResultFrom),
                                out error);
                            if (error != null)
                            {
                                error.PrependSegment(
                                    new Reporting.NameSegment(
                                        "tricky"));
                                return null;
                            }
                            break;
                        }
                        default:
                            error = new Reporting.Error(
                                $"Unexpected property: {keyValue.Key}");
                            return null;
                    }
                }

                if (thePair == null)
                {
                    error = new Reporting.Error(
                        "Required property \"pair\" is missing");
                    return null;
                }

                if (theItems == null)
                {
                    error = new Reporting.Error(
                        "Required property \"items\" is missing");
                    return null;
                }

                if (theTricky == null)
                {
                    error = new Reporting.Error(
                        "Required property \"tricky\" is missing");
                    return null;
                }

                return new Aas.Something(
                    thePair
                         ?? throw new System.InvalidOperationException(
                            "Unexpected null, had to be handled before"),
                    theItems
                         ?? throw new System.InvalidOperationException(
                            "Unexpected null, had to be handled before"),
                    theTricky
                         ?? throw new System.InvalidOperationException(
                            "Unexpected null, had to be handled before"));
            }  // internal static SomethingFrom
        }  // public static class DeserializeImplementation

        /// <summary>
        /// Represent a critical error during the deserialization.
        /// </summary>
        public class Exception : System.Exception
        {
            public readonly string Path;
            public readonly string Cause;
            public Exception(string path, string cause)
                : base($"{cause} at: {path}")
            {
                Path = path;
                Cause = cause;
            }
        }

        /// <summary>
        /// Deserialize instances of meta-model classes from JSON nodes.
        /// </summary>
        /// <example>
        /// Here is an example how to parse an instance of IAbstractItem:
        /// <code>
        /// string someString = "... some JSON ...";
        /// var node = System.Text.Json.Nodes.JsonNode.Parse(someString);
        /// Aas.IAbstractItem anInstance = Deserialize.IAbstractItemFrom(
        ///     node);
        /// </code>
        /// </example>
        public static class Deserialize
        {
            /// <summary>
            /// Deserialize an instance of Result from <paramref name="node" />.
            /// </summary>
            /// <param name="node">JSON node to be parsed</param>
            /// <exception cref="Jsonization.Exception">
            /// Thrown when <paramref name="node" /> is not a valid JSON
            /// representation of Result.
            /// </exception>
            public static Aas.Result ResultFrom(
                Nodes.JsonNode node)
            {
                Aas.Result? result = DeserializeImplementation.ResultFrom(
                    node,
                    out Reporting.Error? error);
                if (error != null)
                {
                    throw new Jsonization.Exception(
                        Reporting.GenerateJsonPath(error.PathSegments),
                        error.Cause);
                }
                return result
                    ?? throw new System.InvalidOperationException(
                        "Unexpected output null when error is null");
            }

            /// <summary>
            /// Deserialize an instance of IAbstractItem from <paramref name="node" />.
            /// </summary>
            /// <param name="node">JSON node to be parsed</param>
            /// <exception cref="Jsonization.Exception">
            /// Thrown when <paramref name="node" /> is not a valid JSON
            /// representation of IAbstractItem.
            /// </exception>
            [CodeAnalysis.SuppressMessage("ReSharper", "InconsistentNaming")]
            public static Aas.IAbstractItem IAbstractItemFrom(
                Nodes.JsonNode node)
            {
                Aas.IAbstractItem? result = DeserializeImplementation.IAbstractItemFrom(
                    node,
                    out Reporting.Error? error);
                if (error != null)
                {
                    throw new Jsonization.Exception(
                        Reporting.GenerateJsonPath(error.PathSegments),
                        error.Cause);
                }
                return result
                    ?? throw new System.InvalidOperationException(
                        "Unexpected output null when error is null");
            }

            /// <summary>
            /// Deserialize an instance of SomeItem from <paramref name="node" />.
            /// </summary>
            /// <param name="node">JSON node to be parsed</param>
            /// <exception cref="Jsonization.Exception">
            /// Thrown when <paramref name="node" /> is not a valid JSON
            /// representation of SomeItem.
            /// </exception>
            public static Aas.SomeItem SomeItemFrom(
                Nodes.JsonNode node)
            {
                Aas.SomeItem? result = DeserializeImplementation.SomeItemFrom(
                    node,
                    out Reporting.Error? error);
                if (error != null)
                {
                    throw new Jsonization.Exception(
                        Reporting.GenerateJsonPath(error.PathSegments),
                        error.Cause);
                }
                return result
                    ?? throw new System.InvalidOperationException(
                        "Unexpected output null when error is null");
            }

            /// <summary>
            /// Deserialize an instance of AnotherItem from <paramref name="node" />.
            /// </summary>
            /// <param name="node">JSON node to be parsed</param>
            /// <exception cref="Jsonization.Exception">
            /// Thrown when <paramref name="node" /> is not a valid JSON
            /// representation of AnotherItem.
            /// </exception>
            public static Aas.AnotherItem AnotherItemFrom(
                Nodes.JsonNode node)
            {
                Aas.AnotherItem? result = DeserializeImplementation.AnotherItemFrom(
                    node,
                    out Reporting.Error? error);
                if (error != null)
                {
                    throw new Jsonization.Exception(
                        Reporting.GenerateJsonPath(error.PathSegments),
                        error.Cause);
                }
                return result
                    ?? throw new System.InvalidOperationException(
                        "Unexpected output null when error is null");
            }

            /// <summary>
            /// Deserialize an instance of Something from <paramref name="node" />.
            /// </summary>
            /// <param name="node">JSON node to be parsed</param>
            /// <exception cref="Jsonization.Exception">
            /// Thrown when <paramref name="node" /> is not a valid JSON
            /// representation of Something.
            /// </exception>
            public static Aas.Something SomethingFrom(
                Nodes.JsonNode node)
            {
                Aas.Something? result = DeserializeImplementation.SomethingFrom(
                    node,
                    out Reporting.Error? error);
                if (error != null)
                {
                    throw new Jsonization.Exception(
                        Reporting.GenerateJsonPath(error.PathSegments),
                        error.Cause);
                }
                return result
                    ?? throw new System.InvalidOperationException(
                        "Unexpected output null when error is null");
            }
        }  // public static class Deserialize

        internal class Transformer
            : Visitation.AbstractTransformer<Nodes.JsonObject>
        {
            /// <summary>
            /// Convert <paramref name="that" /> 64-bit long integer to a JSON value.
            /// </summary>
            /// <param name="that">value to be converted</param>
            /// <exception name="System.ArgumentException">
            /// Thrown if <paramref name="that" /> is not within the range where it
            /// can be losslessly converted to a double floating number.
            /// </exception>
            [CodeAnalysis.SuppressMessage("ReSharper", "UnusedMember.Local")]
            private static Nodes.JsonValue ToJsonValue(long that)
            {
                // We need to check that we can perform a lossless conversion.
                if ((long)((double)that) != that)
                {
                    throw new System.ArgumentException(
                        $"The number can not be losslessly represented in JSON: {that}");
                }
                return Nodes.JsonValue.Create(that);
            }

            /// <summary>
            /// Serialize every item of <paramref name="items" /> with
            /// <paramref name="serializeItem" /> into a JSON array.
            /// </summary>
            /// <remarks>
            /// This is shared by all the list-typed properties.
            /// </remarks>
            /// <typeparam name="T">Type of a single list item</typeparam>
            private static Nodes.JsonArray SerializeArray<T>(
                IEnumerable<T> items,
                System.Func<T, Nodes.JsonNode?> serializeItem)
            {
                var result = new Nodes.JsonArray();
                foreach (T item in items)
                {
                    result.Add(
                        serializeItem(item));
                }
                return result;
            }

            /// <summary>
            /// Convert <paramref name="that" /> to a JSON value.
            /// </summary>
            [CodeAnalysis.SuppressMessage("ReSharper", "UnusedMember.Local")]
            private static Nodes.JsonValue ToJsonValue(bool that)
            {
                return Nodes.JsonValue.Create(that);
            }

            /// <summary>
            /// Convert <paramref name="that" /> to a JSON value.
            /// </summary>
            [CodeAnalysis.SuppressMessage("ReSharper", "UnusedMember.Local")]
            private static Nodes.JsonValue ToJsonValue(double that)
            {
                return Nodes.JsonValue.Create(that);
            }

            /// <summary>
            /// Convert <paramref name="that" /> to a JSON value.
            /// </summary>
            [CodeAnalysis.SuppressMessage("ReSharper", "UnusedMember.Local")]
            private static Nodes.JsonValue ToJsonValue(string that)
            {
                return Nodes.JsonValue.Create(that);
            }

            /// <summary>
            /// Convert <paramref name="that" /> to a JSON value.
            /// </summary>
            [CodeAnalysis.SuppressMessage("ReSharper", "UnusedMember.Local")]
            private static Nodes.JsonValue ToJsonValue(byte[] that)
            {
                return Nodes.JsonValue.Create(System.Convert.ToBase64String(that));
            }

            /// <summary>
            /// Serialize the tuple <paramref name="that" /> of 2 item(s) with
            /// <paramref name="serializeItem0" />, <paramref name="serializeItem1" />, *etc.*
            /// into a JSON array.
            /// </summary>
            /// <remarks>
            /// This is shared by all the tuple-typed properties of arity 2.
            /// </remarks>
            private static Nodes.JsonArray SerializeTuple2<T0, T1>(
                (T0, T1) that,
                System.Func<T0, Nodes.JsonNode?> serializeItem0,
                System.Func<T1, Nodes.JsonNode?> serializeItem1)
            {
                var result = new Nodes.JsonArray();
                result.Add(serializeItem0(that.Item1));
                result.Add(serializeItem1(that.Item2));
                return result;
            }

            /// <summary>
            /// Serialize the tuple <paramref name="that" /> of 6 item(s) with
            /// <paramref name="serializeItem0" />, <paramref name="serializeItem1" />, *etc.*
            /// into a JSON array.
            /// </summary>
            /// <remarks>
            /// This is shared by all the tuple-typed properties of arity 6.
            /// </remarks>
            private static Nodes.JsonArray SerializeTuple6<T0, T1, T2, T3, T4, T5>(
                (T0, T1, T2, T3, T4, T5) that,
                System.Func<T0, Nodes.JsonNode?> serializeItem0,
                System.Func<T1, Nodes.JsonNode?> serializeItem1,
                System.Func<T2, Nodes.JsonNode?> serializeItem2,
                System.Func<T3, Nodes.JsonNode?> serializeItem3,
                System.Func<T4, Nodes.JsonNode?> serializeItem4,
                System.Func<T5, Nodes.JsonNode?> serializeItem5)
            {
                var result = new Nodes.JsonArray();
                result.Add(serializeItem0(that.Item1));
                result.Add(serializeItem1(that.Item2));
                result.Add(serializeItem2(that.Item3));
                result.Add(serializeItem3(that.Item4));
                result.Add(serializeItem4(that.Item5));
                result.Add(serializeItem5(that.Item6));
                return result;
            }

            public override Nodes.JsonObject TransformSomeItem(
                Aas.ISomeItem that
            )
            {
                var result = new Nodes.JsonObject();

                result["name"] = Nodes.JsonValue.Create(
                    that.Name);

                result["modelType"] = "SomeItem";

                return result;
            }

            public override Nodes.JsonObject TransformAnotherItem(
                Aas.IAnotherItem that
            )
            {
                var result = new Nodes.JsonObject();

                result["serialNumber"] = Transformer.ToJsonValue(
                    that.SerialNumber);

                result["modelType"] = "AnotherItem";

                return result;
            }

            public override Nodes.JsonObject TransformSomething(
                Aas.ISomething that
            )
            {
                var result = new Nodes.JsonObject();

                Nodes.JsonArray arrayPair = SerializeTuple2(
                    that.Pair,
                    Transformer.ToJsonValue,
                    Transformer.ToJsonValue);
                result["pair"] = arrayPair;

                Nodes.JsonArray arrayItems = SerializeTuple2(
                    that.Items,
                    Transform,
                    Transform);
                result["items"] = arrayItems;

                Nodes.JsonArray arrayTricky = SerializeTuple6(
                    that.Tricky,
                    Transformer.ToJsonValue,
                    Transform,
                    Transform,
                    Transform,
                    Transformer.ToJsonValue,
                    Serialize.ResultToJsonValue);
                result["tricky"] = arrayTricky;

                return result;
            }
        }  // internal class Transformer

        /// <summary>
        /// Serialize instances of meta-model classes to JSON elements.
        /// </summary>
        /// <example>
        /// Here is an example how to serialize an instance of IAbstractItem:
        /// <code>
        /// var anInstance = new Aas.IAbstractItem(
        ///     // ... some constructor arguments ...
        /// );
        /// System.Text.Json.Nodes.JsonObject element = (
        ///     Serialize.ToJsonObject(
        ///         anInstance));
        /// </code>
        /// </example>
        public static class Serialize
        {
            private static readonly Transformer Transformer = new Transformer();

            /// <summary>
            /// Serialize an instance of the meta-model into a JSON object.
            /// </summary>
            public static Nodes.JsonObject ToJsonObject(Aas.IClass that)
            {
                return Serialize.Transformer.Transform(that);
            }

            /// <summary>
            /// Serialize a literal of Result into a JSON string.
            /// </summary>
            public static Nodes.JsonValue ResultToJsonValue(Aas.Result that)
            {
                string? text = Stringification.ToString(that);
                return Nodes.JsonValue.Create(text)
                    ?? throw new System.ArgumentException(
                        $"Invalid Result: {that}");
            }
        }  // public static class Serialize
    }  // public static class Jsonization
}  // namespace dummy

/*
 * This code has been automatically generated by aas-core-codegen.
 * Do NOT edit or append.
 */
