// Package types provides the data structures corresponding to the meta-model.
package types

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.

import (
	"fmt"

	aascommon "github.com/dummy-works/dummy/common"
)

// Enumerate the model types for faster type switches.
//
// For example, you can use an array of function pointers to
// implement such a switch.
type ModelType int
const (
	ModelTypeStructuralFirst ModelType = iota
	ModelTypeStructuralSecond
	ModelTypeMixedAbstractDescendantOne
	ModelTypeMixedAbstractDescendantTwo
	ModelTypeMixedConcreteWithDescendants
	ModelTypeMixedConcreteWithDescendantsChild
	ModelTypeMixedConcreteLeaf
	ModelTypeModelTypedFirst
	ModelTypeModelTypedSecond
	ModelTypeSomething
)

// Represent the most general interface of an AAS model.
type IClass interface {
	// Return the concrete model type at run-time.
	//
	// Use the model type if you want to switch on the concrete model type
	// in efficient manner, as the compiler will most probably implement
	// the switch in form of a jump table.
	ModelType() ModelType

	// Apply the action on the instances referenced from this instance.
	//
	// If any of the actions returns abort `true`, the descent is immediately
	// stopped,  and abort `true` is also returned. Otherwise, return abort `false`.
	//
	// We do not recurse into the referenced instances.
	//
	// The action is not applied on this instance.
	DescendOnce(action func(IClass) bool) (abort bool)

	// Apply the action recursively on the instances referenced from this instance.
	//
	// If any of the actions returns abort `true`, the descent is immediately
	// stopped,  and abort `true` is also returned. Otherwise, return abort `false`.
	//
	// The action is not applied on this instance.
	Descend(action func(IClass) bool) (abort bool)
}

type IStructuralFirst interface {
	IClass

	UniqueToFirst() string;

	SetUniqueToFirst(
		value string,
	);
}

// Check whether the instance corresponds to [aastypes.IStructuralFirst]
// based on its run-time model type.
//
// The implementation uses a switch statements which is
// most probably compiled as an efficient jump table by the compiler.
func IsStructuralFirst(
	that IClass,
) (ok bool) {
	ok = that.ModelType() == ModelTypeStructuralFirst
	return
}

// Implements IStructuralFirst.
type StructuralFirst struct {
	uniqueToFirst string
}

func (sf *StructuralFirst) UniqueToFirst(
) string {
	return sf.uniqueToFirst
}

func (sf *StructuralFirst) SetUniqueToFirst(
	value string,
) {
	sf.uniqueToFirst = value
}

func (sf *StructuralFirst) ModelType(
) ModelType {
	return ModelTypeStructuralFirst
}

// Apply the action on the instances referenced from sf.
//
// If any of the actions returns abort `true`, the descent is immediately
// stopped,  and abort `true` is also returned. Otherwise, return abort `false`.
//
// We do not recurse into the referenced instances.
//
// The action is not applied on sf.
func (sf *StructuralFirst) DescendOnce(
	action func(IClass) bool,
) (abort bool) {
	// No descendable properties

	return
}

// Apply the action recursively on the instances referenced from sf.
//
// If any of the actions returns abort `true`, the descent is immediately
// stopped,  and abort `true` is also returned. Otherwise, return abort `false`.
//
// The action is not applied on sf.
func (sf *StructuralFirst) Descend(
	action func(IClass) bool,
) (abort bool) {
	// No descendable properties

	return
}

// Create a new instance of StructuralFirst with
// the given properties.
func NewStructuralFirst(
	uniqueToFirst string,
) *StructuralFirst {
	return &StructuralFirst{
		uniqueToFirst: uniqueToFirst,
	}
}

type IStructuralSecond interface {
	IClass

	UniqueToSecond() string;

	SetUniqueToSecond(
		value string,
	);
}

// Check whether the instance corresponds to [aastypes.IStructuralSecond]
// based on its run-time model type.
//
// The implementation uses a switch statements which is
// most probably compiled as an efficient jump table by the compiler.
func IsStructuralSecond(
	that IClass,
) (ok bool) {
	ok = that.ModelType() == ModelTypeStructuralSecond
	return
}

// Implements IStructuralSecond.
type StructuralSecond struct {
	uniqueToSecond string
}

func (ss *StructuralSecond) UniqueToSecond(
) string {
	return ss.uniqueToSecond
}

func (ss *StructuralSecond) SetUniqueToSecond(
	value string,
) {
	ss.uniqueToSecond = value
}

func (ss *StructuralSecond) ModelType(
) ModelType {
	return ModelTypeStructuralSecond
}

// Apply the action on the instances referenced from ss.
//
// If any of the actions returns abort `true`, the descent is immediately
// stopped,  and abort `true` is also returned. Otherwise, return abort `false`.
//
// We do not recurse into the referenced instances.
//
// The action is not applied on ss.
func (ss *StructuralSecond) DescendOnce(
	action func(IClass) bool,
) (abort bool) {
	// No descendable properties

	return
}

// Apply the action recursively on the instances referenced from ss.
//
// If any of the actions returns abort `true`, the descent is immediately
// stopped,  and abort `true` is also returned. Otherwise, return abort `false`.
//
// The action is not applied on ss.
func (ss *StructuralSecond) Descend(
	action func(IClass) bool,
) (abort bool) {
	// No descendable properties

	return
}

// Create a new instance of StructuralSecond with
// the given properties.
func NewStructuralSecond(
	uniqueToSecond string,
) *StructuralSecond {
	return &StructuralSecond{
		uniqueToSecond: uniqueToSecond,
	}
}

type structuralUnionValueKind int

const (
	structuralUnionValueKindStructuralFirst structuralUnionValueKind = iota
	structuralUnionValueKindStructuralSecond
)

// Represent a union of [IStructuralFirst] and [IStructuralSecond].
type StructuralUnion struct {
	valueKind structuralUnionValueKind
	asStructuralFirst IStructuralFirst
	asStructuralSecond IStructuralSecond
}

// Wrap `that` as an instance of [StructuralUnion].
func NewStructuralUnionFromStructuralFirst(that IStructuralFirst) *StructuralUnion {
	return &StructuralUnion{
		valueKind: structuralUnionValueKindStructuralFirst,
		asStructuralFirst: that,
	}
}

// Wrap `that` as an instance of [StructuralUnion].
func NewStructuralUnionFromStructuralSecond(that IStructuralSecond) *StructuralUnion {
	return &StructuralUnion{
		valueKind: structuralUnionValueKindStructuralSecond,
		asStructuralSecond: that,
	}
}

// Get the underlying instance regardless of the concrete case.
func (s *StructuralUnion) Underlying() IClass {
	switch s.valueKind {
	case structuralUnionValueKindStructuralFirst:
		return s.asStructuralFirst
	case structuralUnionValueKindStructuralSecond:
		return s.asStructuralSecond
	default:
		panic(
			fmt.Sprintf(
				"Unexpected value kind: %v",
				s.valueKind,
			),
		)
	}
}

// Wrap `that` as an instance of [StructuralUnion] based on its run-time type.
func StructuralUnionFromUnderlying(that IClass) *StructuralUnion {
	switch casted := that.(type) {
	case IStructuralFirst:
		return NewStructuralUnionFromStructuralFirst(casted)
	case IStructuralSecond:
		return NewStructuralUnionFromStructuralSecond(casted)
	default:
		panic(
			fmt.Sprintf(
				"Unexpected run-time type for the union StructuralUnion: %T",
				that,
			),
		)
	}
}

type IMixedAbstractMember interface {
	IClass
}

// Check whether the instance corresponds to [aastypes.IMixedAbstractMember]
// based on its run-time model type.
//
// The implementation uses a switch statements which is
// most probably compiled as an efficient jump table by the compiler.
func IsMixedAbstractMember(
	that IClass,
) (ok bool) {
	switch that.ModelType() {
	case ModelTypeMixedAbstractDescendantOne:
		ok = true
	case ModelTypeMixedAbstractDescendantTwo:
		ok = true
	}
	return
}

type IMixedAbstractDescendantOne interface {
	IMixedAbstractMember

	UniqueToAbstractDescendantOne() string;

	SetUniqueToAbstractDescendantOne(
		value string,
	);
}

// Check whether the instance corresponds to [aastypes.IMixedAbstractDescendantOne]
// based on its run-time model type.
//
// The implementation uses a switch statements which is
// most probably compiled as an efficient jump table by the compiler.
func IsMixedAbstractDescendantOne(
	that IClass,
) (ok bool) {
	ok = that.ModelType() == ModelTypeMixedAbstractDescendantOne
	return
}

// Implements IMixedAbstractDescendantOne.
type MixedAbstractDescendantOne struct {
	uniqueToAbstractDescendantOne string
}

func (mado *MixedAbstractDescendantOne) UniqueToAbstractDescendantOne(
) string {
	return mado.uniqueToAbstractDescendantOne
}

func (mado *MixedAbstractDescendantOne) SetUniqueToAbstractDescendantOne(
	value string,
) {
	mado.uniqueToAbstractDescendantOne = value
}

func (mado *MixedAbstractDescendantOne) ModelType(
) ModelType {
	return ModelTypeMixedAbstractDescendantOne
}

// Apply the action on the instances referenced from mado.
//
// If any of the actions returns abort `true`, the descent is immediately
// stopped,  and abort `true` is also returned. Otherwise, return abort `false`.
//
// We do not recurse into the referenced instances.
//
// The action is not applied on mado.
func (mado *MixedAbstractDescendantOne) DescendOnce(
	action func(IClass) bool,
) (abort bool) {
	// No descendable properties

	return
}

// Apply the action recursively on the instances referenced from mado.
//
// If any of the actions returns abort `true`, the descent is immediately
// stopped,  and abort `true` is also returned. Otherwise, return abort `false`.
//
// The action is not applied on mado.
func (mado *MixedAbstractDescendantOne) Descend(
	action func(IClass) bool,
) (abort bool) {
	// No descendable properties

	return
}

// Create a new instance of MixedAbstractDescendantOne with
// the given properties.
func NewMixedAbstractDescendantOne(
	uniqueToAbstractDescendantOne string,
) *MixedAbstractDescendantOne {
	return &MixedAbstractDescendantOne{
		uniqueToAbstractDescendantOne: uniqueToAbstractDescendantOne,
	}
}

type IMixedAbstractDescendantTwo interface {
	IMixedAbstractMember

	UniqueToAbstractDescendantTwo() string;

	SetUniqueToAbstractDescendantTwo(
		value string,
	);
}

// Check whether the instance corresponds to [aastypes.IMixedAbstractDescendantTwo]
// based on its run-time model type.
//
// The implementation uses a switch statements which is
// most probably compiled as an efficient jump table by the compiler.
func IsMixedAbstractDescendantTwo(
	that IClass,
) (ok bool) {
	ok = that.ModelType() == ModelTypeMixedAbstractDescendantTwo
	return
}

// Implements IMixedAbstractDescendantTwo.
type MixedAbstractDescendantTwo struct {
	uniqueToAbstractDescendantTwo string
}

func (madt *MixedAbstractDescendantTwo) UniqueToAbstractDescendantTwo(
) string {
	return madt.uniqueToAbstractDescendantTwo
}

func (madt *MixedAbstractDescendantTwo) SetUniqueToAbstractDescendantTwo(
	value string,
) {
	madt.uniqueToAbstractDescendantTwo = value
}

func (madt *MixedAbstractDescendantTwo) ModelType(
) ModelType {
	return ModelTypeMixedAbstractDescendantTwo
}

// Apply the action on the instances referenced from madt.
//
// If any of the actions returns abort `true`, the descent is immediately
// stopped,  and abort `true` is also returned. Otherwise, return abort `false`.
//
// We do not recurse into the referenced instances.
//
// The action is not applied on madt.
func (madt *MixedAbstractDescendantTwo) DescendOnce(
	action func(IClass) bool,
) (abort bool) {
	// No descendable properties

	return
}

// Apply the action recursively on the instances referenced from madt.
//
// If any of the actions returns abort `true`, the descent is immediately
// stopped,  and abort `true` is also returned. Otherwise, return abort `false`.
//
// The action is not applied on madt.
func (madt *MixedAbstractDescendantTwo) Descend(
	action func(IClass) bool,
) (abort bool) {
	// No descendable properties

	return
}

// Create a new instance of MixedAbstractDescendantTwo with
// the given properties.
func NewMixedAbstractDescendantTwo(
	uniqueToAbstractDescendantTwo string,
) *MixedAbstractDescendantTwo {
	return &MixedAbstractDescendantTwo{
		uniqueToAbstractDescendantTwo: uniqueToAbstractDescendantTwo,
	}
}

type IMixedConcreteWithDescendants interface {
	IClass

	SomeBaseProperty() string;

	SetSomeBaseProperty(
		value string,
	);
}

// Check whether the instance corresponds to [aastypes.IMixedConcreteWithDescendants]
// based on its run-time model type.
//
// The implementation uses a switch statements which is
// most probably compiled as an efficient jump table by the compiler.
func IsMixedConcreteWithDescendants(
	that IClass,
) (ok bool) {
	switch that.ModelType() {
	case ModelTypeMixedConcreteWithDescendants:
		ok = true
	case ModelTypeMixedConcreteWithDescendantsChild:
		ok = true
	}
	return
}

// Implements IMixedConcreteWithDescendants.
type MixedConcreteWithDescendants struct {
	someBaseProperty string
}

func (mcwd *MixedConcreteWithDescendants) SomeBaseProperty(
) string {
	return mcwd.someBaseProperty
}

func (mcwd *MixedConcreteWithDescendants) SetSomeBaseProperty(
	value string,
) {
	mcwd.someBaseProperty = value
}

func (mcwd *MixedConcreteWithDescendants) ModelType(
) ModelType {
	return ModelTypeMixedConcreteWithDescendants
}

// Apply the action on the instances referenced from mcwd.
//
// If any of the actions returns abort `true`, the descent is immediately
// stopped,  and abort `true` is also returned. Otherwise, return abort `false`.
//
// We do not recurse into the referenced instances.
//
// The action is not applied on mcwd.
func (mcwd *MixedConcreteWithDescendants) DescendOnce(
	action func(IClass) bool,
) (abort bool) {
	// No descendable properties

	return
}

// Apply the action recursively on the instances referenced from mcwd.
//
// If any of the actions returns abort `true`, the descent is immediately
// stopped,  and abort `true` is also returned. Otherwise, return abort `false`.
//
// The action is not applied on mcwd.
func (mcwd *MixedConcreteWithDescendants) Descend(
	action func(IClass) bool,
) (abort bool) {
	// No descendable properties

	return
}

// Create a new instance of MixedConcreteWithDescendants with
// the given properties.
func NewMixedConcreteWithDescendants(
	someBaseProperty string,
) *MixedConcreteWithDescendants {
	return &MixedConcreteWithDescendants{
		someBaseProperty: someBaseProperty,
	}
}

type IMixedConcreteWithDescendantsChild interface {
	IMixedConcreteWithDescendants

	SomeChildProperty() string;

	SetSomeChildProperty(
		value string,
	);
}

// Check whether the instance corresponds to [aastypes.IMixedConcreteWithDescendantsChild]
// based on its run-time model type.
//
// The implementation uses a switch statements which is
// most probably compiled as an efficient jump table by the compiler.
func IsMixedConcreteWithDescendantsChild(
	that IClass,
) (ok bool) {
	ok = that.ModelType() == ModelTypeMixedConcreteWithDescendantsChild
	return
}

// Implements IMixedConcreteWithDescendantsChild.
type MixedConcreteWithDescendantsChild struct {
	someBaseProperty string
	someChildProperty string
}

func (mcwdc *MixedConcreteWithDescendantsChild) SomeBaseProperty(
) string {
	return mcwdc.someBaseProperty
}

func (mcwdc *MixedConcreteWithDescendantsChild) SetSomeBaseProperty(
	value string,
) {
	mcwdc.someBaseProperty = value
}

func (mcwdc *MixedConcreteWithDescendantsChild) SomeChildProperty(
) string {
	return mcwdc.someChildProperty
}

func (mcwdc *MixedConcreteWithDescendantsChild) SetSomeChildProperty(
	value string,
) {
	mcwdc.someChildProperty = value
}

func (mcwdc *MixedConcreteWithDescendantsChild) ModelType(
) ModelType {
	return ModelTypeMixedConcreteWithDescendantsChild
}

// Apply the action on the instances referenced from mcwdc.
//
// If any of the actions returns abort `true`, the descent is immediately
// stopped,  and abort `true` is also returned. Otherwise, return abort `false`.
//
// We do not recurse into the referenced instances.
//
// The action is not applied on mcwdc.
func (mcwdc *MixedConcreteWithDescendantsChild) DescendOnce(
	action func(IClass) bool,
) (abort bool) {
	// No descendable properties

	return
}

// Apply the action recursively on the instances referenced from mcwdc.
//
// If any of the actions returns abort `true`, the descent is immediately
// stopped,  and abort `true` is also returned. Otherwise, return abort `false`.
//
// The action is not applied on mcwdc.
func (mcwdc *MixedConcreteWithDescendantsChild) Descend(
	action func(IClass) bool,
) (abort bool) {
	// No descendable properties

	return
}

// Create a new instance of MixedConcreteWithDescendantsChild with
// the given properties.
func NewMixedConcreteWithDescendantsChild(
	someBaseProperty string,
	someChildProperty string,
) *MixedConcreteWithDescendantsChild {
	return &MixedConcreteWithDescendantsChild{
		someBaseProperty: someBaseProperty,
		someChildProperty: someChildProperty,
	}
}

type IMixedConcreteLeaf interface {
	IClass

	UniqueToConcreteLeaf() string;

	SetUniqueToConcreteLeaf(
		value string,
	);
}

// Check whether the instance corresponds to [aastypes.IMixedConcreteLeaf]
// based on its run-time model type.
//
// The implementation uses a switch statements which is
// most probably compiled as an efficient jump table by the compiler.
func IsMixedConcreteLeaf(
	that IClass,
) (ok bool) {
	ok = that.ModelType() == ModelTypeMixedConcreteLeaf
	return
}

// Implements IMixedConcreteLeaf.
type MixedConcreteLeaf struct {
	uniqueToConcreteLeaf string
}

func (mcl *MixedConcreteLeaf) UniqueToConcreteLeaf(
) string {
	return mcl.uniqueToConcreteLeaf
}

func (mcl *MixedConcreteLeaf) SetUniqueToConcreteLeaf(
	value string,
) {
	mcl.uniqueToConcreteLeaf = value
}

func (mcl *MixedConcreteLeaf) ModelType(
) ModelType {
	return ModelTypeMixedConcreteLeaf
}

// Apply the action on the instances referenced from mcl.
//
// If any of the actions returns abort `true`, the descent is immediately
// stopped,  and abort `true` is also returned. Otherwise, return abort `false`.
//
// We do not recurse into the referenced instances.
//
// The action is not applied on mcl.
func (mcl *MixedConcreteLeaf) DescendOnce(
	action func(IClass) bool,
) (abort bool) {
	// No descendable properties

	return
}

// Apply the action recursively on the instances referenced from mcl.
//
// If any of the actions returns abort `true`, the descent is immediately
// stopped,  and abort `true` is also returned. Otherwise, return abort `false`.
//
// The action is not applied on mcl.
func (mcl *MixedConcreteLeaf) Descend(
	action func(IClass) bool,
) (abort bool) {
	// No descendable properties

	return
}

// Create a new instance of MixedConcreteLeaf with
// the given properties.
func NewMixedConcreteLeaf(
	uniqueToConcreteLeaf string,
) *MixedConcreteLeaf {
	return &MixedConcreteLeaf{
		uniqueToConcreteLeaf: uniqueToConcreteLeaf,
	}
}

type mixedUnionValueKind int

const (
	mixedUnionValueKindMixedAbstractDescendantOne mixedUnionValueKind = iota
	mixedUnionValueKindMixedAbstractDescendantTwo
	mixedUnionValueKindMixedConcreteWithDescendantsChild
	mixedUnionValueKindMixedConcreteWithDescendants
	mixedUnionValueKindMixedConcreteLeaf
)

// Represent a union of [IMixedAbstractDescendantOne], [IMixedAbstractDescendantTwo], [IMixedConcreteWithDescendantsChild], [IMixedConcreteWithDescendants] and [IMixedConcreteLeaf].
type MixedUnion struct {
	valueKind mixedUnionValueKind
	asMixedAbstractDescendantOne IMixedAbstractDescendantOne
	asMixedAbstractDescendantTwo IMixedAbstractDescendantTwo
	asMixedConcreteWithDescendantsChild IMixedConcreteWithDescendantsChild
	asMixedConcreteWithDescendants IMixedConcreteWithDescendants
	asMixedConcreteLeaf IMixedConcreteLeaf
}

// Wrap `that` as an instance of [MixedUnion].
func NewMixedUnionFromMixedAbstractDescendantOne(that IMixedAbstractDescendantOne) *MixedUnion {
	return &MixedUnion{
		valueKind: mixedUnionValueKindMixedAbstractDescendantOne,
		asMixedAbstractDescendantOne: that,
	}
}

// Wrap `that` as an instance of [MixedUnion].
func NewMixedUnionFromMixedAbstractDescendantTwo(that IMixedAbstractDescendantTwo) *MixedUnion {
	return &MixedUnion{
		valueKind: mixedUnionValueKindMixedAbstractDescendantTwo,
		asMixedAbstractDescendantTwo: that,
	}
}

// Wrap `that` as an instance of [MixedUnion].
func NewMixedUnionFromMixedConcreteWithDescendantsChild(that IMixedConcreteWithDescendantsChild) *MixedUnion {
	return &MixedUnion{
		valueKind: mixedUnionValueKindMixedConcreteWithDescendantsChild,
		asMixedConcreteWithDescendantsChild: that,
	}
}

// Wrap `that` as an instance of [MixedUnion].
func NewMixedUnionFromMixedConcreteWithDescendants(that IMixedConcreteWithDescendants) *MixedUnion {
	return &MixedUnion{
		valueKind: mixedUnionValueKindMixedConcreteWithDescendants,
		asMixedConcreteWithDescendants: that,
	}
}

// Wrap `that` as an instance of [MixedUnion].
func NewMixedUnionFromMixedConcreteLeaf(that IMixedConcreteLeaf) *MixedUnion {
	return &MixedUnion{
		valueKind: mixedUnionValueKindMixedConcreteLeaf,
		asMixedConcreteLeaf: that,
	}
}

// Get the underlying instance regardless of the concrete case.
func (m *MixedUnion) Underlying() IClass {
	switch m.valueKind {
	case mixedUnionValueKindMixedAbstractDescendantOne:
		return m.asMixedAbstractDescendantOne
	case mixedUnionValueKindMixedAbstractDescendantTwo:
		return m.asMixedAbstractDescendantTwo
	case mixedUnionValueKindMixedConcreteWithDescendantsChild:
		return m.asMixedConcreteWithDescendantsChild
	case mixedUnionValueKindMixedConcreteWithDescendants:
		return m.asMixedConcreteWithDescendants
	case mixedUnionValueKindMixedConcreteLeaf:
		return m.asMixedConcreteLeaf
	default:
		panic(
			fmt.Sprintf(
				"Unexpected value kind: %v",
				m.valueKind,
			),
		)
	}
}

// Wrap `that` as an instance of [MixedUnion] based on its run-time type.
func MixedUnionFromUnderlying(that IClass) *MixedUnion {
	switch casted := that.(type) {
	case IMixedAbstractDescendantOne:
		return NewMixedUnionFromMixedAbstractDescendantOne(casted)
	case IMixedAbstractDescendantTwo:
		return NewMixedUnionFromMixedAbstractDescendantTwo(casted)
	case IMixedConcreteWithDescendantsChild:
		return NewMixedUnionFromMixedConcreteWithDescendantsChild(casted)
	case IMixedConcreteWithDescendants:
		return NewMixedUnionFromMixedConcreteWithDescendants(casted)
	case IMixedConcreteLeaf:
		return NewMixedUnionFromMixedConcreteLeaf(casted)
	default:
		panic(
			fmt.Sprintf(
				"Unexpected run-time type for the union MixedUnion: %T",
				that,
			),
		)
	}
}

type IModelTypedFirst interface {
	IClass

	SomeProperty() string;

	SetSomeProperty(
		value string,
	);
}

// Check whether the instance corresponds to [aastypes.IModelTypedFirst]
// based on its run-time model type.
//
// The implementation uses a switch statements which is
// most probably compiled as an efficient jump table by the compiler.
func IsModelTypedFirst(
	that IClass,
) (ok bool) {
	ok = that.ModelType() == ModelTypeModelTypedFirst
	return
}

// Implements IModelTypedFirst.
type ModelTypedFirst struct {
	someProperty string
}

func (mtf *ModelTypedFirst) SomeProperty(
) string {
	return mtf.someProperty
}

func (mtf *ModelTypedFirst) SetSomeProperty(
	value string,
) {
	mtf.someProperty = value
}

func (mtf *ModelTypedFirst) ModelType(
) ModelType {
	return ModelTypeModelTypedFirst
}

// Apply the action on the instances referenced from mtf.
//
// If any of the actions returns abort `true`, the descent is immediately
// stopped,  and abort `true` is also returned. Otherwise, return abort `false`.
//
// We do not recurse into the referenced instances.
//
// The action is not applied on mtf.
func (mtf *ModelTypedFirst) DescendOnce(
	action func(IClass) bool,
) (abort bool) {
	// No descendable properties

	return
}

// Apply the action recursively on the instances referenced from mtf.
//
// If any of the actions returns abort `true`, the descent is immediately
// stopped,  and abort `true` is also returned. Otherwise, return abort `false`.
//
// The action is not applied on mtf.
func (mtf *ModelTypedFirst) Descend(
	action func(IClass) bool,
) (abort bool) {
	// No descendable properties

	return
}

// Create a new instance of ModelTypedFirst with
// the given properties.
func NewModelTypedFirst(
	someProperty string,
) *ModelTypedFirst {
	return &ModelTypedFirst{
		someProperty: someProperty,
	}
}

type IModelTypedSecond interface {
	IClass

	SomeProperty() string;

	SetSomeProperty(
		value string,
	);
}

// Check whether the instance corresponds to [aastypes.IModelTypedSecond]
// based on its run-time model type.
//
// The implementation uses a switch statements which is
// most probably compiled as an efficient jump table by the compiler.
func IsModelTypedSecond(
	that IClass,
) (ok bool) {
	ok = that.ModelType() == ModelTypeModelTypedSecond
	return
}

// Implements IModelTypedSecond.
type ModelTypedSecond struct {
	someProperty string
}

func (mts *ModelTypedSecond) SomeProperty(
) string {
	return mts.someProperty
}

func (mts *ModelTypedSecond) SetSomeProperty(
	value string,
) {
	mts.someProperty = value
}

func (mts *ModelTypedSecond) ModelType(
) ModelType {
	return ModelTypeModelTypedSecond
}

// Apply the action on the instances referenced from mts.
//
// If any of the actions returns abort `true`, the descent is immediately
// stopped,  and abort `true` is also returned. Otherwise, return abort `false`.
//
// We do not recurse into the referenced instances.
//
// The action is not applied on mts.
func (mts *ModelTypedSecond) DescendOnce(
	action func(IClass) bool,
) (abort bool) {
	// No descendable properties

	return
}

// Apply the action recursively on the instances referenced from mts.
//
// If any of the actions returns abort `true`, the descent is immediately
// stopped,  and abort `true` is also returned. Otherwise, return abort `false`.
//
// The action is not applied on mts.
func (mts *ModelTypedSecond) Descend(
	action func(IClass) bool,
) (abort bool) {
	// No descendable properties

	return
}

// Create a new instance of ModelTypedSecond with
// the given properties.
func NewModelTypedSecond(
	someProperty string,
) *ModelTypedSecond {
	return &ModelTypedSecond{
		someProperty: someProperty,
	}
}

type modelTypedUnionValueKind int

const (
	modelTypedUnionValueKindModelTypedFirst modelTypedUnionValueKind = iota
	modelTypedUnionValueKindModelTypedSecond
)

// Represent a union of [IModelTypedFirst] and [IModelTypedSecond].
type ModelTypedUnion struct {
	valueKind modelTypedUnionValueKind
	asModelTypedFirst IModelTypedFirst
	asModelTypedSecond IModelTypedSecond
}

// Wrap `that` as an instance of [ModelTypedUnion].
func NewModelTypedUnionFromModelTypedFirst(that IModelTypedFirst) *ModelTypedUnion {
	return &ModelTypedUnion{
		valueKind: modelTypedUnionValueKindModelTypedFirst,
		asModelTypedFirst: that,
	}
}

// Wrap `that` as an instance of [ModelTypedUnion].
func NewModelTypedUnionFromModelTypedSecond(that IModelTypedSecond) *ModelTypedUnion {
	return &ModelTypedUnion{
		valueKind: modelTypedUnionValueKindModelTypedSecond,
		asModelTypedSecond: that,
	}
}

// Get the underlying instance regardless of the concrete case.
func (m *ModelTypedUnion) Underlying() IClass {
	switch m.valueKind {
	case modelTypedUnionValueKindModelTypedFirst:
		return m.asModelTypedFirst
	case modelTypedUnionValueKindModelTypedSecond:
		return m.asModelTypedSecond
	default:
		panic(
			fmt.Sprintf(
				"Unexpected value kind: %v",
				m.valueKind,
			),
		)
	}
}

// Wrap `that` as an instance of [ModelTypedUnion] based on its run-time type.
func ModelTypedUnionFromUnderlying(that IClass) *ModelTypedUnion {
	switch casted := that.(type) {
	case IModelTypedFirst:
		return NewModelTypedUnionFromModelTypedFirst(casted)
	case IModelTypedSecond:
		return NewModelTypedUnionFromModelTypedSecond(casted)
	default:
		panic(
			fmt.Sprintf(
				"Unexpected run-time type for the union ModelTypedUnion: %T",
				that,
			),
		)
	}
}

type ISomething interface {
	IClass

	StructuralProperty() *StructuralUnion;

	SetStructuralProperty(
		value *StructuralUnion,
	);

	MixedProperty() *MixedUnion;

	SetMixedProperty(
		value *MixedUnion,
	);

	ModelTypedProperty() *ModelTypedUnion;

	SetModelTypedProperty(
		value *ModelTypedUnion,
	);

	ListStructuralProperty() []*StructuralUnion;

	SetListStructuralProperty(
		value []*StructuralUnion,
	);

	ListMixedProperty() []*MixedUnion;

	SetListMixedProperty(
		value []*MixedUnion,
	);

	ListModelTypedProperty() []*ModelTypedUnion;

	SetListModelTypedProperty(
		value []*ModelTypedUnion,
	);

	TupleProperty() aascommon.Tuple3[*StructuralUnion, *MixedUnion, *ModelTypedUnion];

	SetTupleProperty(
		value aascommon.Tuple3[*StructuralUnion, *MixedUnion, *ModelTypedUnion],
	);

	OptionalStructuralProperty() *StructuralUnion;

	SetOptionalStructuralProperty(
		value *StructuralUnion,
	);

	OptionalMixedProperty() *MixedUnion;

	SetOptionalMixedProperty(
		value *MixedUnion,
	);

	OptionalModelTypedProperty() *ModelTypedUnion;

	SetOptionalModelTypedProperty(
		value *ModelTypedUnion,
	);
}

// Check whether the instance corresponds to [aastypes.ISomething]
// based on its run-time model type.
//
// The implementation uses a switch statements which is
// most probably compiled as an efficient jump table by the compiler.
func IsSomething(
	that IClass,
) (ok bool) {
	ok = that.ModelType() == ModelTypeSomething
	return
}

// Implements ISomething.
type Something struct {
	structuralProperty *StructuralUnion
	mixedProperty *MixedUnion
	modelTypedProperty *ModelTypedUnion
	listStructuralProperty []*StructuralUnion
	listMixedProperty []*MixedUnion
	listModelTypedProperty []*ModelTypedUnion
	tupleProperty aascommon.Tuple3[*StructuralUnion, *MixedUnion, *ModelTypedUnion]
	optionalStructuralProperty *StructuralUnion
	optionalMixedProperty *MixedUnion
	optionalModelTypedProperty *ModelTypedUnion
}

func (s *Something) StructuralProperty(
) *StructuralUnion {
	return s.structuralProperty
}

func (s *Something) SetStructuralProperty(
	value *StructuralUnion,
) {
	s.structuralProperty = value
}

func (s *Something) MixedProperty(
) *MixedUnion {
	return s.mixedProperty
}

func (s *Something) SetMixedProperty(
	value *MixedUnion,
) {
	s.mixedProperty = value
}

func (s *Something) ModelTypedProperty(
) *ModelTypedUnion {
	return s.modelTypedProperty
}

func (s *Something) SetModelTypedProperty(
	value *ModelTypedUnion,
) {
	s.modelTypedProperty = value
}

func (s *Something) ListStructuralProperty(
) []*StructuralUnion {
	return s.listStructuralProperty
}

func (s *Something) SetListStructuralProperty(
	value []*StructuralUnion,
) {
	s.listStructuralProperty = value
}

func (s *Something) ListMixedProperty(
) []*MixedUnion {
	return s.listMixedProperty
}

func (s *Something) SetListMixedProperty(
	value []*MixedUnion,
) {
	s.listMixedProperty = value
}

func (s *Something) ListModelTypedProperty(
) []*ModelTypedUnion {
	return s.listModelTypedProperty
}

func (s *Something) SetListModelTypedProperty(
	value []*ModelTypedUnion,
) {
	s.listModelTypedProperty = value
}

func (s *Something) TupleProperty(
) aascommon.Tuple3[*StructuralUnion, *MixedUnion, *ModelTypedUnion] {
	return s.tupleProperty
}

func (s *Something) SetTupleProperty(
	value aascommon.Tuple3[*StructuralUnion, *MixedUnion, *ModelTypedUnion],
) {
	s.tupleProperty = value
}

func (s *Something) OptionalStructuralProperty(
) *StructuralUnion {
	return s.optionalStructuralProperty
}

func (s *Something) SetOptionalStructuralProperty(
	value *StructuralUnion,
) {
	s.optionalStructuralProperty = value
}

func (s *Something) OptionalMixedProperty(
) *MixedUnion {
	return s.optionalMixedProperty
}

func (s *Something) SetOptionalMixedProperty(
	value *MixedUnion,
) {
	s.optionalMixedProperty = value
}

func (s *Something) OptionalModelTypedProperty(
) *ModelTypedUnion {
	return s.optionalModelTypedProperty
}

func (s *Something) SetOptionalModelTypedProperty(
	value *ModelTypedUnion,
) {
	s.optionalModelTypedProperty = value
}

func (s *Something) ModelType(
) ModelType {
	return ModelTypeSomething
}

// Apply the action on the instances referenced from s.
//
// If any of the actions returns abort `true`, the descent is immediately
// stopped,  and abort `true` is also returned. Otherwise, return abort `false`.
//
// We do not recurse into the referenced instances.
//
// The action is not applied on s.
func (s *Something) DescendOnce(
	action func(IClass) bool,
) (abort bool) {
	abort = action(
		s.structuralProperty.Underlying(),
	)
	if abort {
		return
	}

	abort = action(
		s.mixedProperty.Underlying(),
	)
	if abort {
		return
	}

	abort = action(
		s.modelTypedProperty.Underlying(),
	)
	if abort {
		return
	}

	for _, v := range s.listStructuralProperty {
		abort = action(v.Underlying());
		if abort {
			return
		}
	}

	for _, v1 := range s.listMixedProperty {
		abort = action(v1.Underlying());
		if abort {
			return
		}
	}

	for _, v2 := range s.listModelTypedProperty {
		abort = action(v2.Underlying());
		if abort {
			return
		}
	}

	abort = action(
		s.tupleProperty.Item1.Underlying(),
	)
	if abort {
		return
	}
	abort = action(
		s.tupleProperty.Item2.Underlying(),
	)
	if abort {
		return
	}
	abort = action(
		s.tupleProperty.Item3.Underlying(),
	)
	if abort {
		return
	}

	if s.optionalStructuralProperty != nil {
		abort = action(
			s.optionalStructuralProperty.Underlying(),
		)
		if abort {
			return
		}
	}

	if s.optionalMixedProperty != nil {
		abort = action(
			s.optionalMixedProperty.Underlying(),
		)
		if abort {
			return
		}
	}

	if s.optionalModelTypedProperty != nil {
		abort = action(
			s.optionalModelTypedProperty.Underlying(),
		)
		if abort {
			return
		}
	}

	return
}

// Apply the action recursively on the instances referenced from s.
//
// If any of the actions returns abort `true`, the descent is immediately
// stopped,  and abort `true` is also returned. Otherwise, return abort `false`.
//
// The action is not applied on s.
func (s *Something) Descend(
	action func(IClass) bool,
) (abort bool) {
	abort = action(
		s.structuralProperty.Underlying(),
	)
	if abort {
		return
	}
	abort = s.structuralProperty.Underlying().Descend(
		action,
	)
	if abort {
		return
	}

	abort = action(
		s.mixedProperty.Underlying(),
	)
	if abort {
		return
	}
	abort = s.mixedProperty.Underlying().Descend(
		action,
	)
	if abort {
		return
	}

	abort = action(
		s.modelTypedProperty.Underlying(),
	)
	if abort {
		return
	}
	abort = s.modelTypedProperty.Underlying().Descend(
		action,
	)
	if abort {
		return
	}

	for _, v := range s.listStructuralProperty {
		abort = action(v.Underlying());
		if abort {
			return
		}

		abort = v.Underlying().Descend(
			action,
		);
		if abort {
			return
		}
	}

	for _, v1 := range s.listMixedProperty {
		abort = action(v1.Underlying());
		if abort {
			return
		}

		abort = v1.Underlying().Descend(
			action,
		);
		if abort {
			return
		}
	}

	for _, v2 := range s.listModelTypedProperty {
		abort = action(v2.Underlying());
		if abort {
			return
		}

		abort = v2.Underlying().Descend(
			action,
		);
		if abort {
			return
		}
	}

	abort = action(
		s.tupleProperty.Item1.Underlying(),
	)
	if abort {
		return
	}
	abort = s.tupleProperty.Item1.Underlying().Descend(
		action,
	)
	if abort {
		return
	}
	abort = action(
		s.tupleProperty.Item2.Underlying(),
	)
	if abort {
		return
	}
	abort = s.tupleProperty.Item2.Underlying().Descend(
		action,
	)
	if abort {
		return
	}
	abort = action(
		s.tupleProperty.Item3.Underlying(),
	)
	if abort {
		return
	}
	abort = s.tupleProperty.Item3.Underlying().Descend(
		action,
	)
	if abort {
		return
	}

	if s.optionalStructuralProperty != nil {
		abort = action(
			s.optionalStructuralProperty.Underlying(),
		)
		if abort {
			return
		}
		abort = s.optionalStructuralProperty.Underlying().Descend(
			action,
		)
		if abort {
			return
		}
	}

	if s.optionalMixedProperty != nil {
		abort = action(
			s.optionalMixedProperty.Underlying(),
		)
		if abort {
			return
		}
		abort = s.optionalMixedProperty.Underlying().Descend(
			action,
		)
		if abort {
			return
		}
	}

	if s.optionalModelTypedProperty != nil {
		abort = action(
			s.optionalModelTypedProperty.Underlying(),
		)
		if abort {
			return
		}
		abort = s.optionalModelTypedProperty.Underlying().Descend(
			action,
		)
		if abort {
			return
		}
	}

	return
}

// Create a new instance of Something with
// the given properties.
func NewSomething(
	structuralProperty *StructuralUnion,
	mixedProperty *MixedUnion,
	modelTypedProperty *ModelTypedUnion,
	listStructuralProperty []*StructuralUnion,
	listMixedProperty []*MixedUnion,
	listModelTypedProperty []*ModelTypedUnion,
	tupleProperty aascommon.Tuple3[*StructuralUnion, *MixedUnion, *ModelTypedUnion],
) *Something {
	return &Something{
		structuralProperty: structuralProperty,
		mixedProperty: mixedProperty,
		modelTypedProperty: modelTypedProperty,
		listStructuralProperty: listStructuralProperty,
		listMixedProperty: listMixedProperty,
		listModelTypedProperty: listModelTypedProperty,
		tupleProperty: tupleProperty,
		optionalStructuralProperty: nil,
		optionalMixedProperty: nil,
		optionalModelTypedProperty: nil,
	}
}

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.
