// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.

/**
* Load minimal and maximal examples from an XML file.
*/

#ifndef TEST_COMMON_EXAMPLES_GUARD_
#define TEST_COMMON_EXAMPLES_GUARD_

#include <dummy/types.hpp>

namespace test {
namespace common {
namespace examples {

/**
 * Load a minimal example of IStructuralFirst by
 * de-serializing it from an XML file.
 */
std::shared_ptr<
  dummy::types::IStructuralFirst
> LoadMinStructuralFirst();

/**
 * Load a maximal example of IStructuralFirst by
 * de-serializing it from an XML file.
 */
std::shared_ptr<
  dummy::types::IStructuralFirst
> LoadMaxStructuralFirst();

/**
 * Load a minimal example of IStructuralSecond by
 * de-serializing it from an XML file.
 */
std::shared_ptr<
  dummy::types::IStructuralSecond
> LoadMinStructuralSecond();

/**
 * Load a maximal example of IStructuralSecond by
 * de-serializing it from an XML file.
 */
std::shared_ptr<
  dummy::types::IStructuralSecond
> LoadMaxStructuralSecond();

/**
 * Load a minimal example of IMixedAbstractDescendantOne by
 * de-serializing it from an XML file.
 */
std::shared_ptr<
  dummy::types::IMixedAbstractDescendantOne
> LoadMinMixedAbstractDescendantOne();

/**
 * Load a maximal example of IMixedAbstractDescendantOne by
 * de-serializing it from an XML file.
 */
std::shared_ptr<
  dummy::types::IMixedAbstractDescendantOne
> LoadMaxMixedAbstractDescendantOne();

/**
 * Load a minimal example of IMixedAbstractDescendantTwo by
 * de-serializing it from an XML file.
 */
std::shared_ptr<
  dummy::types::IMixedAbstractDescendantTwo
> LoadMinMixedAbstractDescendantTwo();

/**
 * Load a maximal example of IMixedAbstractDescendantTwo by
 * de-serializing it from an XML file.
 */
std::shared_ptr<
  dummy::types::IMixedAbstractDescendantTwo
> LoadMaxMixedAbstractDescendantTwo();

/**
 * Load a minimal example of IMixedConcreteWithDescendants by
 * de-serializing it from an XML file.
 */
std::shared_ptr<
  dummy::types::IMixedConcreteWithDescendants
> LoadMinMixedConcreteWithDescendants();

/**
 * Load a maximal example of IMixedConcreteWithDescendants by
 * de-serializing it from an XML file.
 */
std::shared_ptr<
  dummy::types::IMixedConcreteWithDescendants
> LoadMaxMixedConcreteWithDescendants();

/**
 * Load a minimal example of IMixedConcreteWithDescendantsChild by
 * de-serializing it from an XML file.
 */
std::shared_ptr<
  dummy::types::IMixedConcreteWithDescendantsChild
> LoadMinMixedConcreteWithDescendantsChild();

/**
 * Load a maximal example of IMixedConcreteWithDescendantsChild by
 * de-serializing it from an XML file.
 */
std::shared_ptr<
  dummy::types::IMixedConcreteWithDescendantsChild
> LoadMaxMixedConcreteWithDescendantsChild();

/**
 * Load a minimal example of IMixedConcreteLeaf by
 * de-serializing it from an XML file.
 */
std::shared_ptr<
  dummy::types::IMixedConcreteLeaf
> LoadMinMixedConcreteLeaf();

/**
 * Load a maximal example of IMixedConcreteLeaf by
 * de-serializing it from an XML file.
 */
std::shared_ptr<
  dummy::types::IMixedConcreteLeaf
> LoadMaxMixedConcreteLeaf();

/**
 * Load a minimal example of IModelTypedFirst by
 * de-serializing it from an XML file.
 */
std::shared_ptr<
  dummy::types::IModelTypedFirst
> LoadMinModelTypedFirst();

/**
 * Load a maximal example of IModelTypedFirst by
 * de-serializing it from an XML file.
 */
std::shared_ptr<
  dummy::types::IModelTypedFirst
> LoadMaxModelTypedFirst();

/**
 * Load a minimal example of IModelTypedSecond by
 * de-serializing it from an XML file.
 */
std::shared_ptr<
  dummy::types::IModelTypedSecond
> LoadMinModelTypedSecond();

/**
 * Load a maximal example of IModelTypedSecond by
 * de-serializing it from an XML file.
 */
std::shared_ptr<
  dummy::types::IModelTypedSecond
> LoadMaxModelTypedSecond();

/**
 * Load a minimal example of ISomething by
 * de-serializing it from an XML file.
 */
std::shared_ptr<
  dummy::types::ISomething
> LoadMinSomething();

/**
 * Load a maximal example of ISomething by
 * de-serializing it from an XML file.
 */
std::shared_ptr<
  dummy::types::ISomething
> LoadMaxSomething();

}  // namespace examples
}  // namespace common
}  // namespace test

#endif // TEST_COMMON_EXAMPLES_GUARD_

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.
