/*
 * This code has been automatically generated by aas-core-codegen.
 * Do NOT edit or append.
 */

using Aas = dummy;  // renamed
using System.Collections.Generic;  // can't alias
using System.Linq;  // can't alias

namespace dummy
{
    /// <summary>
    /// Allow for enhancing of our model classes with custom wraps.
    /// </summary>
    public static class Enhancing
    {
        public abstract class Enhanced<TEnhancement> where TEnhancement : class
        {
            // ReSharper disable once InconsistentNaming
            protected readonly TEnhancement _enhancement;

            protected Enhanced(TEnhancement enhancement)
            {
                _enhancement = enhancement;
            }

            internal TEnhancement _getEnhancement()
            {
                return _enhancement;
            }
        }

        public class EnhancedStructuralFirst<TEnhancement>
            : Enhanced<TEnhancement>, Aas.IStructuralFirst
            where TEnhancement : class
        {
            private readonly Aas.IStructuralFirst _instance;

            public EnhancedStructuralFirst(
                Aas.IStructuralFirst instance,
                TEnhancement enhancement
            ) : base(enhancement)
            {
                _instance = instance;
            }

            public string UniqueToFirst
            {
                get => _instance.UniqueToFirst;
                set => _instance.UniqueToFirst = value;
            }

            public IEnumerable<Aas.IClass> DescendOnce()
            {
                return _instance.DescendOnce();
            }

            public IEnumerable<Aas.IClass> Descend()
            {
                return _instance.Descend();
            }

            public void Accept(Aas.Visitation.IVisitor visitor)
            {
                visitor.VisitStructuralFirst(_instance);
            }

            public void Accept<TContext>(
                Visitation.IVisitorWithContext<TContext> visitor,
                TContext context
            )
            {
                visitor.VisitStructuralFirst(_instance, context);
            }

            public T Transform<T>(Visitation.ITransformer<T> transformer)
            {
                return transformer.TransformStructuralFirst(_instance);
            }

            public T Transform<TContext, T>(
                Visitation.ITransformerWithContext<TContext, T> transformer,
                TContext context
            )
            {
                return transformer.TransformStructuralFirst(_instance, context);
            }
        }

        public class EnhancedStructuralSecond<TEnhancement>
            : Enhanced<TEnhancement>, Aas.IStructuralSecond
            where TEnhancement : class
        {
            private readonly Aas.IStructuralSecond _instance;

            public EnhancedStructuralSecond(
                Aas.IStructuralSecond instance,
                TEnhancement enhancement
            ) : base(enhancement)
            {
                _instance = instance;
            }

            public string UniqueToSecond
            {
                get => _instance.UniqueToSecond;
                set => _instance.UniqueToSecond = value;
            }

            public IEnumerable<Aas.IClass> DescendOnce()
            {
                return _instance.DescendOnce();
            }

            public IEnumerable<Aas.IClass> Descend()
            {
                return _instance.Descend();
            }

            public void Accept(Aas.Visitation.IVisitor visitor)
            {
                visitor.VisitStructuralSecond(_instance);
            }

            public void Accept<TContext>(
                Visitation.IVisitorWithContext<TContext> visitor,
                TContext context
            )
            {
                visitor.VisitStructuralSecond(_instance, context);
            }

            public T Transform<T>(Visitation.ITransformer<T> transformer)
            {
                return transformer.TransformStructuralSecond(_instance);
            }

            public T Transform<TContext, T>(
                Visitation.ITransformerWithContext<TContext, T> transformer,
                TContext context
            )
            {
                return transformer.TransformStructuralSecond(_instance, context);
            }
        }

        public class EnhancedMixedAbstractDescendantOne<TEnhancement>
            : Enhanced<TEnhancement>, Aas.IMixedAbstractDescendantOne
            where TEnhancement : class
        {
            private readonly Aas.IMixedAbstractDescendantOne _instance;

            public EnhancedMixedAbstractDescendantOne(
                Aas.IMixedAbstractDescendantOne instance,
                TEnhancement enhancement
            ) : base(enhancement)
            {
                _instance = instance;
            }

            public string UniqueToAbstractDescendantOne
            {
                get => _instance.UniqueToAbstractDescendantOne;
                set => _instance.UniqueToAbstractDescendantOne = value;
            }

            public IEnumerable<Aas.IClass> DescendOnce()
            {
                return _instance.DescendOnce();
            }

            public IEnumerable<Aas.IClass> Descend()
            {
                return _instance.Descend();
            }

            public void Accept(Aas.Visitation.IVisitor visitor)
            {
                visitor.VisitMixedAbstractDescendantOne(_instance);
            }

            public void Accept<TContext>(
                Visitation.IVisitorWithContext<TContext> visitor,
                TContext context
            )
            {
                visitor.VisitMixedAbstractDescendantOne(_instance, context);
            }

            public T Transform<T>(Visitation.ITransformer<T> transformer)
            {
                return transformer.TransformMixedAbstractDescendantOne(_instance);
            }

            public T Transform<TContext, T>(
                Visitation.ITransformerWithContext<TContext, T> transformer,
                TContext context
            )
            {
                return transformer.TransformMixedAbstractDescendantOne(_instance, context);
            }
        }

        public class EnhancedMixedAbstractDescendantTwo<TEnhancement>
            : Enhanced<TEnhancement>, Aas.IMixedAbstractDescendantTwo
            where TEnhancement : class
        {
            private readonly Aas.IMixedAbstractDescendantTwo _instance;

            public EnhancedMixedAbstractDescendantTwo(
                Aas.IMixedAbstractDescendantTwo instance,
                TEnhancement enhancement
            ) : base(enhancement)
            {
                _instance = instance;
            }

            public string UniqueToAbstractDescendantTwo
            {
                get => _instance.UniqueToAbstractDescendantTwo;
                set => _instance.UniqueToAbstractDescendantTwo = value;
            }

            public IEnumerable<Aas.IClass> DescendOnce()
            {
                return _instance.DescendOnce();
            }

            public IEnumerable<Aas.IClass> Descend()
            {
                return _instance.Descend();
            }

            public void Accept(Aas.Visitation.IVisitor visitor)
            {
                visitor.VisitMixedAbstractDescendantTwo(_instance);
            }

            public void Accept<TContext>(
                Visitation.IVisitorWithContext<TContext> visitor,
                TContext context
            )
            {
                visitor.VisitMixedAbstractDescendantTwo(_instance, context);
            }

            public T Transform<T>(Visitation.ITransformer<T> transformer)
            {
                return transformer.TransformMixedAbstractDescendantTwo(_instance);
            }

            public T Transform<TContext, T>(
                Visitation.ITransformerWithContext<TContext, T> transformer,
                TContext context
            )
            {
                return transformer.TransformMixedAbstractDescendantTwo(_instance, context);
            }
        }

        public class EnhancedMixedConcreteWithDescendants<TEnhancement>
            : Enhanced<TEnhancement>, Aas.IMixedConcreteWithDescendants
            where TEnhancement : class
        {
            private readonly Aas.IMixedConcreteWithDescendants _instance;

            public EnhancedMixedConcreteWithDescendants(
                Aas.IMixedConcreteWithDescendants instance,
                TEnhancement enhancement
            ) : base(enhancement)
            {
                _instance = instance;
            }

            public string SomeBaseProperty
            {
                get => _instance.SomeBaseProperty;
                set => _instance.SomeBaseProperty = value;
            }

            public IEnumerable<Aas.IClass> DescendOnce()
            {
                return _instance.DescendOnce();
            }

            public IEnumerable<Aas.IClass> Descend()
            {
                return _instance.Descend();
            }

            public void Accept(Aas.Visitation.IVisitor visitor)
            {
                visitor.VisitMixedConcreteWithDescendants(_instance);
            }

            public void Accept<TContext>(
                Visitation.IVisitorWithContext<TContext> visitor,
                TContext context
            )
            {
                visitor.VisitMixedConcreteWithDescendants(_instance, context);
            }

            public T Transform<T>(Visitation.ITransformer<T> transformer)
            {
                return transformer.TransformMixedConcreteWithDescendants(_instance);
            }

            public T Transform<TContext, T>(
                Visitation.ITransformerWithContext<TContext, T> transformer,
                TContext context
            )
            {
                return transformer.TransformMixedConcreteWithDescendants(_instance, context);
            }
        }

        public class EnhancedMixedConcreteWithDescendantsChild<TEnhancement>
            : Enhanced<TEnhancement>, Aas.IMixedConcreteWithDescendantsChild
            where TEnhancement : class
        {
            private readonly Aas.IMixedConcreteWithDescendantsChild _instance;

            public EnhancedMixedConcreteWithDescendantsChild(
                Aas.IMixedConcreteWithDescendantsChild instance,
                TEnhancement enhancement
            ) : base(enhancement)
            {
                _instance = instance;
            }

            public string SomeBaseProperty
            {
                get => _instance.SomeBaseProperty;
                set => _instance.SomeBaseProperty = value;
            }

            public string SomeChildProperty
            {
                get => _instance.SomeChildProperty;
                set => _instance.SomeChildProperty = value;
            }

            public IEnumerable<Aas.IClass> DescendOnce()
            {
                return _instance.DescendOnce();
            }

            public IEnumerable<Aas.IClass> Descend()
            {
                return _instance.Descend();
            }

            public void Accept(Aas.Visitation.IVisitor visitor)
            {
                visitor.VisitMixedConcreteWithDescendantsChild(_instance);
            }

            public void Accept<TContext>(
                Visitation.IVisitorWithContext<TContext> visitor,
                TContext context
            )
            {
                visitor.VisitMixedConcreteWithDescendantsChild(_instance, context);
            }

            public T Transform<T>(Visitation.ITransformer<T> transformer)
            {
                return transformer.TransformMixedConcreteWithDescendantsChild(_instance);
            }

            public T Transform<TContext, T>(
                Visitation.ITransformerWithContext<TContext, T> transformer,
                TContext context
            )
            {
                return transformer.TransformMixedConcreteWithDescendantsChild(_instance, context);
            }
        }

        public class EnhancedMixedConcreteLeaf<TEnhancement>
            : Enhanced<TEnhancement>, Aas.IMixedConcreteLeaf
            where TEnhancement : class
        {
            private readonly Aas.IMixedConcreteLeaf _instance;

            public EnhancedMixedConcreteLeaf(
                Aas.IMixedConcreteLeaf instance,
                TEnhancement enhancement
            ) : base(enhancement)
            {
                _instance = instance;
            }

            public string UniqueToConcreteLeaf
            {
                get => _instance.UniqueToConcreteLeaf;
                set => _instance.UniqueToConcreteLeaf = value;
            }

            public IEnumerable<Aas.IClass> DescendOnce()
            {
                return _instance.DescendOnce();
            }

            public IEnumerable<Aas.IClass> Descend()
            {
                return _instance.Descend();
            }

            public void Accept(Aas.Visitation.IVisitor visitor)
            {
                visitor.VisitMixedConcreteLeaf(_instance);
            }

            public void Accept<TContext>(
                Visitation.IVisitorWithContext<TContext> visitor,
                TContext context
            )
            {
                visitor.VisitMixedConcreteLeaf(_instance, context);
            }

            public T Transform<T>(Visitation.ITransformer<T> transformer)
            {
                return transformer.TransformMixedConcreteLeaf(_instance);
            }

            public T Transform<TContext, T>(
                Visitation.ITransformerWithContext<TContext, T> transformer,
                TContext context
            )
            {
                return transformer.TransformMixedConcreteLeaf(_instance, context);
            }
        }

        public class EnhancedModelTypedFirst<TEnhancement>
            : Enhanced<TEnhancement>, Aas.IModelTypedFirst
            where TEnhancement : class
        {
            private readonly Aas.IModelTypedFirst _instance;

            public EnhancedModelTypedFirst(
                Aas.IModelTypedFirst instance,
                TEnhancement enhancement
            ) : base(enhancement)
            {
                _instance = instance;
            }

            public string SomeProperty
            {
                get => _instance.SomeProperty;
                set => _instance.SomeProperty = value;
            }

            public IEnumerable<Aas.IClass> DescendOnce()
            {
                return _instance.DescendOnce();
            }

            public IEnumerable<Aas.IClass> Descend()
            {
                return _instance.Descend();
            }

            public void Accept(Aas.Visitation.IVisitor visitor)
            {
                visitor.VisitModelTypedFirst(_instance);
            }

            public void Accept<TContext>(
                Visitation.IVisitorWithContext<TContext> visitor,
                TContext context
            )
            {
                visitor.VisitModelTypedFirst(_instance, context);
            }

            public T Transform<T>(Visitation.ITransformer<T> transformer)
            {
                return transformer.TransformModelTypedFirst(_instance);
            }

            public T Transform<TContext, T>(
                Visitation.ITransformerWithContext<TContext, T> transformer,
                TContext context
            )
            {
                return transformer.TransformModelTypedFirst(_instance, context);
            }
        }

        public class EnhancedModelTypedSecond<TEnhancement>
            : Enhanced<TEnhancement>, Aas.IModelTypedSecond
            where TEnhancement : class
        {
            private readonly Aas.IModelTypedSecond _instance;

            public EnhancedModelTypedSecond(
                Aas.IModelTypedSecond instance,
                TEnhancement enhancement
            ) : base(enhancement)
            {
                _instance = instance;
            }

            public string SomeProperty
            {
                get => _instance.SomeProperty;
                set => _instance.SomeProperty = value;
            }

            public IEnumerable<Aas.IClass> DescendOnce()
            {
                return _instance.DescendOnce();
            }

            public IEnumerable<Aas.IClass> Descend()
            {
                return _instance.Descend();
            }

            public void Accept(Aas.Visitation.IVisitor visitor)
            {
                visitor.VisitModelTypedSecond(_instance);
            }

            public void Accept<TContext>(
                Visitation.IVisitorWithContext<TContext> visitor,
                TContext context
            )
            {
                visitor.VisitModelTypedSecond(_instance, context);
            }

            public T Transform<T>(Visitation.ITransformer<T> transformer)
            {
                return transformer.TransformModelTypedSecond(_instance);
            }

            public T Transform<TContext, T>(
                Visitation.ITransformerWithContext<TContext, T> transformer,
                TContext context
            )
            {
                return transformer.TransformModelTypedSecond(_instance, context);
            }
        }

        public class EnhancedSomething<TEnhancement>
            : Enhanced<TEnhancement>, Aas.ISomething
            where TEnhancement : class
        {
            private readonly Aas.ISomething _instance;

            public EnhancedSomething(
                Aas.ISomething instance,
                TEnhancement enhancement
            ) : base(enhancement)
            {
                _instance = instance;
            }

            public StructuralUnion StructuralProperty
            {
                get => _instance.StructuralProperty;
                set => _instance.StructuralProperty = value;
            }

            public MixedUnion MixedProperty
            {
                get => _instance.MixedProperty;
                set => _instance.MixedProperty = value;
            }

            public ModelTypedUnion ModelTypedProperty
            {
                get => _instance.ModelTypedProperty;
                set => _instance.ModelTypedProperty = value;
            }

            public List<StructuralUnion> ListStructuralProperty
            {
                get => _instance.ListStructuralProperty;
                set => _instance.ListStructuralProperty = value;
            }

            public List<MixedUnion> ListMixedProperty
            {
                get => _instance.ListMixedProperty;
                set => _instance.ListMixedProperty = value;
            }

            public List<ModelTypedUnion> ListModelTypedProperty
            {
                get => _instance.ListModelTypedProperty;
                set => _instance.ListModelTypedProperty = value;
            }

            public (StructuralUnion, MixedUnion, ModelTypedUnion) TupleProperty
            {
                get => _instance.TupleProperty;
                set => _instance.TupleProperty = value;
            }

            public StructuralUnion? OptionalStructuralProperty
            {
                get => _instance.OptionalStructuralProperty;
                set => _instance.OptionalStructuralProperty = value;
            }

            public MixedUnion? OptionalMixedProperty
            {
                get => _instance.OptionalMixedProperty;
                set => _instance.OptionalMixedProperty = value;
            }

            public ModelTypedUnion? OptionalModelTypedProperty
            {
                get => _instance.OptionalModelTypedProperty;
                set => _instance.OptionalModelTypedProperty = value;
            }

            public IEnumerable<Aas.IClass> DescendOnce()
            {
                return _instance.DescendOnce();
            }

            public IEnumerable<Aas.IClass> Descend()
            {
                return _instance.Descend();
            }

            public void Accept(Aas.Visitation.IVisitor visitor)
            {
                visitor.VisitSomething(_instance);
            }

            public void Accept<TContext>(
                Visitation.IVisitorWithContext<TContext> visitor,
                TContext context
            )
            {
                visitor.VisitSomething(_instance, context);
            }

            public T Transform<T>(Visitation.ITransformer<T> transformer)
            {
                return transformer.TransformSomething(_instance);
            }

            public T Transform<TContext, T>(
                Visitation.ITransformerWithContext<TContext, T> transformer,
                TContext context
            )
            {
                return transformer.TransformSomething(_instance, context);
            }
        }

        internal class Wrapper<TEnhancement>
            : Aas.Visitation.AbstractTransformer<Aas.IClass>
            where TEnhancement : class
        {
            private readonly System.Func<Aas.IClass, TEnhancement?> _enhancementFactory;

            internal Wrapper(
                System.Func<Aas.IClass, TEnhancement?> enhancementFactory
            )
            {
                _enhancementFactory = enhancementFactory;
            }

            public override Aas.IClass TransformStructuralFirst(
                Aas.IStructuralFirst that
            )
            {
                if (that is Enhanced<TEnhancement>)
                {
                    throw new System.ArgumentException(
                        $"The instance has been already enhanced: {that}"
                    );
                }

                var enhancement = _enhancementFactory(that);
                return (enhancement == null)
                    ? that
                    : new EnhancedStructuralFirst<TEnhancement>(
                        that,
                        enhancement
                    );
            }

            public override Aas.IClass TransformStructuralSecond(
                Aas.IStructuralSecond that
            )
            {
                if (that is Enhanced<TEnhancement>)
                {
                    throw new System.ArgumentException(
                        $"The instance has been already enhanced: {that}"
                    );
                }

                var enhancement = _enhancementFactory(that);
                return (enhancement == null)
                    ? that
                    : new EnhancedStructuralSecond<TEnhancement>(
                        that,
                        enhancement
                    );
            }

            public override Aas.IClass TransformMixedAbstractDescendantOne(
                Aas.IMixedAbstractDescendantOne that
            )
            {
                if (that is Enhanced<TEnhancement>)
                {
                    throw new System.ArgumentException(
                        $"The instance has been already enhanced: {that}"
                    );
                }

                var enhancement = _enhancementFactory(that);
                return (enhancement == null)
                    ? that
                    : new EnhancedMixedAbstractDescendantOne<TEnhancement>(
                        that,
                        enhancement
                    );
            }

            public override Aas.IClass TransformMixedAbstractDescendantTwo(
                Aas.IMixedAbstractDescendantTwo that
            )
            {
                if (that is Enhanced<TEnhancement>)
                {
                    throw new System.ArgumentException(
                        $"The instance has been already enhanced: {that}"
                    );
                }

                var enhancement = _enhancementFactory(that);
                return (enhancement == null)
                    ? that
                    : new EnhancedMixedAbstractDescendantTwo<TEnhancement>(
                        that,
                        enhancement
                    );
            }

            public override Aas.IClass TransformMixedConcreteWithDescendants(
                Aas.IMixedConcreteWithDescendants that
            )
            {
                if (that is Enhanced<TEnhancement>)
                {
                    throw new System.ArgumentException(
                        $"The instance has been already enhanced: {that}"
                    );
                }

                var enhancement = _enhancementFactory(that);
                return (enhancement == null)
                    ? that
                    : new EnhancedMixedConcreteWithDescendants<TEnhancement>(
                        that,
                        enhancement
                    );
            }

            public override Aas.IClass TransformMixedConcreteWithDescendantsChild(
                Aas.IMixedConcreteWithDescendantsChild that
            )
            {
                if (that is Enhanced<TEnhancement>)
                {
                    throw new System.ArgumentException(
                        $"The instance has been already enhanced: {that}"
                    );
                }

                var enhancement = _enhancementFactory(that);
                return (enhancement == null)
                    ? that
                    : new EnhancedMixedConcreteWithDescendantsChild<TEnhancement>(
                        that,
                        enhancement
                    );
            }

            public override Aas.IClass TransformMixedConcreteLeaf(
                Aas.IMixedConcreteLeaf that
            )
            {
                if (that is Enhanced<TEnhancement>)
                {
                    throw new System.ArgumentException(
                        $"The instance has been already enhanced: {that}"
                    );
                }

                var enhancement = _enhancementFactory(that);
                return (enhancement == null)
                    ? that
                    : new EnhancedMixedConcreteLeaf<TEnhancement>(
                        that,
                        enhancement
                    );
            }

            public override Aas.IClass TransformModelTypedFirst(
                Aas.IModelTypedFirst that
            )
            {
                if (that is Enhanced<TEnhancement>)
                {
                    throw new System.ArgumentException(
                        $"The instance has been already enhanced: {that}"
                    );
                }

                var enhancement = _enhancementFactory(that);
                return (enhancement == null)
                    ? that
                    : new EnhancedModelTypedFirst<TEnhancement>(
                        that,
                        enhancement
                    );
            }

            public override Aas.IClass TransformModelTypedSecond(
                Aas.IModelTypedSecond that
            )
            {
                if (that is Enhanced<TEnhancement>)
                {
                    throw new System.ArgumentException(
                        $"The instance has been already enhanced: {that}"
                    );
                }

                var enhancement = _enhancementFactory(that);
                return (enhancement == null)
                    ? that
                    : new EnhancedModelTypedSecond<TEnhancement>(
                        that,
                        enhancement
                    );
            }

            public override Aas.IClass TransformSomething(
                Aas.ISomething that
            )
            {
                if (that is Enhanced<TEnhancement>)
                {
                    throw new System.ArgumentException(
                        $"The instance has been already enhanced: {that}"
                    );
                }

                that.StructuralProperty = Aas.StructuralUnion.FromUnderlying(
                    Transform(that.StructuralProperty.Underlying));

                that.MixedProperty = Aas.MixedUnion.FromUnderlying(
                    Transform(that.MixedProperty.Underlying));

                that.ModelTypedProperty = Aas.ModelTypedUnion.FromUnderlying(
                    Transform(that.ModelTypedProperty.Underlying));

                that.ListStructuralProperty = (
                    that.ListStructuralProperty
                    .Select(
                        (item) => Aas.StructuralUnion.FromUnderlying(
                            Transform(item.Underlying))
                    )
                ).ToList();

                that.ListMixedProperty = (
                    that.ListMixedProperty
                    .Select(
                        (item) => Aas.MixedUnion.FromUnderlying(
                            Transform(item.Underlying))
                    )
                ).ToList();

                that.ListModelTypedProperty = (
                    that.ListModelTypedProperty
                    .Select(
                        (item) => Aas.ModelTypedUnion.FromUnderlying(
                            Transform(item.Underlying))
                    )
                ).ToList();

                var castedTupleProperty0 = Aas.StructuralUnion.FromUnderlying(
                    Transform(that.TupleProperty.Item1.Underlying));

                var castedTupleProperty1 = Aas.MixedUnion.FromUnderlying(
                    Transform(that.TupleProperty.Item2.Underlying));

                var castedTupleProperty2 = Aas.ModelTypedUnion.FromUnderlying(
                    Transform(that.TupleProperty.Item3.Underlying));
                that.TupleProperty = (
                    castedTupleProperty0,
                    castedTupleProperty1,
                    castedTupleProperty2
                );

                if (that.OptionalStructuralProperty != null)
                {
                    that.OptionalStructuralProperty = Aas.StructuralUnion.FromUnderlying(
                        Transform(that.OptionalStructuralProperty.Underlying));
                }

                if (that.OptionalMixedProperty != null)
                {
                    that.OptionalMixedProperty = Aas.MixedUnion.FromUnderlying(
                        Transform(that.OptionalMixedProperty.Underlying));
                }

                if (that.OptionalModelTypedProperty != null)
                {
                    that.OptionalModelTypedProperty = Aas.ModelTypedUnion.FromUnderlying(
                        Transform(that.OptionalModelTypedProperty.Underlying));
                }

                var enhancement = _enhancementFactory(that);
                return (enhancement == null)
                    ? that
                    : new EnhancedSomething<TEnhancement>(
                        that,
                        enhancement
                    );
            }
        }

        /// <summary>
        /// Unwrap enhancements from the wrapped instances.
        /// </summary>
        /// <typeparam name="TEnhancement">type of the enhancement</typeparam>
        public class Unwrapper<TEnhancement> where TEnhancement : class
        {
            /// <summary>
            /// Unwrap the given model instance.
            /// </summary>
            /// <param name="that">model instance to be unwrapped</param>
            /// <returns>
            /// Enhancement, or <c>null</c> if <paramref name="that" />
            /// has not been wrapped yet.
            /// </returns>
            public TEnhancement? Unwrap(Aas.IClass that)
            {
                // ReSharper disable once SuspiciousTypeConversion.Global
                var enhanced = that as Enhanced<TEnhancement>;
                return enhanced?._getEnhancement();
            }

            /// <summary>
            /// Unwrap the given model instance.
            /// </summary>
            /// <param name="that">model instance to be unwrapped</param>
            /// <returns>
            /// Enhancement wrapped around <paramref name="that" />
            /// </returns>
            /// <exception cref="System.ArgumentException">
            /// Thrown when <paramref name="that" /> has not been wrapped yet
            /// </exception>
            public TEnhancement MustUnwrap(Aas.IClass that)
            {
                return Unwrap(that) ?? throw new System.ArgumentException(
                    $"Expected the instance to have been wrapped, but it was not: {that}"
                );
            }
        }  // public class Unwrapper

        /// <summary>
        /// Wrap and unwrap the instances of model classes with enhancement.
        /// </summary>
        /// <typeparam name="TEnhancement">type of the enhancement</typeparam>
        public class Enhancer<TEnhancement>
            : Unwrapper<TEnhancement>
            where TEnhancement : class
        {
            private readonly Wrapper<TEnhancement> _wrapper;

            /// <param name="enhancementFactory">
            /// <para>how to enhance the instances.</para>
            ///
            /// <para>If it returns <c>null</c>, the instance will not be wrapped. However,
            /// the wrapping will continue recursively.</para>
            ///</param>
            public Enhancer(
                System.Func<Aas.IClass, TEnhancement?> enhancementFactory
            )
            {
                _wrapper = new Wrapper<TEnhancement>(enhancementFactory);
            }

            /// <summary>
            /// Wrap the instance with an enhancement.
            /// </summary>
            /// <remarks>
            /// Double wraps are not allowed to prevent runtime leakage.
            ///
            /// If you use references to the instance objects, you have to update them
            /// after the wrapping, as the wrapping is recursive.
            /// </remarks>
            /// <param name="that">model instance to be wrapped</param>
            /// <returns>
            /// <paramref name="that" /> instance wrapped recursively with enhancements
            /// </returns>
            /// <exception cref="System.ArgumentException">
            /// Thrown when <paramref name="that" /> has been already wrapped
            /// </exception>
            public Aas.IClass Wrap(
                Aas.IClass that
            )
            {
                var wrapped = _wrapper.Transform(that);
                return (
                    wrapped
                ) ?? throw new System.InvalidOperationException(
                    "Expected the wrapped instance to be an instance of IClass, " +
                    $"but got: {wrapped}"
                );
            }
        }  // public class Enhancer
    }  // public static class Enhancing
}  // namespace dummy

/*
 * This code has been automatically generated by aas-core-codegen.
 * Do NOT edit or append.
 */
