/*
 * This code has been automatically generated by aas-core-codegen.
 * Do NOT edit or append.
 */

using Aas = dummy;  // renamed
using EnumMemberAttribute = System.Runtime.Serialization.EnumMemberAttribute;

using System.Collections.Generic;  // can't alias

namespace dummy
{
    /// <summary>
    /// Represent a general class of an AAS model.
    /// </summary>
    public interface IClass
    {
        /// <summary>
        /// Iterate over all the class instances referenced from this instance
        /// without further recursion.
        /// </summary>
        public IEnumerable<IClass> DescendOnce();

        /// <summary>
        /// Iterate recursively over all the class instances referenced from this instance.
        /// </summary>
        public IEnumerable<IClass> Descend();

        /// <summary>
        /// Accept the <paramref name="visitor" /> to visit this instance
        /// for double dispatch.
        /// </summary>
        public void Accept(Visitation.IVisitor visitor);

        /// <summary>
        /// Accept the visitor to visit this instance for double dispatch
        /// with the <paramref name="context" />.
        /// </summary>
        public void Accept<TContext>(
            Visitation.IVisitorWithContext<TContext> visitor,
            TContext context);

        /// <summary>
        /// Accept the <paramref name="transformer" /> to transform this instance
        /// for double dispatch.
        /// </summary>
        public T Transform<T>(Visitation.ITransformer<T> transformer);

        /// <summary>
        /// Accept the <paramref name="transformer" /> to visit this instance
        /// for double dispatch with the <paramref name="context" />.
        /// </summary>
        public T Transform<TContext, T>(
            Visitation.ITransformerWithContext<TContext, T> transformer,
            TContext context);
    }

    public interface IStructuralFirst : IClass
    {
        public string UniqueToFirst { get; set; }
    }

    public class StructuralFirst : IStructuralFirst
    {
        public string UniqueToFirst { get; set; }

        /// <summary>
        /// Iterate over all the class instances referenced from this instance
        /// without further recursion.
        /// </summary>
        public IEnumerable<IClass> DescendOnce()
        {
            // No descendable properties
            yield break;
        }

        /// <summary>
        /// Iterate recursively over all the class instances referenced from this instance.
        /// </summary>
        public IEnumerable<IClass> Descend()
        {
            // No descendable properties
            yield break;
        }

        /// <summary>
        /// Accept the <paramref name="visitor" /> to visit this instance
        /// for double dispatch.
        /// </summary>
        public void Accept(Visitation.IVisitor visitor)
        {
            visitor.VisitStructuralFirst(this);
        }

        /// <summary>
        /// Accept the visitor to visit this instance for double dispatch
        /// with the <paramref name="context" />.
        /// </summary>
        public void Accept<TContext>(
            Visitation.IVisitorWithContext<TContext> visitor,
            TContext context)
        {
            visitor.VisitStructuralFirst(this, context);
        }

        /// <summary>
        /// Accept the <paramref name="transformer" /> to transform this instance
        /// for double dispatch.
        /// </summary>
        public T Transform<T>(Visitation.ITransformer<T> transformer)
        {
            return transformer.TransformStructuralFirst(this);
        }

        /// <summary>
        /// Accept the <paramref name="transformer" /> to visit this instance
        /// for double dispatch with the <paramref name="context" />.
        /// </summary>
        public T Transform<TContext, T>(
            Visitation.ITransformerWithContext<TContext, T> transformer,
            TContext context)
        {
            return transformer.TransformStructuralFirst(this, context);
        }

        public StructuralFirst(string uniqueToFirst)
        {
            UniqueToFirst = uniqueToFirst;
        }
    }

    public interface IStructuralSecond : IClass
    {
        public string UniqueToSecond { get; set; }
    }

    public class StructuralSecond : IStructuralSecond
    {
        public string UniqueToSecond { get; set; }

        /// <summary>
        /// Iterate over all the class instances referenced from this instance
        /// without further recursion.
        /// </summary>
        public IEnumerable<IClass> DescendOnce()
        {
            // No descendable properties
            yield break;
        }

        /// <summary>
        /// Iterate recursively over all the class instances referenced from this instance.
        /// </summary>
        public IEnumerable<IClass> Descend()
        {
            // No descendable properties
            yield break;
        }

        /// <summary>
        /// Accept the <paramref name="visitor" /> to visit this instance
        /// for double dispatch.
        /// </summary>
        public void Accept(Visitation.IVisitor visitor)
        {
            visitor.VisitStructuralSecond(this);
        }

        /// <summary>
        /// Accept the visitor to visit this instance for double dispatch
        /// with the <paramref name="context" />.
        /// </summary>
        public void Accept<TContext>(
            Visitation.IVisitorWithContext<TContext> visitor,
            TContext context)
        {
            visitor.VisitStructuralSecond(this, context);
        }

        /// <summary>
        /// Accept the <paramref name="transformer" /> to transform this instance
        /// for double dispatch.
        /// </summary>
        public T Transform<T>(Visitation.ITransformer<T> transformer)
        {
            return transformer.TransformStructuralSecond(this);
        }

        /// <summary>
        /// Accept the <paramref name="transformer" /> to visit this instance
        /// for double dispatch with the <paramref name="context" />.
        /// </summary>
        public T Transform<TContext, T>(
            Visitation.ITransformerWithContext<TContext, T> transformer,
            TContext context)
        {
            return transformer.TransformStructuralSecond(this, context);
        }

        public StructuralSecond(string uniqueToSecond)
        {
            UniqueToSecond = uniqueToSecond;
        }
    }

    /// <summary>
    /// Represent a union of <see cref="IStructuralFirst" /> and <see cref="IStructuralSecond" />.
    /// </summary>
    public class StructuralUnion
    {
        private enum ValueKind
        {
            StructuralFirst,
            StructuralSecond
        }

        private readonly ValueKind _valueKind;
        private readonly IStructuralFirst? _asStructuralFirst;
        private readonly IStructuralSecond? _asStructuralSecond;

        private StructuralUnion(
            ValueKind valueKind,
            IStructuralFirst? asStructuralFirst,
            IStructuralSecond? asStructuralSecond)
        {
            _valueKind = valueKind;
            _asStructuralFirst = asStructuralFirst;
            _asStructuralSecond = asStructuralSecond;
        }

        /// <summary>
        /// Get the underlying instance regardless of the concrete case.
        /// </summary>
        public IClass Underlying =>
            _valueKind switch
            {
                ValueKind.StructuralFirst => _asStructuralFirst
                    ?? throw new System.InvalidOperationException(
                        "Unexpected null _asStructuralFirst"),
                ValueKind.StructuralSecond => _asStructuralSecond
                    ?? throw new System.InvalidOperationException(
                        "Unexpected null _asStructuralSecond"),
                _ => throw new System.InvalidOperationException(
                    $"Unexpected value kind: {_valueKind}")
            };

        /// <summary>
        /// Wrap <paramref name="that" /> as an instance of StructuralUnion.
        /// </summary>
        public static StructuralUnion FromStructuralFirst(IStructuralFirst that)
        {
            return new StructuralUnion(
                ValueKind.StructuralFirst,
                that,
                null);
        }

        /// <summary>
        /// Wrap <paramref name="that" /> as an instance of StructuralUnion.
        /// </summary>
        public static StructuralUnion FromStructuralSecond(IStructuralSecond that)
        {
            return new StructuralUnion(
                ValueKind.StructuralSecond,
                null,
                that);
        }

        /// <summary>
        /// Wrap <paramref name="that" /> as an instance of StructuralUnion based on
        /// its run-time type.
        /// </summary>
        public static StructuralUnion FromUnderlying(IClass that)
        {
            switch (that)
            {
                case IStructuralFirst casted:
                    return FromStructuralFirst(casted);
                case IStructuralSecond casted:
                    return FromStructuralSecond(casted);
                default:
                    throw new System.ArgumentException(
                        $"Unexpected run-time type for the union StructuralUnion: " +
                        $"{that.GetType()}");
            }
        }
    }

    public interface IMixedAbstractMember : IClass
    {
        // Intentionally empty.
    }

    public interface IMixedAbstractDescendantOne : IMixedAbstractMember
    {
        public string UniqueToAbstractDescendantOne { get; set; }
    }

    public class MixedAbstractDescendantOne : IMixedAbstractDescendantOne
    {
        public string UniqueToAbstractDescendantOne { get; set; }

        /// <summary>
        /// Iterate over all the class instances referenced from this instance
        /// without further recursion.
        /// </summary>
        public IEnumerable<IClass> DescendOnce()
        {
            // No descendable properties
            yield break;
        }

        /// <summary>
        /// Iterate recursively over all the class instances referenced from this instance.
        /// </summary>
        public IEnumerable<IClass> Descend()
        {
            // No descendable properties
            yield break;
        }

        /// <summary>
        /// Accept the <paramref name="visitor" /> to visit this instance
        /// for double dispatch.
        /// </summary>
        public void Accept(Visitation.IVisitor visitor)
        {
            visitor.VisitMixedAbstractDescendantOne(this);
        }

        /// <summary>
        /// Accept the visitor to visit this instance for double dispatch
        /// with the <paramref name="context" />.
        /// </summary>
        public void Accept<TContext>(
            Visitation.IVisitorWithContext<TContext> visitor,
            TContext context)
        {
            visitor.VisitMixedAbstractDescendantOne(this, context);
        }

        /// <summary>
        /// Accept the <paramref name="transformer" /> to transform this instance
        /// for double dispatch.
        /// </summary>
        public T Transform<T>(Visitation.ITransformer<T> transformer)
        {
            return transformer.TransformMixedAbstractDescendantOne(this);
        }

        /// <summary>
        /// Accept the <paramref name="transformer" /> to visit this instance
        /// for double dispatch with the <paramref name="context" />.
        /// </summary>
        public T Transform<TContext, T>(
            Visitation.ITransformerWithContext<TContext, T> transformer,
            TContext context)
        {
            return transformer.TransformMixedAbstractDescendantOne(this, context);
        }

        public MixedAbstractDescendantOne(string uniqueToAbstractDescendantOne)
        {
            UniqueToAbstractDescendantOne = uniqueToAbstractDescendantOne;
        }
    }

    public interface IMixedAbstractDescendantTwo : IMixedAbstractMember
    {
        public string UniqueToAbstractDescendantTwo { get; set; }
    }

    public class MixedAbstractDescendantTwo : IMixedAbstractDescendantTwo
    {
        public string UniqueToAbstractDescendantTwo { get; set; }

        /// <summary>
        /// Iterate over all the class instances referenced from this instance
        /// without further recursion.
        /// </summary>
        public IEnumerable<IClass> DescendOnce()
        {
            // No descendable properties
            yield break;
        }

        /// <summary>
        /// Iterate recursively over all the class instances referenced from this instance.
        /// </summary>
        public IEnumerable<IClass> Descend()
        {
            // No descendable properties
            yield break;
        }

        /// <summary>
        /// Accept the <paramref name="visitor" /> to visit this instance
        /// for double dispatch.
        /// </summary>
        public void Accept(Visitation.IVisitor visitor)
        {
            visitor.VisitMixedAbstractDescendantTwo(this);
        }

        /// <summary>
        /// Accept the visitor to visit this instance for double dispatch
        /// with the <paramref name="context" />.
        /// </summary>
        public void Accept<TContext>(
            Visitation.IVisitorWithContext<TContext> visitor,
            TContext context)
        {
            visitor.VisitMixedAbstractDescendantTwo(this, context);
        }

        /// <summary>
        /// Accept the <paramref name="transformer" /> to transform this instance
        /// for double dispatch.
        /// </summary>
        public T Transform<T>(Visitation.ITransformer<T> transformer)
        {
            return transformer.TransformMixedAbstractDescendantTwo(this);
        }

        /// <summary>
        /// Accept the <paramref name="transformer" /> to visit this instance
        /// for double dispatch with the <paramref name="context" />.
        /// </summary>
        public T Transform<TContext, T>(
            Visitation.ITransformerWithContext<TContext, T> transformer,
            TContext context)
        {
            return transformer.TransformMixedAbstractDescendantTwo(this, context);
        }

        public MixedAbstractDescendantTwo(string uniqueToAbstractDescendantTwo)
        {
            UniqueToAbstractDescendantTwo = uniqueToAbstractDescendantTwo;
        }
    }

    public interface IMixedConcreteWithDescendants : IClass
    {
        public string SomeBaseProperty { get; set; }
    }

    public class MixedConcreteWithDescendants : IMixedConcreteWithDescendants
    {
        public string SomeBaseProperty { get; set; }

        /// <summary>
        /// Iterate over all the class instances referenced from this instance
        /// without further recursion.
        /// </summary>
        public IEnumerable<IClass> DescendOnce()
        {
            // No descendable properties
            yield break;
        }

        /// <summary>
        /// Iterate recursively over all the class instances referenced from this instance.
        /// </summary>
        public IEnumerable<IClass> Descend()
        {
            // No descendable properties
            yield break;
        }

        /// <summary>
        /// Accept the <paramref name="visitor" /> to visit this instance
        /// for double dispatch.
        /// </summary>
        public void Accept(Visitation.IVisitor visitor)
        {
            visitor.VisitMixedConcreteWithDescendants(this);
        }

        /// <summary>
        /// Accept the visitor to visit this instance for double dispatch
        /// with the <paramref name="context" />.
        /// </summary>
        public void Accept<TContext>(
            Visitation.IVisitorWithContext<TContext> visitor,
            TContext context)
        {
            visitor.VisitMixedConcreteWithDescendants(this, context);
        }

        /// <summary>
        /// Accept the <paramref name="transformer" /> to transform this instance
        /// for double dispatch.
        /// </summary>
        public T Transform<T>(Visitation.ITransformer<T> transformer)
        {
            return transformer.TransformMixedConcreteWithDescendants(this);
        }

        /// <summary>
        /// Accept the <paramref name="transformer" /> to visit this instance
        /// for double dispatch with the <paramref name="context" />.
        /// </summary>
        public T Transform<TContext, T>(
            Visitation.ITransformerWithContext<TContext, T> transformer,
            TContext context)
        {
            return transformer.TransformMixedConcreteWithDescendants(this, context);
        }

        public MixedConcreteWithDescendants(string someBaseProperty)
        {
            SomeBaseProperty = someBaseProperty;
        }
    }

    public interface IMixedConcreteWithDescendantsChild : IMixedConcreteWithDescendants
    {
        public string SomeChildProperty { get; set; }
    }

    public class MixedConcreteWithDescendantsChild : IMixedConcreteWithDescendantsChild
    {
        public string SomeBaseProperty { get; set; }

        public string SomeChildProperty { get; set; }

        /// <summary>
        /// Iterate over all the class instances referenced from this instance
        /// without further recursion.
        /// </summary>
        public IEnumerable<IClass> DescendOnce()
        {
            // No descendable properties
            yield break;
        }

        /// <summary>
        /// Iterate recursively over all the class instances referenced from this instance.
        /// </summary>
        public IEnumerable<IClass> Descend()
        {
            // No descendable properties
            yield break;
        }

        /// <summary>
        /// Accept the <paramref name="visitor" /> to visit this instance
        /// for double dispatch.
        /// </summary>
        public void Accept(Visitation.IVisitor visitor)
        {
            visitor.VisitMixedConcreteWithDescendantsChild(this);
        }

        /// <summary>
        /// Accept the visitor to visit this instance for double dispatch
        /// with the <paramref name="context" />.
        /// </summary>
        public void Accept<TContext>(
            Visitation.IVisitorWithContext<TContext> visitor,
            TContext context)
        {
            visitor.VisitMixedConcreteWithDescendantsChild(this, context);
        }

        /// <summary>
        /// Accept the <paramref name="transformer" /> to transform this instance
        /// for double dispatch.
        /// </summary>
        public T Transform<T>(Visitation.ITransformer<T> transformer)
        {
            return transformer.TransformMixedConcreteWithDescendantsChild(this);
        }

        /// <summary>
        /// Accept the <paramref name="transformer" /> to visit this instance
        /// for double dispatch with the <paramref name="context" />.
        /// </summary>
        public T Transform<TContext, T>(
            Visitation.ITransformerWithContext<TContext, T> transformer,
            TContext context)
        {
            return transformer.TransformMixedConcreteWithDescendantsChild(this, context);
        }

        public MixedConcreteWithDescendantsChild(
            string someBaseProperty,
            string someChildProperty)
        {
            SomeBaseProperty = someBaseProperty;
            SomeChildProperty = someChildProperty;
        }
    }

    public interface IMixedConcreteLeaf : IClass
    {
        public string UniqueToConcreteLeaf { get; set; }
    }

    public class MixedConcreteLeaf : IMixedConcreteLeaf
    {
        public string UniqueToConcreteLeaf { get; set; }

        /// <summary>
        /// Iterate over all the class instances referenced from this instance
        /// without further recursion.
        /// </summary>
        public IEnumerable<IClass> DescendOnce()
        {
            // No descendable properties
            yield break;
        }

        /// <summary>
        /// Iterate recursively over all the class instances referenced from this instance.
        /// </summary>
        public IEnumerable<IClass> Descend()
        {
            // No descendable properties
            yield break;
        }

        /// <summary>
        /// Accept the <paramref name="visitor" /> to visit this instance
        /// for double dispatch.
        /// </summary>
        public void Accept(Visitation.IVisitor visitor)
        {
            visitor.VisitMixedConcreteLeaf(this);
        }

        /// <summary>
        /// Accept the visitor to visit this instance for double dispatch
        /// with the <paramref name="context" />.
        /// </summary>
        public void Accept<TContext>(
            Visitation.IVisitorWithContext<TContext> visitor,
            TContext context)
        {
            visitor.VisitMixedConcreteLeaf(this, context);
        }

        /// <summary>
        /// Accept the <paramref name="transformer" /> to transform this instance
        /// for double dispatch.
        /// </summary>
        public T Transform<T>(Visitation.ITransformer<T> transformer)
        {
            return transformer.TransformMixedConcreteLeaf(this);
        }

        /// <summary>
        /// Accept the <paramref name="transformer" /> to visit this instance
        /// for double dispatch with the <paramref name="context" />.
        /// </summary>
        public T Transform<TContext, T>(
            Visitation.ITransformerWithContext<TContext, T> transformer,
            TContext context)
        {
            return transformer.TransformMixedConcreteLeaf(this, context);
        }

        public MixedConcreteLeaf(string uniqueToConcreteLeaf)
        {
            UniqueToConcreteLeaf = uniqueToConcreteLeaf;
        }
    }

    /// <summary>
    /// Represent a union of <see cref="IMixedAbstractDescendantOne" />, <see cref="IMixedAbstractDescendantTwo" />, <see cref="IMixedConcreteWithDescendantsChild" />, <see cref="IMixedConcreteWithDescendants" /> and <see cref="IMixedConcreteLeaf" />.
    /// </summary>
    public class MixedUnion
    {
        private enum ValueKind
        {
            MixedAbstractDescendantOne,
            MixedAbstractDescendantTwo,
            MixedConcreteWithDescendantsChild,
            MixedConcreteWithDescendants,
            MixedConcreteLeaf
        }

        private readonly ValueKind _valueKind;
        private readonly IMixedAbstractDescendantOne? _asMixedAbstractDescendantOne;
        private readonly IMixedAbstractDescendantTwo? _asMixedAbstractDescendantTwo;
        private readonly IMixedConcreteWithDescendantsChild? _asMixedConcreteWithDescendantsChild;
        private readonly IMixedConcreteWithDescendants? _asMixedConcreteWithDescendants;
        private readonly IMixedConcreteLeaf? _asMixedConcreteLeaf;

        private MixedUnion(
            ValueKind valueKind,
            IMixedAbstractDescendantOne? asMixedAbstractDescendantOne,
            IMixedAbstractDescendantTwo? asMixedAbstractDescendantTwo,
            IMixedConcreteWithDescendantsChild? asMixedConcreteWithDescendantsChild,
            IMixedConcreteWithDescendants? asMixedConcreteWithDescendants,
            IMixedConcreteLeaf? asMixedConcreteLeaf)
        {
            _valueKind = valueKind;
            _asMixedAbstractDescendantOne = asMixedAbstractDescendantOne;
            _asMixedAbstractDescendantTwo = asMixedAbstractDescendantTwo;
            _asMixedConcreteWithDescendantsChild = asMixedConcreteWithDescendantsChild;
            _asMixedConcreteWithDescendants = asMixedConcreteWithDescendants;
            _asMixedConcreteLeaf = asMixedConcreteLeaf;
        }

        /// <summary>
        /// Get the underlying instance regardless of the concrete case.
        /// </summary>
        public IClass Underlying =>
            _valueKind switch
            {
                ValueKind.MixedAbstractDescendantOne => _asMixedAbstractDescendantOne
                    ?? throw new System.InvalidOperationException(
                        "Unexpected null _asMixedAbstractDescendantOne"),
                ValueKind.MixedAbstractDescendantTwo => _asMixedAbstractDescendantTwo
                    ?? throw new System.InvalidOperationException(
                        "Unexpected null _asMixedAbstractDescendantTwo"),
                ValueKind.MixedConcreteWithDescendantsChild => _asMixedConcreteWithDescendantsChild
                    ?? throw new System.InvalidOperationException(
                        "Unexpected null _asMixedConcreteWithDescendantsChild"),
                ValueKind.MixedConcreteWithDescendants => _asMixedConcreteWithDescendants
                    ?? throw new System.InvalidOperationException(
                        "Unexpected null _asMixedConcreteWithDescendants"),
                ValueKind.MixedConcreteLeaf => _asMixedConcreteLeaf
                    ?? throw new System.InvalidOperationException(
                        "Unexpected null _asMixedConcreteLeaf"),
                _ => throw new System.InvalidOperationException(
                    $"Unexpected value kind: {_valueKind}")
            };

        /// <summary>
        /// Wrap <paramref name="that" /> as an instance of MixedUnion.
        /// </summary>
        public static MixedUnion FromMixedAbstractDescendantOne(IMixedAbstractDescendantOne that)
        {
            return new MixedUnion(
                ValueKind.MixedAbstractDescendantOne,
                that,
                null,
                null,
                null,
                null);
        }

        /// <summary>
        /// Wrap <paramref name="that" /> as an instance of MixedUnion.
        /// </summary>
        public static MixedUnion FromMixedAbstractDescendantTwo(IMixedAbstractDescendantTwo that)
        {
            return new MixedUnion(
                ValueKind.MixedAbstractDescendantTwo,
                null,
                that,
                null,
                null,
                null);
        }

        /// <summary>
        /// Wrap <paramref name="that" /> as an instance of MixedUnion.
        /// </summary>
        public static MixedUnion FromMixedConcreteWithDescendantsChild(IMixedConcreteWithDescendantsChild that)
        {
            return new MixedUnion(
                ValueKind.MixedConcreteWithDescendantsChild,
                null,
                null,
                that,
                null,
                null);
        }

        /// <summary>
        /// Wrap <paramref name="that" /> as an instance of MixedUnion.
        /// </summary>
        public static MixedUnion FromMixedConcreteWithDescendants(IMixedConcreteWithDescendants that)
        {
            return new MixedUnion(
                ValueKind.MixedConcreteWithDescendants,
                null,
                null,
                null,
                that,
                null);
        }

        /// <summary>
        /// Wrap <paramref name="that" /> as an instance of MixedUnion.
        /// </summary>
        public static MixedUnion FromMixedConcreteLeaf(IMixedConcreteLeaf that)
        {
            return new MixedUnion(
                ValueKind.MixedConcreteLeaf,
                null,
                null,
                null,
                null,
                that);
        }

        /// <summary>
        /// Wrap <paramref name="that" /> as an instance of MixedUnion based on
        /// its run-time type.
        /// </summary>
        public static MixedUnion FromUnderlying(IClass that)
        {
            switch (that)
            {
                case IMixedAbstractDescendantOne casted:
                    return FromMixedAbstractDescendantOne(casted);
                case IMixedAbstractDescendantTwo casted:
                    return FromMixedAbstractDescendantTwo(casted);
                case IMixedConcreteWithDescendantsChild casted:
                    return FromMixedConcreteWithDescendantsChild(casted);
                case IMixedConcreteWithDescendants casted:
                    return FromMixedConcreteWithDescendants(casted);
                case IMixedConcreteLeaf casted:
                    return FromMixedConcreteLeaf(casted);
                default:
                    throw new System.ArgumentException(
                        $"Unexpected run-time type for the union MixedUnion: " +
                        $"{that.GetType()}");
            }
        }
    }

    public interface IModelTypedFirst : IClass
    {
        public string SomeProperty { get; set; }
    }

    public class ModelTypedFirst : IModelTypedFirst
    {
        public string SomeProperty { get; set; }

        /// <summary>
        /// Iterate over all the class instances referenced from this instance
        /// without further recursion.
        /// </summary>
        public IEnumerable<IClass> DescendOnce()
        {
            // No descendable properties
            yield break;
        }

        /// <summary>
        /// Iterate recursively over all the class instances referenced from this instance.
        /// </summary>
        public IEnumerable<IClass> Descend()
        {
            // No descendable properties
            yield break;
        }

        /// <summary>
        /// Accept the <paramref name="visitor" /> to visit this instance
        /// for double dispatch.
        /// </summary>
        public void Accept(Visitation.IVisitor visitor)
        {
            visitor.VisitModelTypedFirst(this);
        }

        /// <summary>
        /// Accept the visitor to visit this instance for double dispatch
        /// with the <paramref name="context" />.
        /// </summary>
        public void Accept<TContext>(
            Visitation.IVisitorWithContext<TContext> visitor,
            TContext context)
        {
            visitor.VisitModelTypedFirst(this, context);
        }

        /// <summary>
        /// Accept the <paramref name="transformer" /> to transform this instance
        /// for double dispatch.
        /// </summary>
        public T Transform<T>(Visitation.ITransformer<T> transformer)
        {
            return transformer.TransformModelTypedFirst(this);
        }

        /// <summary>
        /// Accept the <paramref name="transformer" /> to visit this instance
        /// for double dispatch with the <paramref name="context" />.
        /// </summary>
        public T Transform<TContext, T>(
            Visitation.ITransformerWithContext<TContext, T> transformer,
            TContext context)
        {
            return transformer.TransformModelTypedFirst(this, context);
        }

        public ModelTypedFirst(string someProperty)
        {
            SomeProperty = someProperty;
        }
    }

    public interface IModelTypedSecond : IClass
    {
        public string SomeProperty { get; set; }
    }

    public class ModelTypedSecond : IModelTypedSecond
    {
        public string SomeProperty { get; set; }

        /// <summary>
        /// Iterate over all the class instances referenced from this instance
        /// without further recursion.
        /// </summary>
        public IEnumerable<IClass> DescendOnce()
        {
            // No descendable properties
            yield break;
        }

        /// <summary>
        /// Iterate recursively over all the class instances referenced from this instance.
        /// </summary>
        public IEnumerable<IClass> Descend()
        {
            // No descendable properties
            yield break;
        }

        /// <summary>
        /// Accept the <paramref name="visitor" /> to visit this instance
        /// for double dispatch.
        /// </summary>
        public void Accept(Visitation.IVisitor visitor)
        {
            visitor.VisitModelTypedSecond(this);
        }

        /// <summary>
        /// Accept the visitor to visit this instance for double dispatch
        /// with the <paramref name="context" />.
        /// </summary>
        public void Accept<TContext>(
            Visitation.IVisitorWithContext<TContext> visitor,
            TContext context)
        {
            visitor.VisitModelTypedSecond(this, context);
        }

        /// <summary>
        /// Accept the <paramref name="transformer" /> to transform this instance
        /// for double dispatch.
        /// </summary>
        public T Transform<T>(Visitation.ITransformer<T> transformer)
        {
            return transformer.TransformModelTypedSecond(this);
        }

        /// <summary>
        /// Accept the <paramref name="transformer" /> to visit this instance
        /// for double dispatch with the <paramref name="context" />.
        /// </summary>
        public T Transform<TContext, T>(
            Visitation.ITransformerWithContext<TContext, T> transformer,
            TContext context)
        {
            return transformer.TransformModelTypedSecond(this, context);
        }

        public ModelTypedSecond(string someProperty)
        {
            SomeProperty = someProperty;
        }
    }

    /// <summary>
    /// Represent a union of <see cref="IModelTypedFirst" /> and <see cref="IModelTypedSecond" />.
    /// </summary>
    public class ModelTypedUnion
    {
        private enum ValueKind
        {
            ModelTypedFirst,
            ModelTypedSecond
        }

        private readonly ValueKind _valueKind;
        private readonly IModelTypedFirst? _asModelTypedFirst;
        private readonly IModelTypedSecond? _asModelTypedSecond;

        private ModelTypedUnion(
            ValueKind valueKind,
            IModelTypedFirst? asModelTypedFirst,
            IModelTypedSecond? asModelTypedSecond)
        {
            _valueKind = valueKind;
            _asModelTypedFirst = asModelTypedFirst;
            _asModelTypedSecond = asModelTypedSecond;
        }

        /// <summary>
        /// Get the underlying instance regardless of the concrete case.
        /// </summary>
        public IClass Underlying =>
            _valueKind switch
            {
                ValueKind.ModelTypedFirst => _asModelTypedFirst
                    ?? throw new System.InvalidOperationException(
                        "Unexpected null _asModelTypedFirst"),
                ValueKind.ModelTypedSecond => _asModelTypedSecond
                    ?? throw new System.InvalidOperationException(
                        "Unexpected null _asModelTypedSecond"),
                _ => throw new System.InvalidOperationException(
                    $"Unexpected value kind: {_valueKind}")
            };

        /// <summary>
        /// Wrap <paramref name="that" /> as an instance of ModelTypedUnion.
        /// </summary>
        public static ModelTypedUnion FromModelTypedFirst(IModelTypedFirst that)
        {
            return new ModelTypedUnion(
                ValueKind.ModelTypedFirst,
                that,
                null);
        }

        /// <summary>
        /// Wrap <paramref name="that" /> as an instance of ModelTypedUnion.
        /// </summary>
        public static ModelTypedUnion FromModelTypedSecond(IModelTypedSecond that)
        {
            return new ModelTypedUnion(
                ValueKind.ModelTypedSecond,
                null,
                that);
        }

        /// <summary>
        /// Wrap <paramref name="that" /> as an instance of ModelTypedUnion based on
        /// its run-time type.
        /// </summary>
        public static ModelTypedUnion FromUnderlying(IClass that)
        {
            switch (that)
            {
                case IModelTypedFirst casted:
                    return FromModelTypedFirst(casted);
                case IModelTypedSecond casted:
                    return FromModelTypedSecond(casted);
                default:
                    throw new System.ArgumentException(
                        $"Unexpected run-time type for the union ModelTypedUnion: " +
                        $"{that.GetType()}");
            }
        }
    }

    public interface ISomething : IClass
    {
        public StructuralUnion StructuralProperty { get; set; }

        public MixedUnion MixedProperty { get; set; }

        public ModelTypedUnion ModelTypedProperty { get; set; }

        public List<StructuralUnion> ListStructuralProperty { get; set; }

        public List<MixedUnion> ListMixedProperty { get; set; }

        public List<ModelTypedUnion> ListModelTypedProperty { get; set; }

        public (StructuralUnion, MixedUnion, ModelTypedUnion) TupleProperty { get; set; }

        public StructuralUnion? OptionalStructuralProperty { get; set; }

        public MixedUnion? OptionalMixedProperty { get; set; }

        public ModelTypedUnion? OptionalModelTypedProperty { get; set; }
    }

    public class Something : ISomething
    {
        public StructuralUnion StructuralProperty { get; set; }

        public MixedUnion MixedProperty { get; set; }

        public ModelTypedUnion ModelTypedProperty { get; set; }

        public List<StructuralUnion> ListStructuralProperty { get; set; }

        public List<MixedUnion> ListMixedProperty { get; set; }

        public List<ModelTypedUnion> ListModelTypedProperty { get; set; }

        public (StructuralUnion, MixedUnion, ModelTypedUnion) TupleProperty { get; set; }

        public StructuralUnion? OptionalStructuralProperty { get; set; }

        public MixedUnion? OptionalMixedProperty { get; set; }

        public ModelTypedUnion? OptionalModelTypedProperty { get; set; }

        /// <summary>
        /// Iterate over all the class instances referenced from this instance
        /// without further recursion.
        /// </summary>
        public IEnumerable<IClass> DescendOnce()
        {
            yield return StructuralProperty.Underlying;

            yield return MixedProperty.Underlying;

            yield return ModelTypedProperty.Underlying;

            foreach (var anItem in ListStructuralProperty)
            {
                yield return anItem.Underlying;
            }

            foreach (var anItem in ListMixedProperty)
            {
                yield return anItem.Underlying;
            }

            foreach (var anItem in ListModelTypedProperty)
            {
                yield return anItem.Underlying;
            }

            yield return TupleProperty.Item1.Underlying;

            yield return TupleProperty.Item2.Underlying;

            yield return TupleProperty.Item3.Underlying;

            if (OptionalStructuralProperty != null)
            {
                yield return OptionalStructuralProperty.Underlying;
            }

            if (OptionalMixedProperty != null)
            {
                yield return OptionalMixedProperty.Underlying;
            }

            if (OptionalModelTypedProperty != null)
            {
                yield return OptionalModelTypedProperty.Underlying;
            }
        }

        /// <summary>
        /// Iterate recursively over all the class instances referenced from this instance.
        /// </summary>
        public IEnumerable<IClass> Descend()
        {
            yield return StructuralProperty.Underlying;

            // Recurse
            foreach (var anItem in StructuralProperty.Underlying.Descend())
            {
                yield return anItem;
            }

            yield return MixedProperty.Underlying;

            // Recurse
            foreach (var anItem in MixedProperty.Underlying.Descend())
            {
                yield return anItem;
            }

            yield return ModelTypedProperty.Underlying;

            // Recurse
            foreach (var anItem in ModelTypedProperty.Underlying.Descend())
            {
                yield return anItem;
            }

            foreach (var anItem in ListStructuralProperty)
            {
                yield return anItem.Underlying;

                // Recurse
                foreach (var anotherItem in anItem.Underlying.Descend())
                {
                    yield return anotherItem;
                }
            }

            foreach (var anItem in ListMixedProperty)
            {
                yield return anItem.Underlying;

                // Recurse
                foreach (var anotherItem in anItem.Underlying.Descend())
                {
                    yield return anotherItem;
                }
            }

            foreach (var anItem in ListModelTypedProperty)
            {
                yield return anItem.Underlying;

                // Recurse
                foreach (var anotherItem in anItem.Underlying.Descend())
                {
                    yield return anotherItem;
                }
            }

            yield return TupleProperty.Item1.Underlying;

            // Recurse
            foreach (var anItem in TupleProperty.Item1.Underlying.Descend())
            {
                yield return anItem;
            }

            yield return TupleProperty.Item2.Underlying;

            // Recurse
            foreach (var anItem in TupleProperty.Item2.Underlying.Descend())
            {
                yield return anItem;
            }

            yield return TupleProperty.Item3.Underlying;

            // Recurse
            foreach (var anItem in TupleProperty.Item3.Underlying.Descend())
            {
                yield return anItem;
            }

            if (OptionalStructuralProperty != null)
            {
                yield return OptionalStructuralProperty.Underlying;

                // Recurse
                foreach (var anItem in OptionalStructuralProperty.Underlying.Descend())
                {
                    yield return anItem;
                }
            }

            if (OptionalMixedProperty != null)
            {
                yield return OptionalMixedProperty.Underlying;

                // Recurse
                foreach (var anItem in OptionalMixedProperty.Underlying.Descend())
                {
                    yield return anItem;
                }
            }

            if (OptionalModelTypedProperty != null)
            {
                yield return OptionalModelTypedProperty.Underlying;

                // Recurse
                foreach (var anItem in OptionalModelTypedProperty.Underlying.Descend())
                {
                    yield return anItem;
                }
            }
        }

        /// <summary>
        /// Accept the <paramref name="visitor" /> to visit this instance
        /// for double dispatch.
        /// </summary>
        public void Accept(Visitation.IVisitor visitor)
        {
            visitor.VisitSomething(this);
        }

        /// <summary>
        /// Accept the visitor to visit this instance for double dispatch
        /// with the <paramref name="context" />.
        /// </summary>
        public void Accept<TContext>(
            Visitation.IVisitorWithContext<TContext> visitor,
            TContext context)
        {
            visitor.VisitSomething(this, context);
        }

        /// <summary>
        /// Accept the <paramref name="transformer" /> to transform this instance
        /// for double dispatch.
        /// </summary>
        public T Transform<T>(Visitation.ITransformer<T> transformer)
        {
            return transformer.TransformSomething(this);
        }

        /// <summary>
        /// Accept the <paramref name="transformer" /> to visit this instance
        /// for double dispatch with the <paramref name="context" />.
        /// </summary>
        public T Transform<TContext, T>(
            Visitation.ITransformerWithContext<TContext, T> transformer,
            TContext context)
        {
            return transformer.TransformSomething(this, context);
        }

        public Something(
            StructuralUnion structuralProperty,
            MixedUnion mixedProperty,
            ModelTypedUnion modelTypedProperty,
            List<StructuralUnion> listStructuralProperty,
            List<MixedUnion> listMixedProperty,
            List<ModelTypedUnion> listModelTypedProperty,
            (StructuralUnion, MixedUnion, ModelTypedUnion) tupleProperty,
            StructuralUnion? optionalStructuralProperty = null,
            MixedUnion? optionalMixedProperty = null,
            ModelTypedUnion? optionalModelTypedProperty = null)
        {
            StructuralProperty = structuralProperty;
            MixedProperty = mixedProperty;
            ModelTypedProperty = modelTypedProperty;
            ListStructuralProperty = listStructuralProperty;
            ListMixedProperty = listMixedProperty;
            ListModelTypedProperty = listModelTypedProperty;
            TupleProperty = tupleProperty;
            OptionalStructuralProperty = optionalStructuralProperty;
            OptionalMixedProperty = optionalMixedProperty;
            OptionalModelTypedProperty = optionalModelTypedProperty;
        }
    }
}  // namespace dummy

/*
 * This code has been automatically generated by aas-core-codegen.
 * Do NOT edit or append.
 */
