/*
 * This code has been automatically generated by aas-core-codegen.
 * Do NOT edit or append.
 */

using Aas = dummy;  // renamed
using CodeAnalysis = System.Diagnostics.CodeAnalysis;
using Regex = System.Text.RegularExpressions.Regex;

using System.Collections.Generic;  // can't alias
using System.Linq;  // can't alias

namespace dummy
{
    /// <summary>
    /// Verify that the instances of the meta-model satisfy the invariants.
    /// </summary>
    /// <example>
    /// Here is an example how to verify an instance of StructuralFirst:
    /// <code>
    /// var anInstance = new Aas.StructuralFirst(
    ///     // ... some constructor arguments ...
    /// );
    /// foreach (var error in Verification.Verify(anInstance))
    /// {
    ///     System.Console.Writeln(
    ///         $"{error.Cause} at: " +
    ///         Reporting.GenerateJsonPath(error.PathSegments));
    /// }
    /// </code>
    /// </example>
    public static class Verification
    {
        /// <summary>
        /// Hash allowed enum values for efficient validation of enums.
        /// </summary>
        internal static class EnumValueSet
        {

        }  // internal static class EnumValueSet

        [CodeAnalysis.SuppressMessage("ReSharper", "InconsistentNaming")]
        private static readonly Verification.Transformer _transformer = (
            new Verification.Transformer());

        private class Transformer
            : Visitation.AbstractTransformer<IEnumerable<Reporting.Error>>
        {
            [CodeAnalysis.SuppressMessage("ReSharper", "NegativeEqualityExpression")]
            public override IEnumerable<Reporting.Error> TransformStructuralFirst(
                Aas.IStructuralFirst that
            )
            {
                // No verification has been defined for StructuralFirst.
                yield break;
            }

            [CodeAnalysis.SuppressMessage("ReSharper", "NegativeEqualityExpression")]
            public override IEnumerable<Reporting.Error> TransformStructuralSecond(
                Aas.IStructuralSecond that
            )
            {
                // No verification has been defined for StructuralSecond.
                yield break;
            }

            [CodeAnalysis.SuppressMessage("ReSharper", "NegativeEqualityExpression")]
            public override IEnumerable<Reporting.Error> TransformMixedAbstractDescendantOne(
                Aas.IMixedAbstractDescendantOne that
            )
            {
                // No verification has been defined for MixedAbstractDescendantOne.
                yield break;
            }

            [CodeAnalysis.SuppressMessage("ReSharper", "NegativeEqualityExpression")]
            public override IEnumerable<Reporting.Error> TransformMixedAbstractDescendantTwo(
                Aas.IMixedAbstractDescendantTwo that
            )
            {
                // No verification has been defined for MixedAbstractDescendantTwo.
                yield break;
            }

            [CodeAnalysis.SuppressMessage("ReSharper", "NegativeEqualityExpression")]
            public override IEnumerable<Reporting.Error> TransformMixedConcreteWithDescendants(
                Aas.IMixedConcreteWithDescendants that
            )
            {
                // No verification has been defined for MixedConcreteWithDescendants.
                yield break;
            }

            [CodeAnalysis.SuppressMessage("ReSharper", "NegativeEqualityExpression")]
            public override IEnumerable<Reporting.Error> TransformMixedConcreteWithDescendantsChild(
                Aas.IMixedConcreteWithDescendantsChild that
            )
            {
                // No verification has been defined for MixedConcreteWithDescendantsChild.
                yield break;
            }

            [CodeAnalysis.SuppressMessage("ReSharper", "NegativeEqualityExpression")]
            public override IEnumerable<Reporting.Error> TransformMixedConcreteLeaf(
                Aas.IMixedConcreteLeaf that
            )
            {
                // No verification has been defined for MixedConcreteLeaf.
                yield break;
            }

            [CodeAnalysis.SuppressMessage("ReSharper", "NegativeEqualityExpression")]
            public override IEnumerable<Reporting.Error> TransformModelTypedFirst(
                Aas.IModelTypedFirst that
            )
            {
                // No verification has been defined for ModelTypedFirst.
                yield break;
            }

            [CodeAnalysis.SuppressMessage("ReSharper", "NegativeEqualityExpression")]
            public override IEnumerable<Reporting.Error> TransformModelTypedSecond(
                Aas.IModelTypedSecond that
            )
            {
                // No verification has been defined for ModelTypedSecond.
                yield break;
            }

            [CodeAnalysis.SuppressMessage("ReSharper", "NegativeEqualityExpression")]
            public override IEnumerable<Reporting.Error> TransformSomething(
                Aas.ISomething that
            )
            {
                foreach (var error in Verification.Verify(that.StructuralProperty.Underlying))
                {
                    error.PrependSegment(
                        new Reporting.NameSegment(
                            "structuralProperty"));
                    yield return error;
                }

                foreach (var error in Verification.Verify(that.MixedProperty.Underlying))
                {
                    error.PrependSegment(
                        new Reporting.NameSegment(
                            "mixedProperty"));
                    yield return error;
                }

                foreach (var error in Verification.Verify(that.ModelTypedProperty.Underlying))
                {
                    error.PrependSegment(
                        new Reporting.NameSegment(
                            "modelTypedProperty"));
                    yield return error;
                }

                int indexListStructuralProperty = 0;
                foreach (var item in that.ListStructuralProperty)
                {
                    foreach (var error in Verification.Verify(item.Underlying))
                    {
                        error.PrependSegment(
                            new Reporting.IndexSegment(
                                indexListStructuralProperty));
                        error.PrependSegment(
                            new Reporting.NameSegment(
                                "listStructuralProperty"));
                        yield return error;
                    }
                    indexListStructuralProperty++;
                }

                int indexListMixedProperty = 0;
                foreach (var item in that.ListMixedProperty)
                {
                    foreach (var error in Verification.Verify(item.Underlying))
                    {
                        error.PrependSegment(
                            new Reporting.IndexSegment(
                                indexListMixedProperty));
                        error.PrependSegment(
                            new Reporting.NameSegment(
                                "listMixedProperty"));
                        yield return error;
                    }
                    indexListMixedProperty++;
                }

                int indexListModelTypedProperty = 0;
                foreach (var item in that.ListModelTypedProperty)
                {
                    foreach (var error in Verification.Verify(item.Underlying))
                    {
                        error.PrependSegment(
                            new Reporting.IndexSegment(
                                indexListModelTypedProperty));
                        error.PrependSegment(
                            new Reporting.NameSegment(
                                "listModelTypedProperty"));
                        yield return error;
                    }
                    indexListModelTypedProperty++;
                }

                foreach (var error in Verification.Verify(that.TupleProperty.Item1.Underlying))
                {
                    error.PrependSegment(
                        new Reporting.IndexSegment(
                            0));
                    error.PrependSegment(
                        new Reporting.NameSegment(
                            "tupleProperty"));
                    yield return error;
                }
                foreach (var error in Verification.Verify(that.TupleProperty.Item2.Underlying))
                {
                    error.PrependSegment(
                        new Reporting.IndexSegment(
                            1));
                    error.PrependSegment(
                        new Reporting.NameSegment(
                            "tupleProperty"));
                    yield return error;
                }
                foreach (var error in Verification.Verify(that.TupleProperty.Item3.Underlying))
                {
                    error.PrependSegment(
                        new Reporting.IndexSegment(
                            2));
                    error.PrependSegment(
                        new Reporting.NameSegment(
                            "tupleProperty"));
                    yield return error;
                }

                if (that.OptionalStructuralProperty != null)
                {
                    foreach (
                            var error in Verification.Verify(
                                that.OptionalStructuralProperty.Underlying))
                    {
                        error.PrependSegment(
                            new Reporting.NameSegment(
                                "optionalStructuralProperty"));
                        yield return error;
                    }
                }

                if (that.OptionalMixedProperty != null)
                {
                    foreach (
                            var error in Verification.Verify(
                                that.OptionalMixedProperty.Underlying))
                    {
                        error.PrependSegment(
                            new Reporting.NameSegment(
                                "optionalMixedProperty"));
                        yield return error;
                    }
                }

                if (that.OptionalModelTypedProperty != null)
                {
                    foreach (
                            var error in Verification.Verify(
                                that.OptionalModelTypedProperty.Underlying))
                    {
                        error.PrependSegment(
                            new Reporting.NameSegment(
                                "optionalModelTypedProperty"));
                        yield return error;
                    }
                }
            }
        }  // private class Transformer

        /// <summary>
        /// Verify the constraints of <paramref name="that" /> recursively.
        /// </summary>
        /// <param name="that">
        /// The instance of the meta-model to be verified
        /// </param>
        public static IEnumerable<Reporting.Error> Verify(Aas.IClass that)
        {
            foreach (var error in _transformer.Transform(that))
            {
                yield return error;
            }
        }
    }  // public static class Verification
}  // namespace dummy

/*
 * This code has been automatically generated by aas-core-codegen.
 * Do NOT edit or append.
 */
